### ISSUE TITLE
How can we control the ordering of columns in the table view

### ISSUE THREAD

**Issue by phillipjohnston** [marcusolsson/obsidian-projects#103]
### What would you like help with?

How is the column ordering in table view set? I would like to create a consistent ordering across project views, but each project has a slightly different order. Doesn't seem like I can manually reorder, but maybe I missed that!

**Comment by marcusolsson** [comment]
You can't reorder columns yet, but feel free to create an feature request for it!

That being said, ordering should be consistent. I'll look into it!

**Comment by phillipjohnston** [comment]
> That being said, ordering should be consistent. I'll look into it!

My hypothesis is that is matters what order notes are processed in. I have a standard frontmatter format, but there are notes with earlier versions that have not yet been updated, as well as a hodgepodge of inbox notes with various metadata outside the standard.

Questions:

- Does the order get set when the project is first created, or will it be set every time I open a project?
- When recursively processing, does the first folder get processed before the first note in the top-level folder?

**Comment by marcusolsson** [comment]
Closing in favor of #105 (I'll answer you questions there once I've taken a look).
