### ISSUE TITLE
Ability to reorder table columns

### ISSUE THREAD

**Issue by phillipjohnston** [marcusolsson/obsidian-projects#105]
### What would you like to be added?

I would like the ability to control the order of the table columns.

### Why is this needed?

- It appears that the order notes are processed in controls the order of table columns, creating inconsistent orders across projects
- There may be different ideal orderings when looking at metadata in a file vs in the project management table
- Your ideas of what you want to see (and what is prioritized) in the table view may evolve over time

**Comment by marcusolsson** [comment]
Still working on the UI bits, but if you can't wait, you can manually configure the column order in 1.9.0.

More information in #321.

**Comment by MSBack** [comment]
> Still working on the UI bits, but if you can't wait, you can manually configure the column order in 1.9.0.
> 
> More information in #321.

This doesn't work for me. Instead of displaying the columns in the desired order, Projects just resets the data.json folder and deletes the whole configuration upon reopening Obsidian.

**Comment by marcusolsson** [comment]
Sorry about that! I'll look into why the order resets.

**Comment by MSBack** [comment]
> Sorry about that! I'll look into why the order resets.

That's okay, but it's not just the order that resets. If I manually edit the data.json file, Projects will delete **everything** in the file the next time I restart Obsidian. This means all my projects disappear and I have to reconfigure them.
