### ISSUE TITLE
Date Selection Off by One

### ISSUE THREAD

**Issue by MKDJr** [marcusolsson/obsidian-projects#107]
### What happened?

When entering a value in an empty cell in a `date` column, the day prior to the day selected in the calendar GUI is shown as the date listed in the metadata.

https://user-images.githubusercontent.com/61061178/200362584-657d79c8-c932-44b6-bb66-ca1cc436c123.mp4

### What did you expect to happen?

The date selected in the calendar GUI is the same as the date entered into the metadata

### How can we reproduce it (as minimally and precisely as possible)?

In an empty cell of a `date` column, use the calendar to select a date.

### Anything else we need to know?

This is also reflected in the actual page metadata. I have a lot of other plugins installed, so they might be interacting.

### Plugin version

1.0.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment]
I think this might be related to time zones, since I haven't been able to reproduce this on my side. I'll do some more digging.

**Comment by marcusolsson** [comment]
I'm able to reproduce this by setting my time zone to the US west coast.
