### ISSUE TITLE
Drag notes in calendar view

### ISSUE THREAD

**Issue by navakelvin** [marcusolsson/obsidian-projects#108]
### What would you like to be added?

Incredible plugin, Marcus. I have this feature idea:

Drag notes from one day to another in the calendar view.

> PD. Apologies if this is already planned. I have seen an interview on YouTube and apparently it will come in the future.

### Why is this needed?

Easier to reassign expiration dates or dates in general.

**Comment by marcusolsson** [comment]
Thank you for creating this! It's definitely happening!
