### ISSUE TITLE
Color for note pills in calendar view

### ISSUE THREAD

**Issue by navakelvin** [marcusolsson/obsidian-projects#109]
### What would you like to be added?

Color for calendar notes based on a certain tag. That is, imagine how Google Calendar does it: group notes by group, and that group will have a display color in the calendar. I just think that could be the implementation, adding to a group using YAML.

With this you could differentiate between events in the calendar: university exams in one color, meetings in another color, etc.

### Why is this needed?

This idea mostly aesthetic, but perhaps also functional in terms of being able to see the outlook for the month in a visually distinctive way.

**Comment by marcusolsson** [comment]
I think this would make for a great addition! 👍 

Maybe we could add something like a "Calendar"/"Group by" field setting that would take a field of String type. For an initial version, maybe we could have a fixed set of colors?

I don't know when I'll be able to work on this, but I'd be happy to review a pull request!

**Comment by danieltomasz** [comment]
Maybe it might be synergised with the Supercharged links? 
https://github.com/mdelobelle/obsidian_supercharged_links

I requested for support here https://github.com/mdelobelle/obsidian_supercharged_links/issues/160

**Comment by marcusolsson** [comment]
With the filtering functionality released in 1.5.0, I started experimenting with reusing it for setting colors. 

https://user-images.githubusercontent.com/8396880/208913821-020cee42-0a57-4853-a94c-93ca0156deee.mp4

Curious to hear what you think. This would add color support for all the views. This is obviously more complicated than just grouping calendar events by a field, but it would open up more intelligent colors.

**Comment by navakelvin** [comment]
Amazinng Marcus, it's very clever to apply a color based on a filter! It completely fulfills the need to differentiate events/notes and in a great way! 🙌
