### ISSUE TITLE
Support link formats in the Cover field

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/obsidian-projects#112]
### What would you like to be added?

Support for links in the values for the Cover field in Gallery view.

- `[[logo.jpg]]` and `"[[logo.jpg]]"`
- `![[logo.jpg]]` and `"![[logo.jpg]]"`

### Why is this needed?

Based on feedback so far, many users seem to try these formats first, and struggle when they don't work. Supporting these formats also lets the user auto-complete the path.

**Comment by marcusolsson** [comment]
Next release will have support for `[[image.jpg]]`, but `![[image.jpg]]` (with exclamation mark) will have to wait as it would introduce changes to the data model that I'm not certain we'd want at this point. Will revisit it in the future.

**Comment by zenminimalist** [comment]
Just to add: 
I'd love for it to support `[](7-Habits-of-Highly-Effective-People-Covey-Stephen-R.jpg)` as well.
