### ISSUE TITLE
Configure weeks to start on Sunday

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/obsidian-projects#116]
### What would you like to be added?

Make it possible for weeks to start on a Sunday in the Calendar view.

### Why is this needed?

Many countries start their week on a Sunday.

**Comment by apeironian** [comment]
this is a test comment

**Comment by apeironian** [comment]
siick

**Comment by nousernameavailableanymore** [comment]
Wait, what?
I came here to request to start weeks on Monday.
There doesnt seem to be any setting to configure the date format.

Please add setting to configure when week starts.

**Comment by gfpoliva** [comment]
> Wait, what? I came here to request to start weeks on Monday.

@nousernameavailableanymore I think the default starting day is already Monday.

@marcusolsson any updates here? This would be a terrific feature!
