### ISSUE TITLE
Settings Menu

### ISSUE THREAD

**Issue by pwflint** [marcusolsson/obsidian-projects#122]
### What would you like to be added?

A menu for creating various default user settings.

One such setting could be to reverse ctrl+click behavior for opening links or editing YAML data, as mentioned in #78. Other users may have additional settings, feel free to populate below.

### Why is this needed?

Customizable settings allow for better integration into existing user workflows and UX

**Comment by marcusolsson** [comment]
I've managed to do without a Settings tab so far, but I think this is a good example of a preference that should work globally 👍

**Comment by mccorkle** [comment]
I would also love to see the option to expose metadata such as due date, assignee, and #tags from a card on the board view.  Not everyone needs those on that page, but to replace my current kanban board, I'd love to see a little more flexibility on what displays on the card faces.

**Comment by georgziganek** [comment]
I would like a setting to define how dates should be formatted and displayed in the table view, eg, YYYY-MM-DD or MM/DD/YYYY or DD.MM.YYYY

**Comment by marcusolsson** [comment]
I'm closing this issue as I've added a settings menu in 1.5.0 for configuring how to quote strings in front matter.

While there are more ideas on what to customize, let's create more specific issues for the things you'd like to customize so that we can track them individually.
