### ISSUE TITLE
Receiving type error

### ISSUE THREAD

**Issue by MKDJr** [marcusolsson/obsidian-projects#126]
### What happened?

When creating a project for a folder and its subfolders, I see this error:

![image](https://user-images.githubusercontent.com/61061178/201242732-07d96979-99ca-4a20-afb8-8d824dae4e7b.png)

### What did you expect to happen?

The views would load.

### How can we reproduce it (as minimally and precisely as possible)?

I am not entirely sure what is causing this. On my end, I created a new project for a folder and its subfolders.

### Anything else we need to know?

I've tried to troubleshoot this by creating a project for an empty folder and manually adding each note into the folder while watching the table view to see which one is causing the problem, as I originally assumed this was a YAML formatting issue. Unexpectedly, I was able to add all the notes and the views worked fine. It was only when I created a new project using that same folder that the error appeared again.

Notably, it only occurs in some folders, which makes me suspect invalid YAML formatting, but given the above ^, this might not be the case.

### Plugin version

1.0.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment]
Thank you for reporting!

**Comment by marcusolsson** [comment]
Unfortunately, I haven't been able to reproduce this yet. If you (or anyone else) can provide any more information on how I can produce this error, I'll prioritize this.

**Comment by MKDJr** [comment]
I haven't encountered it since one of your more recent updates. I'm not sure if it was update 1.1.0, 1.1.1, or 1.1.2, but I think it was one of those that fixed it.

**Comment by marcusolsson** [comment]
Thanks for letting me know! I'll go ahead and close this one, but will reopen if you encounter it again!
