### ISSUE TITLE
When picking dates with the date picker, the date is wrong.

### ISSUE THREAD

**Issue by ChaseLittlepaws** [marcusolsson/obsidian-projects#127]
### What happened?

If, for example, I select November 16th 2022 as a date for a note, it changes to November 15th. This has happened with several notes of mine. If I manually change it by opening the note and editing the text itself, it works fine.

### What did you expect to happen?

I expected the selected date to remain the one I selected.

### How can we reproduce it (as minimally and precisely as possible)?

I suppose select a date with the date picker and see if the behavior persists.

### Plugin version

1.0.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by MKDJr** [comment]
I believe this will be fixed in the next update! I reported the same thing in issue #107 and Marcus has fixed it :heart:

**Comment by marcusolsson** [comment]
@MKDJr is correct! A fix is coming in the next release (1.1.0).

**Comment by ChaseLittlepaws** [comment]
Wonderful, thank you!
