### ISSUE TITLE
Collaboration with dbfolder

### ISSUE THREAD

**Issue by RafaelGB** [marcusolsson/obsidian-projects#13]
Nice job here @marcusolsson 

I have a similar plugin already published and I think we can maybe join forces to make a bigger project

https://github.com/RafaelGB/obsidian-db-folder

**Comment by marcusolsson** [comment]
Ooh, that looks really cool! I'll make sure to try it out.

I'd be willing to collaborate, though since the two plugins are written in different frameworks (Svelte vs. React), I'm not sure how much of what I've done is reusable.

Would you be interested in integrating them somehow? Let me know if you have other ideas!

**Comment by RafaelGB** [comment]
The strength of your project are the views and I think the dbfolder strength is the dataview integration and sources.

You have a promising plugin for sure!

About to integrated both we need to expose an API and share the same source of data. I am using a yaml as configuration.

**Comment by marcusolsson** [comment]
I think creating a shared API that abstracts away the data would be incredibly powerful. Would be cool if there was a way that this plugin could embed other plugins as views.

For example, the Projects plugin could send an event with a data model, and other plugins could respond with an instance of `ItemView`. Plugins like DBfolder, Fantasy Calendar, and Kanban would be able to work both standalone and with Projects. Hopefully with minimal effort.

**Comment by marcusolsson** [comment]
I'm not using any configuration right now. I'm maintaining a runtime index of all notes and filter them based on the workspace.

**Comment by RafaelGB** [comment]
I will investigate the itemView object once I start with the API issue :)

I suggest to use dataview models as reference of those future APIs. I amHappy to share ideas with you ane surely I can help you at least with the table view issues

**Comment by marcusolsson** [comment]
I'll look into inter-plugin communication and the dataview API.

**Comment by marcusolsson** [comment]
Closing in favor of #27
