### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by xverbatim1971** [marcusolsson/obsidian-projects#131]
### What happened?

hello,
I have created a board view and have different status displays.
when i click on a note here and i

 want to change something in the status, obisidan freezes completely ...

![freeze](https://user-images.githubusercontent.com/116034938/201319965-617b0ea6-cadf-4636-a5f7-f6bc0de24a5a.png)

### What did you expect to happen?

that the status can be changed

### How can we reproduce it (as minimally and precisely as possible)?

i have several notes in the subfolder. if each note has a status and you have changed it?

### Plugin version

1.1.0

### Obsidian version

1.0.3 (Installer V. 0.15.9)

### OS

Windows

**Comment by marcusolsson** [comment]
Seems like the date input is the culprit. It ends up updating itself in an infinite loop when the record changes. Working on a fix.

**Comment by marcusolsson** [comment]
Let me know if the issue persists! 🙏

**Comment by xverbatim1971** [comment]
> Let me know if the issue persists! 🙏

thank you for the quick reply and the error correction.
so far everything is running well.

thank you and please continue :-)
great plugin 
good work
