### ISSUE TITLE
[Board/Kanban View] Drag notes between columns

### ISSUE THREAD

**Issue by dartungar** [marcusolsson/obsidian-projects#133]
### What would you like to be added?

I may have missed or misconfigured something, but it seems that we can't drag notes in Board view from one column to another (changing its 'status') field.

So, the feature is this: drag & drop notes between columns in Board view to update its status field.

### Why is this needed?

Dragging cards between columns is a staple for any Kanban-style board.

**Comment by marcusolsson** [comment]
Thanks for creating this! I actually have some work in progress already, but I still have some ways to go. It's definitely a must-have.

**Comment by MelGrubb** [comment]
I'm very interested in this as well, but I have a question. As I understand it now, the columns on the board come directly from the list of values found on the notes. Doesn't that mean that a column would completely disappear if there were no notes in that state? If so, how could I drag a note to that state?

I get that it's basically using the existing data as its only source right now, and that this means a master list of those status values would have to exist somewhere. This means additional metadata about the board itself that isn't purely stored on the notes, and I'm not sure how to feel about that. One of my reasons for using Obsidian is that my notes are good forever regardless of the editor, and I suppose that's still true. I could still see that Note A is "In Progress", but I can't tell that "In Review" is the next step from looking solely at Note A. It's that permanence that needs a home, preferably one that's just another markdown file that says "Kanban board goes here" with a human-readable explanation of what the columns are, what order they go in, and what order their _items_ are sorted in.

**Comment by marcusolsson** [comment]
@MelGrubb You're absolutely right 💯 The way I see it, there's two approaches here.

1. Store master list in notes: Assumes that valid options are part of the data. Would require some custom parsing of Markdown notes.
2. Store master list in view: Assumes that valid options are for visual aid: Most likely you'd configure a set of persistent columns in the view settings. Maybe a shortcut to "pin" each column.

The latter would have the least impact on notes, so I'm leaning to that one.

**Comment by MelGrubb** [comment]
For #1, if you defined the entire list in each note, how would you deal with possible mismatches? If I add a new status, does it have to then update _all_ the notes to include it? Part of me would like to see note-based projects where there's a human-readable markdown document that describes the views, similar to how the Kanban board plugin works. That markdown is interesting to look at, but only in a "Hmmm, that's interesting" way. I can't see myself ever using that document directly, although it _does_ give you the opportunity to purposefully place multiple boards wherever you want them. Click on note, see board. If you don't have the plugin, then you see a markdown document that you can still make some sense of.

#2 is the most flexible, puts the information under _your_ control, and keeps it out of the hands of humans who often fiddle with things that they don't understand. It's your most powerful option, but less in line with Obsidian's general vibe of "text files are forever".
