### ISSUE TITLE
When I use projects to edit yaml items, the yaml area format is broken

### ISSUE THREAD

**Issue by Alex-coder251** [marcusolsson/obsidian-projects#134]
### What happened?

I add a tag to my note, then tae yaml area format of the note will be broken.

1. here is my note: ![image](https://user-images.githubusercontent.com/58896036/201359135-b3202a12-414d-4d7f-aeec-3c2a61686f31.png)

2. then I add a tag to my note: ![image](https://user-images.githubusercontent.com/58896036/201359790-9aa0ef89-4562-47b6-99c0-238ab6658705.png)
3. then I go back to my note: 
![image](https://user-images.githubusercontent.com/58896036/201360304-9356f146-0204-48d0-99a9-bce7687140bc.png), you will find there are something wrong in my note.
4. last I go back to project, projects is broken too😂: 
![image](https://user-images.githubusercontent.com/58896036/201361060-e76da0f6-3ec6-4a8d-a13f-4fe7c6a25ccb.png)

### What did you expect to happen?

projects should be a uniformly modify the interface of yaml items.

### How can we reproduce it (as minimally and precisely as possible)?

Just try to edit items in projects.

### Plugin version

1.1.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment]
Thank you for reporting this (and for the helpful examples)! 🙏 I'll get right on this.

**Comment by marcusolsson** [comment]
I couldn't reproduce the exact error, but it seems to be related to breaking long strings. I've disabled it for now, which should hopefully fix the issue. 

Could you try the newly released 1.1.2? If it doesn't fix it, could you share the exact front matter as text so that I can copy-paste it into the test suite?

**Comment by Alex-coder251** [comment]
thank you so much! the problem has been resolved
