### ISSUE TITLE
Same icon as workspace core plugin

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#138]
### What happened?

Your plugin sidebar icon has the same icon as the workspace core plugin, which makes things confusing.

### What did you expect to happen?

Have a different unique icon to differentiate this plugin's icon from the other icons

### How can we reproduce it (as minimally and precisely as possible)?

Activate workspace core plugin with projects plugin.

### Anything else we need to know?

https://user-images.githubusercontent.com/38974541/201399387-92edc4e5-56b6-437f-9358-ee8051a033fe.mov

### Plugin version

1.1.0

### Obsidian version

1.0.3

### OS

macOS

**Comment by marcusolsson** [comment]
I'm hesitant to change this. Firstly, because I think it's actually fits the plugin. Second, because any (good) icon will likely result in a conflict with another plugin, unless we make a custom one.

If anyone has a suggestion on a better icon, please suggest it in a comment. If it receives a decent amount of reactions, I'll consider it. That being said, people who are happy with the current one probably won't vote :)

**Comment by Acylation** [comment]
Now we have icon 'Layout', which conflicts with the core plugin 'workspace'.
![layout](https://user-images.githubusercontent.com/73122375/202070884-47477b30-3add-4ce4-a6cd-ae2f85cf6d21.png)
Actually the icon 'table-2' will do better. Please notice that the vertical line in this icon cross through the horizontal one and connected to the top, the same as the icon of github projects tab
![table-2](https://user-images.githubusercontent.com/73122375/202069724-3e36195a-b3f2-409b-90ff-9b8e72020303.png)

Though I don't think this icon distinguishable lol

**Comment by marcusolsson** [comment]
Thanks for the suggestions! Ideally I don't want to favor any of the views, i.e. no table, calendar, board, etc.

I'd be willing to switch to table-2, but like you say, it's not that much of a difference.

The checkmarks are better, though it may give the impression of a task/todo plugin. I could see something like `clipboard-check` working though.

Though cliché, I could also imagine something like a bullseye, for "hitting your targets".

<img width="89" alt="CleanShot 2022-11-16 at 10 46 03@2x" src="https://user-images.githubusercontent.com/8396880/202146567-8d43fafa-9859-411b-b342-9650879146b6.png">

(I don't like the `target` icon in lucide though. It doesn't have the arrow so it's just some concentric circles.)

**Comment by Acylation** [comment]
As the plugin have a unique icon in introduction page now, shall we update the ribbon icon as well?
