### ISSUE TITLE
Hide "DB folder" config file

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#141]
### What would you like to be added?

When adding a DB folder view, the plugin creates a file `33450fb7-3980-41f3-b6b9-46602fa44063_db` in the folder. 
The DB folder view hides this file, but the other views don't. Could you hide it in all the views?

### Why is this needed?

Because we don't need to see the db file in the other views.

**Comment by marcusolsson** [comment]
Sounds like this would be solved with #93, so I'm marking this as duplicate.
