### ISSUE TITLE
Request for localized or user-defined date format

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#153]
### What would you like to be added?

Would you mind provide a configuration choice allow users to adapt the local setting of date fromat? Particularly in the Table View.

### Why is this needed?

Now date is displayed in the form of "MM/DD/YYYY", while the format “DD/MM/YYYY” and "YYYY/MM/DD" are also widely used. Though I can get used to it, somehow it is not that clear. I would be confused by M/D sometimes.

**Comment by marcusolsson** [comment]
It _should_ pick the date format from the locale on your laptop. If it doesn't, I'd consider that a bug rather than a feature.

In case you'd like to override the local format, we could add a preference setting. This would only change the display format of dates, not how the date is parsed.

**Comment by Acylation** [comment]
The calendar widget applied my locale setting, that's ture. But in table view, it keeps the "MM/DD/YYYY" format. I should have made a more detailed description, thx.
Here's the screenshots
<img width="200" alt="image" src="https://user-images.githubusercontent.com/73122375/202172102-9f8c5f15-f0b8-48da-bc9b-a1188a27246d.png"><img src="https://user-images.githubusercontent.com/73122375/202170030-e5a100d1-f22e-4097-ab18-0778c02bf970.png" width = "300"/>

**Comment by marcusolsson** [comment]
Changing to bug, as they should both display the format for your current locale.

**Comment by Acylation** [comment]
Obsidian: v1.0.3
Projects Plugin: v1.2.0
OS: Windows
Time zone & Locale: UTC+8, zh_CN
Reproduce: create a table view containing notes with a date field and value

Thanks for your response.

**Comment by Johan1974** [comment]
Hello, 

I have some issues with date fields too and now tried a couple of formats

Datum:     01-03-2023
Datum2:   2023-03-01
Datum3:   2023/03/01

First none of them were detected as a date.After a restart only Datum2 was detected as a date. 

Did the console check and got this 

new Intl.DateTimeFormat().format(new Date());
'1-3-2023'

Now i know this i can simply add an extra tag with the correct format.
But i was wondering if there was a way to also recognize the other date formats?

Greetings,

Johan

**Comment by Acylation** [comment]
Hi @Johan1974 , you're right, for now the Projects plugin only recognizes YYYY-MM-DD format in the markdown fields (refer to discussion #309 ), and displays dates according to your locale setting. 

> But i was wondering if there was a way to also recognize the other date formats?
This would be satisfied by submitting a feature request. As the resources are limited, the feature may not be prioritized. 

By the way, there's an issue (#430 ) waiting for triaging related to the display format settings for date fields.

**Comment by jrcloutier** [comment]
Forgive what is likely a very dumb question from someone new to programming, but how do I change the date display to YYYY-MM-DD? When I type `new Intl.DateTimeFormat().format(new Date());` in  **Developer Tools > Console**, I get `8/9/2023`

<img width="206" alt="Screenshot 2023-08-09 at 1 38 36 PM" src="https://github.com/marcusolsson/obsidian-projects/assets/16066872/51b66e0d-cc19-43e5-8d00-a640a6d2c35d">

**Comment by Acylation** [comment]
For now there's no way for the plugin to config the locale. You may try to change your system locale, and restart the Obsidian app as well as the Projects plugin to see if there's any difference. (This did nothing on my laptop, my win10 OS only supports one display language, and the Obsidian kept recognizing my locale as `zh-CN`)

If you want to config the display format, there will be two ways to support it.
- Use `moment.locale()` to determine the format, and you can config this by changing Obsidian display language
- Provide options to config the display format in Projects plugin, and you can adjust this in the plugin setting tab

---

The language and locale of Obsidian and plugins are little bit in chaos I would say...
- Projects plugin uses `Intl` api to format the date, which further requires `Date()` api 
- Obsidian app uses the `window.navigator.language` to get OS locale and feeds it into the `Date()` default
- If you change the display language of Obsidian app in `Settings->About`, it will affects the `moment.locale()`
- `moment.locale()` would be also affected by the community plugin `Calendar`, but it is also widely used by plugins to determine the i18n language
