### ISSUE TITLE
YAMLParseError: Unexpected flow-seq-start at node end

### ISSUE THREAD

**Issue by ruanwz** [marcusolsson/obsidian-projects#160]
### What happened?

The latest version 1.2 has following error after creating a new note using template with double quotes in yaml meta data when open projects windows:

plugin:obsidian-projects:21418 Uncaught (in promise) YAMLParseError: Unexpected flow-seq-start at node end at line 12, column 40:

  - "[[<%tp.file.title%>#Summary|📝]] "[[<%tp.file.title%>#Ideas|💡]]" [[<%tp.f…
                                       ^

### What did you expect to happen?

The older version doesn't has this error. 
If I remove double quotes, or replace with single quote, the project window is opened correctly.

### How can we reproduce it (as minimally and precisely as possible)?

use a template include text has double quotes in meta data:

```
headings:
  - "[[testmeet3 note#Summary|📝]] [[testmeet3 note#Ideas|💡]] [[testmeet3 note#Attendees|🧑‍🤝‍🧑]]"
```

### Plugin version

1.2.0

### Obsidian version

1.0.3

### OS

macOS

**Comment by ruanwz** [comment]
this issue can be fixed by changing the array of strings style to:

```
- ['[[<%tp.file.title%>#Summary|📝]]','[[<%tp.file.title%>#Ideas|💡]]','[[<%tp.file.title%>#Top 3 Quotes|💬]]']
- ['[[<%tp.file.title%>#Future Plans|📆]]','[[<%tp.file.title%>#Thoughts|💭]]','[[<%tp.file.title%>#Author Purpose|🏁]]']
```

**Comment by marcusolsson** [comment]
Thank you for reporting this! I've opened a PR with a failing regression test for now.

**Comment by ruanwz** [comment]
Thanks for the fix. Now the project doesn't show the YAML parseError. But the YAML is still invalid. I think it is because that when using the template, the single quote is removed in final note.

For now, I need to change the template like 
```
headings: "'[[<% tp.file.title %>#Summary|📝]][[<% tp.file.title %>#Ideas|💡]][[<% tp.file.title %>#Attendees|🧑‍🤝‍🧑]][[<% tp.file.title %>#Future Plans|📆]][[<% tp.file.title %>#Thoughts|💭]][[<% tp.file.title %>#Next Actions|🛫]]'"
```
Then if I use it in templater, it generates
```
headings: "'[[2022-11-19 testmeet2#Summary|📝]][[2022-11-19 testmeet2#Ideas|💡]][[2022-11-19 testmeet2#Attendees|🧑‍🤝‍🧑]][[2022-11-19 testmeet2#Future Plans|📆]][[2022-11-19 testmeet2#Thoughts|💭]][[2022-11-19 testmeet2#Next Actions|🛫]]'"
```
when use in projects's template, it generates
```
headings: '[[Untitled note#Summary|📝]][[Untitled note#Ideas|💡]][[Untitled note#Attendees|🧑‍🤝‍🧑]][[Untitled note#Future Plans|📆]][[Untitled note#Thoughts|💭]][[Untitled note#Next Actions|🛫]]'
```

I think it is caused by the difference between templater and template in projects. For some reason, template in projects always remove single quote.

I currently use single quote in double quotes, it can some how make it works in both templater and projects template.
