### ISSUE TITLE
Sorting behavior affects editing in table view unexpectedly

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#163]
### What happened?

When editing a sorted number cell, like priority, if it's position will change after sorting, something strange happend. The cursor/activated cell stays while the item has been moved. Further edit will affect another cell, which substitutes the former one.

Here's the recording. The priority column is sorted "from A to Z", and other fields are added to make the position switching more obvious. 

When decreasing the priority of item1, from 1 to 3, its position would change. Then I typed multiple "1" continuously. As the number grows, the items are activated alternately.

https://user-images.githubusercontent.com/73122375/202772193-97f4edbc-2656-401c-ae24-93061fe19fa8.mp4

### What did you expect to happen?

Solution 1, sort after exiting edit mode. Text field acts like this
Solution 2, sort while editing, but let the cursor and activate cell follow

### How can we reproduce it (as minimally and precisely as possible)?

Create a project contains a number field, sort it in table view, then edit a cell with a input which will change it's order.

### Anything else we need to know?

Here's my test case

**Item1.md**
```YAML
Priority: 1
Due: 2022-11-30
Status: Finished
Finished: true
```
**Item2.md**
```YAML
Priority: 2
Due: 2022-12-31
Status: Unplanned
Finished: false
```

**Project setting**

<img src="https://user-images.githubusercontent.com/73122375/202774662-a56513fb-be45-4fa7-9a12-6d07c76be7e8.png" width = 400 />

### Plugin version

1.2.0

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment]
Thanks for reporting! I can reproduce. That's indeed a rather interesting bug 😅
