### ISSUE TITLE
[BUG] Change file daily note's file name to something else causes triple events

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#17]
Related to #16 

# How to repro:

1. Create a daily note with name like `2022-09-01`
2. Set yaml with `date: 2022-09-01`
3. Change name for test.
4. Return to the calendar view, you will see the triple events.

Suggestion: need to 

![图片](https://user-images.githubusercontent.com/13215013/187818701-a8649320-4b83-4326-a227-3228c5caaf78.png)
![图片](https://user-images.githubusercontent.com/13215013/187818745-bd3f9319-9ccb-4f4d-9951-d4351356832c.png)

**Comment by marcusolsson** [comment]
Thank you for reporting these! I'll get right on it!
