### ISSUE TITLE
hiding dbfolder note?

### ISSUE THREAD

**Issue by xverbatim1971** [marcusolsson/obsidian-projects#170]
### What would you like to be added?

hi,
thank you for the great work.

one question.
is it possible to hide the database folder note in the table/cover or board view? it is unsightly when i see it :-)

maybe you can hide it somehow?
i have not found anything :-)
![hide](https://user-images.githubusercontent.com/116034938/202857328-c29be3d7-7a65-4e54-a56a-bcad3ff1d777.png)

### Why is this needed?

better overview

**Comment by danieltomasz** [comment]
Hi @xverbatim1971  could you add these notes in the excluded notes in the project settings?

**Comment by xverbatim1971** [comment]
hi,

thanks for the answer.

now i understand the option in project setting :-)
my english is not so good...

yes, i can hide the note here...
thanks 

good work... 
and please keep it up, that plugin is so helpful and useful.

**Comment by xverbatim1971** [comment]
i just noticed that in the database folder view, i can't hide the note here, even though i have hidden it in the project settings....
bug?
or is there another setting in the database folder view?

**Comment by marcusolsson** [comment]
This is a known limitation of DB folder right now, but the author is working on it! Check out the improvements coming in this [this issue](https://github.com/RafaelGB/obsidian-db-folder/issues/592).
