### ISSUE TITLE
Project-level setting to include/exclude notes based on tags or other front matter

### ISSUE THREAD

**Issue by MelGrubb** [marcusolsson/obsidian-projects#171]
### What would you like to be added?

Instead of excluding individual notes in the "Edit Project" dialog, I'd like to specify tags to _include_ by specifying a tag list that the Project should pay attention to so that I can control which items appear in lists, boards, and calendars.

### Why is this needed?

I have a lot of supporting documents in my project that are getting included in the table, board, and calendar views. I'm using the "Folder Note" plugin so that each folder in my project has a "ReadMe", which is the main item that I want to track. That folder may contain many supporting documents, drawings, and other files that are _part_ of that item, but are not top-level notes in and of themselves. For instance, Excalidraw notes that support the main note should not appear in the Project view.

If I could add a marker tag to the template for the important top-level notes and tell the Project that these are the only ones it needs to be concerned with, then I could focus its attention on the items I actually want to track and ignore the supporting documents automatically.

Tags to _include_ would be better than tags to _exclude_ because some of the folders in my project represent entire GitHub projects, complete with their own README.md files meant for public consumption, so I can't really "pollute" them with Obsidian front-matter. Maybe my use case is unusual, but I've put Obsidian in charge of the folder structure for entire video projects, including scripting, slides, etc. and it's working pretty well. Obsidian Projects is ideal for what I'm doing as I could eliminate the separate Kanban plugin and track my work items directly.

**Comment by marcusolsson** [comment]
I've been wanting to add support for defining projects based on native Obsidian search queries. Sounds like it would address your use case? Basically, you'd define a query like: `tag:#projects path:Content`. I'm not aware of whether this is possible, but I'll do some research.

**Comment by marcusolsson** [comment]
Found a feature request on the Obsidian repository: https://github.com/obsidianmd/obsidian-api/issues/22.

**Comment by MelGrubb** [comment]
A user-specified query sounds like the most flexible solution, but it also sounds like that might not be available for a while. From the outside, I would have assumed that the API was already exposing something like that. It's amazing what plugin authors have been able to create without it, honestly.

**Comment by marcusolsson** [comment]
Closing in favor #234.
