### ISSUE TITLE
How do I find undefined or null files?

### ISSUE THREAD

**Issue by DannyHatcher-Git** [marcusolsson/obsidian-projects#175]
### What would you like help with?

I am getting this error:
![image](https://user-images.githubusercontent.com/78496825/202907827-9157a2cd-f1e2-42e3-bf9d-b00beb3da044.png)

But I have no idea which files these are in. What is the quickest way to find them to sort them out.
I have tried search but no luck.

**Comment by marcusolsson** [comment]
Thanks for reporting! 🙏 

Are you seeing the error in a particular view, or is it all of them? Are you using Dataview?

Could you open the console in Developer Tools and see if you can find a stack trace that might give a hint of where it originated from?

**Comment by DannyHatcher-Git** [comment]
It is in every view for the notes folder I am using.
Not using dataview.

I don't really know what I would be looking for, is there a guide I could follow?

**Comment by marcusolsson** [comment]
This is on macOS, but I'm sure it's similar on Windows as well.

https://user-images.githubusercontent.com/8396880/202925197-b7a1ed00-ea08-4c46-810b-6352a7e9afc9.mp4

Look for anything with red text in the console tab. Ideally, it should say the same error as your seeing.

**Comment by DannyHatcher-Git** [comment]
I have just taken a screenshot of everything I see.

For reference I have tried 2 projects, 1 with my Journal folder and it works fine, 1 with my notes folder and I get the TypeError.
![image](https://user-images.githubusercontent.com/78496825/202933081-4adbe6d6-e947-4eb9-8355-28015178c675.png)

**Comment by marcusolsson** [comment]
Thank you! I'll do some troubleshooting based on this. If you find the offending note, let me know!

**Comment by DannyHatcher-Git** [comment]
I found out what it was.

There were some notes that had empty frontmatter so projects was reading it as undefined.

So in the page I had
---
---

**Comment by marcusolsson** [comment]
Thank you for that! Confirming that I can reproduce. I'll have a fix for you later today.
