### ISSUE TITLE
Correcting behavior of nullable dates

### ISSUE THREAD

**Issue by usernotnull** [marcusolsson/obsidian-projects#183]
### What happened?

When YAML dates can be null, the field is treated as string instead of date

### What did you expect to happen?

Some dates, such as published_at, can be null instead of having a date. 

The issue is that the field itself cannot be treated as a date anymore, so it won't show in the Calendar View's 'Date' field. The Table View will also treat the fields that have a date as a string instead.

### How can we reproduce it (as minimally and precisely as possible)?

Add a date YAML, with some files having no value.

### Plugin version

1.2.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment]
This is likely an unintended result of previous fix which aimed to fall back to string when all values where null. Thanks for reporting! 🙏
