### ISSUE TITLE
Open notes from board view...

### ISSUE THREAD

**Issue by Deus333** [marcusolsson/obsidian-projects#187]
### Opening notes from the board view

I can't open notes from the board view Is it because there isn't a feature for it or is my knowledge lacking?

**Comment by marcusolsson** [comment]
- If you're on Window or Linux, press Ctrl and click the link.
- If you're on macOS, press Cmd and click the link.

Same thing applies to Calendar and Gallery.

**Comment by puertoric** [comment]
I have the same problem as Deus333 describes. I have several times to click in either view before note does open if at all. (using Obsidian on Windows). Using ctrl and click on the link does not help. Do I miss something?

**Comment by marcusolsson** [comment]
Thank you for confirming! I didn't actually address this explicitly, but I'm glad it got fixed :)

**Comment by puertoric** [comment]
Thank you Marcus. Also for me issue was fixed with the last update this week.
