### ISSUE TITLE
Ordering the Project Selector

### ISSUE THREAD

**Issue by ppmw99** [marcusolsson/obsidian-projects#192]
### What would you like to be added?

I would like to be able to reorder my project list in the project selector box (top left of Project screen)  even the alphabetical sort offered on fields/columns  (  A->Z and Z->A ) would be good.

### Why is this needed?

This would enable me to have my main project   TASKS   at the top and opened by default.

**Comment by marcusolsson** [comment]
Rather than reordering the projects, would a "Make default project" setting work, so that it always opens first?

**Comment by marcusolsson** [comment]
You can revise this issue if you want to, or create a separate as well, whatever works for you!

Thank you for the kind words! ❤️
