### ISSUE TITLE
Error reading notes

### ISSUE THREAD

**Issue by the1gofer** [marcusolsson/obsidian-projects#195]
### What happened?

Trying to create a project from existing files with YAMIL data. 

<img width="992" alt="Screenshot 2022-11-23 at 10 03 07 AM" src="https://user-images.githubusercontent.com/2140724/203606670-71a84617-a8ad-4e38-9331-f12b4c0e8137.png">

### What did you expect to happen?

I expected it to look at the YAMIL already on the notes, and create the project.

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure.  Maybe try URLS in the YAMIL

### Plugin version

1.2.3

### Obsidian version

About Obsidian Version 1.0.3 (Installer 0.15.8)

### OS

macOS

**Comment by marcusolsson** [comment]
Thanks for reporting! Would you mind sharing the (anonymized) front matter that causes the error?

**Comment by the1gofer** [comment]
I think it doesn't like the following:

```
---
aliases: govloanoptions.com
registrar: 
registration-proxy: 
name-server: 
IP: 
URL: http://trkrvb.com/?o=632&a=643&subid=16L200B080822&subid2=&email=ronald.harvy@gmail.com&firstname=Ronald&lastname=Harvy&phone=16022951875&street_address=2644%20S%20Los%20Altos&zip=85202
archive:https://archive.ph/0GC5h
---
```

As I was trying to find the file, I realized that I have folders and subfolders with notes with different headers and it's trying to process them all.   I know you can exclude files.

So I have a structure like this:

Project Folder:
- Thing A folder
-- notes with yamil
-- subfolder for thing related to A
--- notes with yamil
- Thing B folder 

Now it seems like it's going to try to create a project entry for everything it finds with YAMIL.  Is there any way to specify a specific note to use?  Im n this example, I would want to keep the THINGS in the project folder, but I don't neccicarrly need to track all of the subfolders.

**Comment by the1gofer** [comment]
Seems to only be those links in that file.  I removed them and everything works.  Other files seems to have no issues with urls.

**Comment by marcusolsson** [comment]
@Acylation is right, the front matter has malformed YAML. Closing issue since the error is correct.
