### ISSUE TITLE
Board: Drag and drop ordering of columns

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/obsidian-projects#2]

**Comment by promethean** [comment]
Yes please!

**Comment by marcusolsson** [comment]
I have limited experience with the drag and drop web APIs so I'll need to do some reading up on this. 

If anyone is interested in helping out with this, let me know!

**Comment by half-adder** [comment]
I don't have much experience with drag-and-drop either, but it might be useful to look at the kanban plugin, which supports drag-and-drop.

**Comment by marcusolsson** [comment]
I believe the Kanban plugin uses a React library for drag and drop. Since this plugin uses Svelte, I'd need to find a Svelte library, or use the Web APIs directly.
