### ISSUE TITLE
[FR] Projects - Tag Support

### ISSUE THREAD

**Issue by yurijserrano** [marcusolsson/obsidian-projects#201]
### What would you like to be added?

Good Evening @marcusolsson 

I hope you are well

That notes could be filtered by the tag they have.

### Why is this needed?

As the plugin returns all notes specified in the Path, the folder may contain more than one type of note, which is not desired in many scenarios, as can be seen in the image below:

![notag](https://user-images.githubusercontent.com/14169134/203685384-caccb7d6-72b1-4e52-8560-884eb93dea2f.png)

So, filtering notes by tag would help to show only one type of note.

**Comment by Acylation** [comment]
Would filter functions mentioned in issue #80 be helpful?

**Comment by marcusolsson** [comment]
I'm considering adding a third data source that uses native Obsidian search terms to define your project. So you could for example define a project using `tag:#sync path:Synchronicity`. Sounds like it would solve your use case?

**Comment by yurijserrano** [comment]
Good Evening @marcusolsson 

I hope you are well

Regarding this excerpt:

> I'm considering adding a third data source that uses native Obsidian search terms to define your project. So you could for example define a project using tag:#sync path:Synchronicity. Sounds like it would solve your use case?

Yes, it would certainly bring more flexibility to return a certain group of notes.


If you need anything else, just let me know.


Have a wonderful day

**Comment by marcusolsson** [comment]
Closing in favor of #234
