### ISSUE TITLE
"Board: Drag and drop cards" feature not working

### ISSUE THREAD

**Issue by RenanSantos7** [marcusolsson/obsidian-projects#208]
### What happened?

The 1.30 new feature (Board: Drag and drop cards by @marcusolsson) is not working. When I try drag and drop cards, the entire column is moved instead just the card.

### What did you expect to happen?

Drag and drop cards (notes)

### How can we reproduce it (as minimally and precisely as possible)?

Try drag and drop cards.

### Plugin version

1.30

### Obsidian version

1.0.3

### OS

Linux

**Comment by imeed166** [comment]
Is this a duplicate of #205?

**Comment by MelGrubb** [comment]
I think these are separate things. #205 is talking about dragging and dropping as it relates to the priority of items within a single column. This is talking about dragging items from one column to another.

**Comment by RenanSantos7** [comment]
Excuse me, but really is duplication. 

I didn't realize it, but if you set priority, the problem stops happening, as reported in #205
