### ISSUE TITLE
How can I filter "true" and "false" from dataview query? 

### ISSUE THREAD

**Issue by Deus333** [marcusolsson/obsidian-projects#209]
### What would you like help with?

How can I filter "true" and "false" from dataview query? 

WHERE done!= "true"
this command doesn't work....

this is the whole code:
TABLE priority, project, duration, start-date, finish-date, done
FROM #task
WHERE done!= "true"

**Comment by marcusolsson** [comment]
This feels like more of a Dataview question than a Projects question. I'd consult the Dataview docs first and get it working with a Dataview code block. If you get it working that way, but not in Projects, I'll reopen this issue.
