### ISSUE TITLE
Tag based exclusions

### ISSUE THREAD

**Issue by rapatel0** [marcusolsson/obsidian-projects#210]
### What would you like to be added?

Exclusions based on tags (instead of individual exclusions)

### Why is this needed?

When managing files in subfolders currently there are settings to exclude individual files. This quickly becomes untenable in large nested directories. 

Dataview based queries are read-only substantial functionality is removed if using a query to populate the database

**Comment by marcusolsson** [comment]
The Excluded files feature is mostly for handling exceptions at this point. Would [this comment](https://github.com/marcusolsson/obsidian-projects/issues/201#issuecomment-1328132763) solve your use case?

**Comment by rapatel0** [comment]
Yeah other comment will address the request. I'll close this thread
