### ISSUE TITLE
Better Error Info

### ISSUE THREAD

**Issue by rapatel0** [marcusolsson/obsidian-projects#211]
### What would you like to be added?

When there is a YAML error or dataview error that prevents the database from being populated, It would be helpful to know which files are causing the issue or to have a debugger hook

### Why is this needed?

<img width="870" alt="image" src="https://user-images.githubusercontent.com/18704704/204096064-32b82e98-2471-4548-ad0c-18ba31ffb8d4.png">

As shown here There is no way to know which of my 3k files is causing the issue from the error message

**Comment by marcusolsson** [comment]
I think this would be a clear improvement and pretty easy to add 👍
