### ISSUE TITLE
Cannot Enable Plugin on IPad Pro IPadOS 16.1.1

### ISSUE THREAD

**Issue by captorxxv** [marcusolsson/obsidian-projects#212]
### What happened?

Unable to Enable Plugin on IPad Pro IPadOS 16.1.1

### What did you expect to happen?

Ive expected same experience as on desktop 

### How can we reproduce it (as minimally and precisely as possible)?

Just run obsidian on IPad and try to enable Project plugin 

### Plugin version

Pro 12.9

### Obsidian version

Latest 

### OS

macOS

**Comment by marcusolsson** [comment]
I'm able to reproduce this on iPhone as well. I wonder if this might be related to the fact that the plugin uses [lookbehind in regular expressions](https://marcus.se.net/obsidian-plugin-docs/testing/mobile-devices#lookbehind-in-regular-expressions).

**Comment by marcusolsson** [comment]
Could you try 1.4.0 and see if the problem persists?

**Comment by inter1907** [comment]
Unable to Enable Plugin (version 1.4.0) on IPad Pro IPadOS 16.2

**Comment by marcusolsson** [comment]
Thanks for confirming, I'll continue debugging!

**Comment by inter1907** [comment]
thanks for your concern

**Comment by ChristianLempa** [comment]
Same issue on iPhone 13, iOS 16.1.2

**Comment by JoshuaElArbol** [comment]
Same problem :(, I'm looking forward to your solution. I have iPadOS 16.1.1

**Comment by marcusolsson** [comment]
Closing in favor of #161.
