### ISSUE TITLE
Change inline field value in the DB Folder view will create a new YAML value

### ISSUE THREAD

**Issue by lukasmaxsimon** [marcusolsson/obsidian-projects#213]
### What happened?

I use the plugin with a dataview query. 

1. I cant change the values in the table, for example: status from "WIP" to "done", if i use inlinefields. 
2. If i created the DB Folder View i can change the value but then the inline metafield, for example "status::" will be removed an created new as a YAML value. 

### What did you expect to happen?

That i can change the value as an inlinefield in the table view and DB Folder view. 

### How can we reproduce it (as minimally and precisely as possible)?

Use a dataview query with inlinefields and try to change the value of a note in the "DB Folder View". 

### Plugin version

1-3.0

### Obsidian version

1.0.3

### OS

macOS

**Comment by marcusolsson** [comment]
Dataview projects are [readonly](https://github.com/marcusolsson/obsidian-projects#dataview), meaning you can't edit values in notes, only view them.

As for DB folder, I think you're better of asking in the DB folder repository. Closing this for now.

**Comment by lukasmaxsimon** [comment]
Hey, thanks but thats also why i opened that ticket. If i change something on the Database which i created just with the official "DB Folder" Plugin, it works perfectly. So i can change a cell and the inlinefield changes too. So it is possible through the DB Folder.
