### ISSUE TITLE
Can't drag notes between columns in board view

### ISSUE THREAD

**Issue by MelGrubb** [marcusolsson/obsidian-projects#214]
### What happened?

When I try to drag a note from one column to another, it tries to move/reorder the entire column instead.

### What did you expect to happen?

Dragging a single note to another column should change that note's status value so that the note moves to the column it was dropped on.

### How can we reproduce it (as minimally and precisely as possible)?

Create a board view and put notes in more than one column. Try to drag an individual note from one column to another.

### Plugin version

1.3.0

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment]
You're right! I limited drag and drop to when the priority field is set, but you should still be able to change the status even if you can change the priority.

**Comment by MelGrubb** [comment]
I'm confused. My priority field IS set. Both the status and priority fields have values. What am I doing wrong?

**Comment by marcusolsson** [comment]
Hm. That is indeed a bug then. You should definitely be able to sort cards with a priority field set. Is there anyway you could create a screen recording of what you're seeing?

**Comment by MelGrubb** [comment]
Here's a Loom link. The audio is messed up for some reason, but I just created a new project, threw five notes in it with different statuses, set the status and priority drop-downs and then tried to drag a task from one column to another. This is in Edge if that makes a difference.

https://www.loom.com/share/443d796e198745f3b7506a4deb7173d7

**Comment by marcusolsson** [comment]
I don't have a Windows machine unfortunately, so I don't know when I'll be able to reproduce this. If anyone else is seeing this on a different OS, I'll prioritize this. If any Windows devs are seeing this, I'd love help debugging this 🙏

**Comment by Acylation** [comment]
I tested it. The problem occurs when the priority drop-down is sorted by an date field. When using number field to sort, the drag and drop works well. FYI

Windows OS, plugin 1.3.0

**Comment by MelGrubb** [comment]
Ah, a drug interaction between two separate things I need. Nice.

**Comment by marcusolsson** [comment]
Oh yeah, date fields can't be reprioritized. Mostly because the plugin has no way of telling what date to set on the card that was moved. Can I ask what how you'd expect it to work?

**Comment by Acylation** [comment]
Maybe we can make date field invisible in the priority drop-down.

**Comment by marcusolsson** [comment]
This was introduced in #172. Though thinking more about it, maybe it was added a little prematurely. For date fields, it simply becomes a matter of sorting cards rather than prioritizing them. For example, we could enable string fields to sort cards alphabetically, which isn't quite what the feature is about.

**Comment by MelGrubb** [comment]
Date fields WERE invisible in the priority drop-down. That was another issue I had entered.
I would say that when the priority drop-down is set to a date field, you simply disable the ability to drag and drop within a column. I should still be able to drag and drop _between_ columns, just not _within_ a column.

**Comment by mcdebugger** [comment]
I use due date mainly to prioritize so I'm voting also to add ability to move cards between sections even when priority is set to date. So to move cards between sections even if no need to move them withing section itself.
