### ISSUE TITLE
API to support metadata plugin

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#215]
### What would you like to be added?

I opened a FR in [metadata menu plugin](https://github.com/mdelobelle/metadatamenu) repo to support the projects plugin. Because metadata menu adds functionality to dataview table, with multiple types of properties like the table view of projects, but with more features. So I thought that if they could integrate together, they could make the default projects table view more powerful. 

Here is the [issue](https://github.com/mdelobelle/metadatamenu/issues/194#issuecomment-1329662489), the developer is requesting an API to "build the views programmatically". Is this possible?

### Why is this needed?

To make the table view more powerful by using the metadata plugin instead of improving the view yourself.

**Comment by marcusolsson** [comment]
I'm going to need more information about what the metadata plugin needs in terms of API before we can do anything about this. Let's wait and see what the author says in the linked issue.

**Comment by brimwats** [comment]
cc @mdelobelle bc i know he got busy last month and may not have seen this
