### ISSUE TITLE
Include/exclude files from specific views

### ISSUE THREAD

**Issue by oldjove** [marcusolsson/obsidian-projects#218]
### What would you like to be added?

I would like to be able to specify a subset of files to be visible in a specific view. E.g. it would be nice to only see files that are relevant to a specific workflow in a board view. I would imagine that this could be managed via either tags, frontmatter or path (e.g. a "type" key).

UPDATE: Oh, maybe this is already covered by #80. 

### Why is this needed?

Sorry if this has already been requested somewhere. I've seen that a few people have requested the ability to include/exclude files from whole projects, but I'm not sure anyone has mentioned view-specific exclusion just yet.

The use case I'm thinking of is an ethnographic project with different file types: fieldnotes, interview transcripts, personal profiles, etc. Perhaps I want to use a board to track which interviews I've transcribed and coded but I don't need to see all the fieldnotes etc in that view. It would be helpful to specify a frontmatter key, tag or path to include or exclude files.

**Comment by marcusolsson** [comment]
Closing in favor of #80.
