### ISSUE TITLE
[BUG] Yaml date format shows invalid date in project 

### ISSUE THREAD

**Issue by NaturallyAsh** [marcusolsson/obsidian-projects#22]
Hello! I would first like to express my gratitude and appreciation for this wonderful plugin you're developing! 

So, I notice a bug where the plugin is not recognizing my note date format. Although, it does recognize my yaml `created:` date-time format.

**In project:**  
<img width="469" alt="Screen Shot 2022-09-04 at 2 23 03 PM" src="https://user-images.githubusercontent.com/39710346/188328032-155e5acc-1404-4849-a8b2-067eebc32923.png">

**In my note's yaml:**
<img width="281" alt="Screen Shot 2022-09-04 at 2 21 33 PM" src="https://user-images.githubusercontent.com/39710346/188328048-7cb6e117-6422-4df1-99bc-456025e92e3a.png">

P.S. This is the first time I've submitted a github issue. Do I need to add a bug label or something this issue post? Thanks again!

**Comment by marcusolsson** [comment]
Thank you for reporting (and for the kind words)! Right now, the plugin only supports the YYYY-MM-DD format. That being said, your dates should at least show up as text fields, so I'll mark this as a bug still.

**Comment by hrenaud** [comment]
Hi, great job! 👏
About the date format, you should document in the readme the expected format.

Or even add a sample note template.

While I'm at it, I was expecting to see the 3 types of boards directly displayed, I didn't find the `New` button right away, maybe it should be renamed to `Add view`/`New view`...

Renaud

**Comment by marcusolsson** [comment]
Thank you for the feedback! More documentation is coming as soon as the plugin stabilizes. Hopefully I can improve the onboarding experience a bit as well!
