### ISSUE TITLE
Board views showing only existing statuses

### ISSUE THREAD

**Issue by ertugruluyar-github** [marcusolsson/obsidian-projects#221]
### What would you like to be added?

Board views showing only existing statuses.
I defined options for statuses with Templater plugin, would be awesome if you add status to board from "<% tp.system.suggestor%>" even if the value of status not set. Or different way to do this. Could be select list type for table properties.

### Why is this needed?

I have got a project and 14 status for this project. But the board is just showing only the statuses that ı set before.
So ı can't drag and drop between statuses. I have to open the file and rewrite status and this hard because ı use icons and long texts. 

type: <% await tp.system.suggester(["Article", "Master Thesis", "phD Thesis"], ["Article", "Master Thesis", "phD Thesis"]) %>
research-name: "<% tp.file.title %>"
status: <% await tp.system.suggester(["0️⃣💡 İdeas", "1️⃣🤔 Determine Research Topic", "2️⃣🗝️ Determine Research Keywords", "3️⃣🔎 Literature Review", "4️⃣🎯 Write Aims and Sub-aims", "5️⃣🧭 Write Method Section", "6️⃣📜 Select Target Journal/Index", "7️⃣⛔ Write Intro Section", "8️⃣🟰 Write Results Section", "9️⃣💥 Write Discussions Section", "🔟📝 Write Title and Abstract Sections", "1️⃣1️⃣📧 Write Cover Letter",  "1️⃣2️⃣📨 Send To The Editor", "1️⃣3️⃣💯 Reviewing", "1️⃣4️⃣🚀 Published"], ["0️⃣💡 İdeas", "1️⃣🤔 Determine Research Topic", "2️⃣🗝️ Determine Research Keywords", "3️⃣🔎 Literature Review", "4️⃣🎯 Write Aims and Sub-aims", "5️⃣🧭 Write Method Section", "6️⃣📜 Select Target Journal/Index", "7️⃣⛔ Write Intro Section", "8️⃣🟰 Write Results Section", "9️⃣💥 Write Discussions Section", "🔟📝 Write Title and Abstract Sections", "1️⃣1️⃣📧 Write Cover Letter",  "1️⃣2️⃣📨 Send To The Editor", "1️⃣3️⃣💯 Reviewing", "1️⃣4️⃣🚀 Published"]) %>
due: {{date:YYYY-MM-DD}}
is-published: false
cover-image:

**Comment by marcusolsson** [comment]
Thank you for sharing your use case. I'm aware of the issue, and definitely agree we should find a way to address it.

**Comment by danebace** [comment]
"Show empty lists" option could be on the board configuration. Below that could be an empty space to fill the possible "status" alternatives. This could be done with ";" to separate.
(e.g: To do; Doing; Done). Any other diferent status chosen on the note that didn't match the options would still make an additional list.
![Uploading SHow empry lists on Projects plugin.png…]()

**Comment by danebace** [comment]
Im new on git hub and don't know how to had the thumbs up to this feature :/

**Comment by ertugruluyar-github** [comment]
I use MetadataMenu plugin, maybe you can implement like that.

**Comment by marcusolsson** [comment]
Thank you for all the tips and inspiration!

I had some time to experiment with this. This would introduce a modal for field configuration. Each field would be able to have user-defined configuration that complements the data in the Markdown.

Here's a prototype:

https://user-images.githubusercontent.com/8396880/209584679-80297c7f-0546-4ee5-870c-6e0de656a9df.mp4

Up until now, all field configuration is detected from the note. This would introduce the ability to complement the front matter supporting field information without bloating the note.

I imagine this could be further extended to configure things like multiple date formats within the same notes.

Let me know what you think!

**Comment by metaember** [comment]
not op but I think this is a great solution

**Comment by ertugruluyar-github** [comment]
Metadata Mneu very powerful plugin ı guess, maybe Projects plugin can collaborate with Metadata Menu plugin.
