### ISSUE TITLE
Empty new project window on android

### ISSUE THREAD

**Issue by Yyote** [marcusolsson/obsidian-projects#223]
When I push the new project button, an empty window with only a cross(for closing) appears. Obsidian continues to work and when I push "back" button the note window opens the previous note. Except that I can only tap outside the window to close it.

**Comment by marcusolsson** [comment]
I unfortunately don't have any Android devices to reproduce this on, nor do I have a idea of why your seeing this. Would love a contribution on this from someone using Android.

**Comment by RobertTalbert** [comment]
Just sharing a screenshot of what I'm getting on my Samsung Galaxy S8+ tablet: 
![image](https://user-images.githubusercontent.com/3129186/205915765-401d0349-f0fe-4cc9-8786-fec854f23cf0.png)

**Comment by tamamu** [comment]
I avoid above error by returning `true` when `platform.default` is not available, then I found another error:
```
plugin:obsidian-projects:46104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'basename')
    at getDisplayName (plugin:obsidian-projects:46104:41)
    at Array.create_default_slot25 (plugin:obsidian-projects:50605:17)
    at create_slot (plugin:obsidian-projects:13508:25)
    at create_fragment21 (plugin:obsidian-projects:19149:24)
    at init (plugin:obsidian-projects:14352:38)
    at new InternalLink (plugin:obsidian-projects:19268:5)
    at create_each_block11 (plugin:obsidian-projects:50636:18)
    at update_keyed_each (plugin:obsidian-projects:14162:15)
    at Object.p (plugin:obsidian-projects:50763:23)
    at update (plugin:obsidian-projects:14015:32)
```
https://github.com/marcusolsson/obsidian-projects/blob/d2770e2732bea9982d031c4b7dd1b337fd1960cf/src/views/Board/components/Board/board-helpers.ts#L83

I'm wordering it is caused by reference `default` property of a module, so I think it may be a problem of building the plugin or the app.

**Comment by marcusolsson** [comment]
Both the `os` and `path` packages are NodeJS packages which are only available in desktop. Working on a fix.

**Comment by marcusolsson** [comment]
Could you try 1.4.0 and see if the problem persists?

**Comment by Yyote** [comment]
> Could you try 1.4.0 and see if the problem persists?

No, it doesn't! Thanks :)
