### ISSUE TITLE
Support portrait images in gallery view

### ISSUE THREAD

**Issue by cstby** [marcusolsson/obsidian-projects#224]
### What would you like to be added?

In gallery view, allow the full image to be viewable on each card. This could be done by setting the image *height* to the size of of the card?

### Why is this needed?

The gallery view currently isn't very useful when using portrait images. 

Below is a screenshot of a portait in Obsidian Projects gallery view.
![image](https://user-images.githubusercontent.com/45189177/205476666-a7b68d93-d72d-4270-9f52-2915ee98edaa.png)

And below is a sceenshot of the same image in Notion gallery view.
![image](https://user-images.githubusercontent.com/45189177/205476675-bf4c673f-0db2-461f-8456-73d88ba6be90.png)

**Comment by marcusolsson** [comment]
I think this should be configurable. For example, here's how Airtable does it:

<img width="362" alt="CleanShot 2022-12-05 at 00 08 17@2x" src="https://user-images.githubusercontent.com/8396880/205521228-42f90f12-69d5-46ba-9291-41a47ef4ff8d.png">

**Comment by marcusolsson** [comment]
Fixed in 1.5.1.
