### ISSUE TITLE
Filter file by Regular Expression

### ISSUE THREAD

**Issue by RTE90** [marcusolsson/obsidian-projects#232]
### What would you like to be added?

Good Morning,
along the lines of the "Include subfolder" option, is it possible to insert the possibility of including in the views only the files that respect a specific regular expression?

### Why is this needed?

For each macro activity to be performed, I create a directory that includes all the files that concern that activity, and I would be interested in filtering only the MOC of that folder.

**Comment by marcusolsson** [comment]
Could be solved using #234?

**Comment by RTE90** [comment]
Yes, it should be helpful! Thanks
