### ISSUE TITLE
UI Treat collections the same using both Dataview and Path Options

### ISSUE THREAD

**Issue by bgk0018** [marcusolsson/obsidian-projects#236]
### What would you like to be added?

First off, thank you for this plugin!
---

Using the file path option for defining a project, I see the following for any given array in the YAML Frontmatter:

![image](https://user-images.githubusercontent.com/1944453/206864913-6ab473bb-b9a8-4c0a-a2a2-237bb766a882.png)

While I imagine it'd be readonly, it'd be great to get the same UI output from the Dataview Query option for defining a project.

As it stands today, it seems that arrays are not natively supported from the Dataview Query option.  I have to use the `join` method to concatenate the array into a string like so:

```
TABLE title as Title, join(tags, ", ") as Tags, join(author, ", ") as Author, cover FROM "graph" WHERE media-type and status = "todo"
```

produces:

![image](https://user-images.githubusercontent.com/1944453/206865007-28507009-ace6-49fe-80bd-d1d1e9806791.png)

### Why is this needed?

I would like to have the power of Dataview query but with some of the quality of life changes you've produced on the file path approach of populating a project.

**Comment by marcusolsson** [comment]
Thank you, this is a bug 🙏
