### ISSUE TITLE
Allow wrapping or stacking of array results in Table

### ISSUE THREAD

**Issue by bgk0018** [marcusolsson/obsidian-projects#237]
### What would you like to be added?

Today, using either the Dataview or Path approaches, collections are single line only.

File Path Example:
![image](https://user-images.githubusercontent.com/1944453/206865173-88aa2afb-f44d-4258-bdc1-908377df2fa6.png)

Using Dataview + join() method:
![image](https://user-images.githubusercontent.com/1944453/206865208-1296aac8-cfd4-441f-bbfe-4ca3c8788859.png)

It would be great if the results of these collections could be stacked or wrapped inside of the column.

### Why is this needed?

In terms of readability for tags, authors, or other collection related metadata, it's much easier (and space efficient) to see these results stacked.

**Comment by marcusolsson** [comment]
I'd like for rows in the table view to have a fixed height normally. When you're editing an array field in the table, it does wrap and expand the whole row.

<img width="244" alt="CleanShot 2022-12-12 at 01 28 12@2x" src="https://user-images.githubusercontent.com/8396880/206938384-543253ac-f19f-4180-a23d-036c5754f498.png">

Would it work for you if the cell expanded when you selected it? To allow wrapping in Dataview projects as well?

**Comment by bgk0018** [comment]
🤔

I don't think I could ask for a 'click to list/wrap' functionality as I don't think I'd use it. That might be something for other users to ask for.

I'm onboard with 'fixed height rows' as default. I think part of the answer here is definitely reorganizing some of my data to not fight the tool by being more succinct.

This may not be the time to tackle this particular issue, but I feel like dealing with length by wrapping and not just hidden overflow will likely come up again (I'm thinking of certain long named Notes such as "{Unique ID} - {Book Title}, {Authors}")

Love your work, thank you for taking the time. I will close for now.
