### ISSUE TITLE
[Bug?]`Clear Record` disappears quickly

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#24]
Like the video below:\

When I right click on a cell to clear record, it disappeared quickly

https://user-images.githubusercontent.com/13215013/188766453-af1f7af9-7f02-4215-a0c0-231c52b0622e.mp4

**Comment by marcusolsson** [comment]
Interesting (thanks for the video)! I can't seem to reproduce it. What environment are you using (OS, Obsidian version, plugin version)?

**Comment by Quorafind** [comment]
```
Obsidian version: 0.16.2
OS: Win 10
Plugin version: 0.8.0
```

And this still happened now.
