### ISSUE TITLE
Calendar doesn't render full width

### ISSUE THREAD

**Issue by jebeaudoin** [marcusolsson/obsidian-projects#240]
### What happened?

When I create and use a calendar view, the calendar does not render in the full width of the tab. It does not matter if I'm using a month, weekly, or daily calendar. The other views (Gallery, Table, etc) work as expected, using the entire tab width. See screen shoot below.

![Screenshot 2022-12-16 at 9 29 23 AM](https://user-images.githubusercontent.com/10992411/208120678-c2c45009-0028-4996-b544-415be901fcd9.png)

### What did you expect to happen?

I expected the calendar to render across the full width of the tab

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new project or open an existing one
2. Create a new calendar view

### Anything else we need to know?

This is happening in two separate vaults, although they have mostly the same set of plugins. I created an empty vault, added Projects, and get the same result. I've looked through the existing issues and can't seem to find a similar experience.

### Plugin version

1.3.0

### Obsidian version

Obsidian Version 1.1.5 (Installer 0.15.6)

### OS

macOS

**Comment by marcusolsson** [comment]
This has already been fixed and will be available in 1.4.0!
