### ISSUE TITLE
View API - increment available height

### ISSUE THREAD

**Issue by RafaelGB** [marcusolsson/obsidian-projects#243]
### What would you like to be added?

To support custom native visual styles, the APIfied views required the entire space of the page

https://user-images.githubusercontent.com/11924043/208297025-56da080d-9289-43ff-a3b2-a8bb254ac42a.mov

There is a `div` which limit the space available for those views

### Why is this needed?

More freedom with the style of the custom views

**Comment by marcusolsson** [comment]
What plugin version did you see this on (I thought I had fixed this in 1.4.0)?

**Comment by RafaelGB** [comment]
with 1.4.0 I am afraid

I am going to improve the integration with all the features introduced with 3.1.0 =)

**Comment by marcusolsson** [comment]
Looking closer, it seems like the other views don't have the view you're referring to.

Could it be this `createDiv()` maybe?

https://github.com/RafaelGB/obsidian-db-folder/blob/bb191db35ba938b33c6082bdb2d7674c34a7663a/src/api/obsidian-projects-api.ts#L108

You should be able to put `height: 100%` on that div to expand to the full space.

**Comment by RafaelGB** [comment]
oh! my bad, been a problem of the 1.3 I though it still persist. Thanks!

I will work on improvements with that implementation 😊

Un saludo
________________________________

**Comment by RafaelGB** [comment]
Commit 11923c3a fixed as custom class
