### ISSUE TITLE
[Bug] Cannot edit cell normally

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#25]
I found I cannot edit some of cells( Like it doesn't have edit mode?)

![projectsBug](https://user-images.githubusercontent.com/13215013/188766800-b6360996-e7a3-4f29-a657-948e2003adc5.gif)

**Comment by Quorafind** [comment]
```
📆日期: 2021-10-27
🥚早饭: [鸡蛋两个,白馒头,蜂蜜糠]
🍛午饭: 
🍨下午茶: // blank|type: text
🥩晚饭: 
🏋️‍♀️健身: 
💪体重: 
```

And the one that can input don't have any yaml yet.

Is this possible that blank yaml field cause this problem?

**Comment by Quorafind** [comment]
I can repro this in Sanbox vault when I have blank yaml fields in note whilte another note has stuff in these yaml fields:

![图片](https://user-images.githubusercontent.com/13215013/189149523-dc5fdded-0918-4166-a90d-727ce412b966.png)

![图片](https://user-images.githubusercontent.com/13215013/189149588-1557a1f3-0287-449a-b05f-c422efb7e89e.png)

**Comment by marcusolsson** [comment]
I can reproduce it with the frontmatter in your example. Seems to be when the property is an empty string.
