### ISSUE TITLE
Date fields within Dataview or Folders mode showing as Text

### ISSUE THREAD

**Issue by profucius** [marcusolsson/obsidian-projects#254]
### What would you like help with?

I'm not certain if I am missing something, or if this is a bug. When I create a Project with a Dataview query, or of a Folder/Subfolders, it is displaying the date frontmatter as a Text field, even though it has a Date within it.

I believe this may be due to the plugin only parsing dates with a specific syntax of YYYY-MM-DD however my dates are in MM/DD/YYYY format, and the Projects plugin does not recognize that as a date field.

Is there currently or in the future any option of configuring the date field to read different date formats? Have I missed something already available?

![image](https://user-images.githubusercontent.com/18254607/208969696-7f4babbf-fb4e-4e55-a22c-43d8dcc48efc.png)
![image](https://user-images.githubusercontent.com/18254607/208969826-38d79827-fc0a-4c84-869c-6f60931e0212.png)

**Comment by marcusolsson** [comment]
You're correct. The plugin only supports ISO8601 dates for now. If this is important to you, feel free to open a feature request 🙏

**Comment by profucius** [comment]
Okay, will do. Would you mind making mention of this ISO8601 restriction somewhere prominent enough (Readme.md?) so that people like myself can avoid losing time testing the plugin before discovering that our date formats aren't compatible yet.

Thank you for your hard work on this plugin, looking forward to seeing where it goes from here. 👍

**Comment by marcusolsson** [comment]
Added a troubleshooting section to the README. Thank you for reporting! 🙏
