### ISSUE TITLE
[FEAT]Hotkey to improve accessibility while editing table

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#26]
`Enter` to edit, and `ctrl+enter` to exit edit mode.
`Up` \ `Down` \ `Left` \ `Right` to move between cells like `tab` and `shift+tab`
`Ctrl+C` & `Ctrl+V` to copy or paste cell.

**Comment by marcusolsson** [comment]
I've been working on this, but unfortunately I've encountered a bug in Svelte that has made this rather tricky. I'll continue to work on it though.

**Comment by marcusolsson** [comment]
I've addressed most of this in 0.16.0, except using the arrow keys (that one's trickier), but I'll create a separate issue for that.
