### ISSUE TITLE
Projects Crashing Obsidian on Startup

### ISSUE THREAD

**Issue by manuelalonso** [marcusolsson/obsidian-projects#270]
Hi,

After installing the plugin I was playing around, created a new project and then the keyboard froze.  I force closed Obsidian.  It will not restart, got stuck in the load screen (with the horizontal line sliding back and forth).

I had to remove the plugin manually editing the community-plugins.json file.  It restarted perfectly.  If I put the plugin back in, Obsidian will again fail to load. 

So... something is deeply wrong in the guts of this promising, interesting plugin. I hope someone finds the issue.  Happy to provide logs or whatever troubleshooting files Marcus wants to see.

**Comment by marcusolsson** [comment]
Thank you for reporting this! I'm sorry for the inconvenience 🙏 

In addition to disabling the plugin, you can try to remove the `.obsidian/plugins/obsidian-projects` folder in your vault, in case the configuration file is corrupt (this will completely remove any projects you've configured).

Just to clarify, the steps you took were:

1. Installed and enabled Projects from Community Plugins in Obsidian.
2. Ran the "Projects: Show projects" command.
3. Selected **Create new project** from the wizard modal.
4. Obsidian froze.

To help debug this, could you please provide the versions of Obsidian and the plugin as well as the OS you're running it on?
