### ISSUE TITLE
Sort by multiple values in all views

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#275]
### What would you like to be added?

Just like the button for `filtering` or `coloring`, add a button for `sorting` that is available for all views, where you can add multiple sorts (either ascending or descending) based on the properties available in the project.

![Screen Shot 2022-12-29 at 10 32 37 AM](https://user-images.githubusercontent.com/38974541/209932462-bc438287-abb9-4729-951e-8529bfc5acdf.png)

### Why is this needed?

There are 3 added values for this feature :
- **You can sort by multiple values.** You're not restricted to just one.
- **It's easier for the user to know where you can sort by values.** Currently, in the table view, it's under the column menu, and in the board view, it's under the priority menu. If you unify them under one button, it would be easier to use.
- **You can enable sorting in other views.** Currently, the calendar, and the gallery view don't have any sorting options available.

**Comment by marcusolsson** [comment]
I love it! It would make for a great addition to the plugin.

The only real issue I see is how the Priority field would work in the Board view. Since the Priority field doesn't just sort, but it also let's you _update_ the priority field by dragging the cards.

Of course, we could always disable the Priority setting if you've configured sorting for the view.

**Comment by kmaustral** [comment]
It would be great at least to be able to reverse the priority order. My priorities are ordered 5 > 1.

**Comment by kmaustral** [comment]
> 
I withdraw that comment about priority order. I have a better understanding of how it works in Projects and can adapt my system to fit.

**Comment by IsFilimonov** [comment]
I support the need for this implementation. The ability to sort by multiple fields is sorely lacking. In the DataView source this can be implemented in the format `SORT columnA ASC, columnB ASC`, but not yet in the Folder source. Even if this feature will only be implemented at the `data.json` level at first, to test in the early stages of implementation - so to speak, for those who really need it.

**Comment by obstschale** [comment]
I just was looking for this feature and there it is. I simply needed to update to 1.16 🙏  Thank you very much
