### ISSUE TITLE
first view doesn't persist filters

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#276]
### What happened?

When you switch projects, the first view doesn't persist the filters.

### What did you expect to happen?

The filters persist in the first view even if you switch between projects.

### How can we reproduce it (as minimally and precisely as possible)?

1. create demo project
2. add another project
3. add filter to the first/current view
4. go to demo project
5. go back to created project (the filter is gone)

### Plugin version

1.6.2

### Obsidian version

1.1.9

### OS

macOS

**Comment by marcusolsson** [comment]
Thank you for reporting. I'm able to reproduce this with the steps provided. Will make this my priority.
