### ISSUE TITLE
[Bug] Right clicking many UI elements pops up the menu and then loses it as soon as you finish the right click (let up on mouse click)

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#28]
Here is video showing it. Many areas the right-click seems to fire the menu but then not persist it as you let go of the right click button. Some of the examples in the video stay on screen for a second or two because I am holding the right click mouse button and then it disappears as soon as you let go. I am on Windows 11 FYI.

https://user-images.githubusercontent.com/64155612/190438188-ab6cc16e-274e-467f-96df-6fe8e3f0fa8c.mp4

**Comment by marcusolsson** [comment]
Seems related to #24. Both running on Windows. I'll see if I can boot up my Windows machine to reproduce this.

**Comment by GitMurf** [comment]
> Seems related to #24. Both running on Windows. I'll see if I can boot up my Windows machine to reproduce this.

Ah, yep I also have the same problem as #24 with right-click > clear value.

**Comment by GitMurf** [comment]
Ok weirdest thing. If I am NOT focused on the Obsidian app and have it on another screen and have for example Chrome focused (or any other app on Windows) and then right-click into the Obsidian app into Projects (while Obsidian was not the active focused app) then the menu stays open on just this first click. But now that Obsidian app is active if I try right-clicking again then it disappears just like above describes. @Quorafind curious if you see the same behavior?

**Comment by GitMurf** [comment]
I wonder if this is related? https://github.com/piroor/treestyletab/issues/1441
