### ISSUE TITLE
can't save the predefined values in text column

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#282]
### What happened?

When I add the predefined text options in the text column setting, pressing the `save` button does nothing.

### What did you expect to happen?

It saves the options, which enables me to use the feature.

### How can we reproduce it (as minimally and precisely as possible)?

add options in the text column setting and press the `save` button.

### Plugin version

1.7.0

### Obsidian version

1.1.9

### OS

macOS

**Comment by marcusolsson** [comment]
Unfortunately, I can't seem to reproduce this. 

> pressing the save button does nothing.

Does the modal close? Or, does the modal close but the changes don't persist?

https://user-images.githubusercontent.com/8396880/209964648-c9d96555-f041-444e-96f3-f28cca4f9701.mp4

**Comment by Acylation** [comment]
The modal stays still after clicking "save" button.

Could you please try to reproduce it in a former project, created before 1.7.0 update? I found that when I try to configure a field in a new project, everything works well, while the old projects can reproduce the bug.

**Comment by imeed166** [comment]
I confirm what @Acylation said. It happens only with already-created projects.

**Comment by marcusolsson** [comment]
Thank you for the quick response, I'll do some more troublehooting!

**Comment by marcusolsson** [comment]
By any chance, do any of you see any errors in the console?

**Comment by Acylation** [comment]
![屏幕截图 2022-12-30 010810](https://user-images.githubusercontent.com/73122375/209986033-085e20b6-f8b8-4d9b-ad9b-50cbac122404.jpg)

It occurs when the `save` button clicked

**Comment by marcusolsson** [comment]
Perfect! Thank you! 🙏
