### ISSUE TITLE
[Bug] When you click the Project "open in new tab" button to the left of a Project item (note) in the table view it replaces the tab to the left instead of opening a new tab

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#29]
See my video for full description as well as the title.

https://user-images.githubusercontent.com/64155612/190439089-a860a1ef-ba84-4284-991a-130974301470.mp4

**Comment by marcusolsson** [comment]
Try out 0.9.1 and let me know if the bug's still there 🙏

**Comment by GitMurf** [comment]
@marcusolsson I do not see any updates available via BRAT. Did you update the manifest? Thanks!

**Comment by GitMurf** [comment]
I see the commit for the fix but I do not see a new release so maybe I jumped the gun and your message was meant for me to see it later after you got the release packaged up? ;-)

**Comment by marcusolsson** [comment]
I forgot to push the tag 😓 I'll create another release with some of your other feature request!

**Comment by GitMurf** [comment]
Confirmed this is fixed! Thanks @marcusolsson
