### ISSUE TITLE
Hi, any support for saved filter ?

### ISSUE THREAD

**Issue by changwuf31** [marcusolsson/obsidian-projects#291]
### What would you like help with?

I found out that after switch projects, the table view filter is reset to none.

Is there any support for the filter to be persisted ?

**Comment by marcusolsson** [comment]
What version are you running? This should been fixed in 1.8.0.

**Comment by changwuf31** [comment]
Ah, thank you :+1: 
Indeed it has been fixed, was running v1.6.2 before.
