### ISSUE TITLE
[FEAT] Create a template for naming your new items (md notes) within a workspace

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#31]
Would be great to be able to set a template / default for when you add new items (Projects) inside a Workspace. For example, lets say your Workspace is located under `Projects/Family/Health` I may often want to name my new project something like `Personal Projects - Family - Description of new project` so this new feature would provide a setting/field within a Workspace that would say something like "Default new project name" and I would enter `Personal Projects - Family - ` in this setting so that when I add a new item the input pop up would default to this in the modal prompt so I could then easily just finish the name of the Project (note name).

![image](https://user-images.githubusercontent.com/64155612/190467629-a0b7660a-0f77-4958-a1e6-baec38a5f745.png)

**Comment by marcusolsson** [comment]
Your example looks like it's merely adding the template string as a default. Another option would be to configure a template that looks something like `Personal Projects - Family - {{title}}`. Then, the modal would show a little preview of the final note title under the text field as you type.

**Comment by GitMurf** [comment]
@marcusolsson that is ultimately what I wanted but i didn't want to get too greedy on this initial feature request idea 🤣 But I love that approach!
