### ISSUE TITLE
Allow properties/columns of type "Link" to be used as the 'status' of board views.

### ISSUE THREAD

**Issue by m-beau** [marcusolsson/obsidian-projects#316]
### What would you like to be added?

Currently, only columns of data type 'Text' can be used to serve as a grouping variable to generate a board view. I would like to be able to make boards whose columns have links as grouping variables (an internal link to a note (a Map Of Content), in my case).

### Why is this needed?

This will allow to subsitute mere passive column titles by clickable links to map of contents (for instance, 'To Do' might be a note with rich content, backlinks etc instead of a simple title).

**Comment by marcusolsson** [comment]
As I mentioned in #315, text fields will eventually support links. When they do, I'm not sure there's enough value in a dedicated Link field type.

I'm thinking this issue won't be needed once #315 is implemented. WDYT?

**Comment by m-beau** [comment]
I gave an opinion in #315 directly: [link](https://github.com/marcusolsson/obsidian-projects/issues/315#issuecomment-1372036384)

Cheers for your work!

**Comment by marcusolsson** [comment]
Try out the new option for rich text formatting in 1.9.0, which renders links in text fields. It might solve your problem.

**Comment by marcusolsson** [comment]
Are you able to share your dataview query (and maybe a screenshot)?

**Comment by m-beau** [comment]
Sure (apologies for the french):

```
TABLE
picture as "Picture", MOCs AS "Catégorie"
FROM #recette
WHERE file.name != "Recette template"
```
Leads to this table view (all empty rows should actually have two links, [[link1]], [[link2]], and the 'Picture' view should contain images):
![Screenshot from 2023-01-05 16-48-49](https://user-images.githubusercontent.com/25953361/210835690-4711c536-8163-41c3-b21c-dcdeee03064a.png)

And this board view:
![Screenshot from 2023-01-05 16-49-01](https://user-images.githubusercontent.com/25953361/210835677-ca044547-ec13-439c-9565-0753e7f0156f.png)

And this gallery view, where 'Picture' is set as the cover:
![Screenshot from 2023-01-05 16-50-45](https://user-images.githubusercontent.com/25953361/210835667-977ec9c6-8bac-4652-bded-0399f2c96d34.png)

**Comment by marcusolsson** [comment]
Thank you, that's helpful! The rich text support is only available for front matter at the moment, but I'm working on the Dataview support.
