### ISSUE TITLE
[FEAT] Specify a template for new notes/projects within a Workspace to set default YAML front matter and any default text you want your note to start with

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#32]
This is similar to #31 but instead of just a template for naming the new project/note it would be nice to be able to specify another note as a template to use for new projects/notes within a specific workspace. Similar to how Daily Notes works where you specify a template to create your Daily Notes Page each day.

As an extension to this feature it would be cool if similar to Notion you could specify multiple templates to choose from for a given Workspace (one of which could be a "blank template"). So you may have a Workspace for writing blog posts and then have a few different templates to choose from each time you add a new item/project/note e.g., Tech Blog Post OR Hobby Blog Post OR Parenting Blog Post.

So the workflow would be:

1) Select add new item
2) The modal pops up asking for your name of the new project/note and suggests whatever you set as the default name (see #31 )
3) If you have zero templates set/added to this workspace it automatically just creates a blank note
3-a) If you do have a template(s) configured for this Workspace it supplies a dropdown asking you to select a template to use. There is also an option for "Start from blank note" as one of the template options to choose from

**Comment by marcusolsson** [comment]
Amazing idea as well!

**Comment by Quorafind** [comment]
A useful solution now: Use templater to monitor the folder to add content to created note.

**Comment by GitMurf** [comment]
Thanks this is great! I have another piece of feedback on this but I will open a new issue for tracking purposes :)
