### ISSUE TITLE
The initial color filter runs out of the screen

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#325]
### What happened?

When create the first color filter, the popover went out of the screen. Reopen it would solve this, but still can be improved, as the filter popover works fine.

https://user-images.githubusercontent.com/73122375/210927643-dd4d5489-de80-4d57-9244-7e941013bd62.mp4

### What did you expect to happen?

Align correctly.

https://user-images.githubusercontent.com/73122375/210928532-42b7a5d9-96c5-4fcf-87cb-a756eeda374a.mp4

### How can we reproduce it (as minimally and precisely as possible)?

Create a new color condition from blank in any view.

### Anything else we need to know?

Seems like the problem occurs since the color feature was added in the release 1.6.0, and it remains.

### Plugin version

1.9.0

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment]
Thank you for reporting 🙏  I can confirm this, though I need to investigate why this works for Filter but not Color.
