### ISSUE TITLE
Display project name in the delete project prompt

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#326]
### What would you like to be added?

Now the prompt only shows "Are you sure you want to delete the project". I hope to add the target project name onto it.
![image](https://user-images.githubusercontent.com/73122375/210960311-42a97133-b9f2-4439-a174-a716b2488ad8.png)

Here's how obsidian does it
![image](https://user-images.githubusercontent.com/73122375/211019460-f6f34779-4571-4684-964f-55f30ebe8fc5.png)

### Why is this needed?

Add project name to the prompt would avoid unintentionally delete.

**Comment by marcusolsson** [comment]
Great idea! 👍
