### ISSUE TITLE
[FEAT] Add right-click context menu item to Folders in the Obsidian file explorer view to quickly Create a new Workspace

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#33]
Would be great if we could right-click a folder in the file explorer and have an option to Create/Add a new Projects Workspace using that folder location. Then it would bring up the Add Workspace modal and pre populate the Workspace Path with the full path and the Workspace Name with the name of the folder you selected. So if a folder is located at: `Projects/Consulting` then it would pre-populate the Workspace Path with `Projects/Consulting` and the Workspace Name with `Consulting` (see screenshot below). Of course you can then edit the Workspace Name in that modal as you wish.

![image](https://user-images.githubusercontent.com/64155612/190470493-b579d8f3-3cad-4ef7-9936-e1dfe128c5a7.png)

![image](https://user-images.githubusercontent.com/64155612/190471426-e29243d8-6948-4316-aa2b-92a5372b9ee4.png)

**Comment by marcusolsson** [comment]
I _love_ this idea! So incredibly clean!

**Comment by GitMurf** [comment]
@marcusolsson you are a machine! Thanks for getting on these ideas so quickly :) I am very much looking forward to the development of this plugin and eventually plan to help contribute!

**Comment by GitMurf** [comment]
This is working perfectly! Thanks!
