### ISSUE TITLE
Folder suggester modal shows up on main Obsidian app window if you are in a pop out window

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#35]
I am not sure if this is an Obsidian bug or a bug with the way Templater implemented this feature (which I believe is also how Projects does it)? See this issue in Templater repo: https://github.com/SilentVoid13/Templater/issues/830

![image](https://user-images.githubusercontent.com/64155612/190827554-2d456f99-89a1-4ca7-82da-dab59f89c245.png)

This screenshot is for Templater but same thing happens when adding a new workspace in Projects from a pop out window and trying to use the folder suggester.

**Comment by marcusolsson** [comment]
For 1.0, I will probably hold out to see the results from the linked issue. If anyone looks at this, I'd be happy to review a PR.
