### ISSUE TITLE
Lock a selected column, so it stays in view when side-scrolling.

### ISSUE THREAD

**Issue by FeralFlora** [marcusolsson/obsidian-projects#351]
### What would you like to be added?

It would be nice if it was possible to freeze the first column (or X number of columns), so these columns always stay visible. For reference, a similar feature exists in Excel. 

### Why is this needed?

With this feature, it will be much easier to perform edits on tables with many columns, without scrolling back and forth to make sure you're looking at the right row.

**Comment by marcusolsson** [comment]
Great idea! 👍
