### ISSUE TITLE
Goals or Epics?

### ISSUE THREAD

**Issue by NullAleph** [marcusolsson/obsidian-projects#358]
Hi Marcus,
Enjoying your plugin - that you for the work you put into this!

I would be great to be able to groups Projects into a collection of Projects that make up a larger Goal.  An analog to this idea might be the idea of Epics, where a Goal/Epic might be related to multiple Projects.

Your thoughts?

Cheers!

**Comment by marcusolsson** [comment]
This seems related to #140. Could that work you?
