### ISSUE TITLE
[FEAT] Add the Template location to the settings editor so that you can change it after initial workspace creation

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#36]
This is in response to the new feature #32 where you can now add a Template to use for a workspace. After the initial creation of the workspace there is no way to add a Template (if you didn't during initial workspace creation) or to change the Template if you did configure one during workspace configuration.

![image](https://user-images.githubusercontent.com/64155612/190828563-085145db-3cea-4bac-8a83-14a390d798c7.png)

**Comment by marcusolsson** [comment]
Yeah, the Edit modal should really be the same as the Create modal. Should be an easy fix!
