### ISSUE TITLE
Table: Reactivity problem of the name field

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#361]
### What happened?

As the screen recording shows, I edited a text cell in a sorted column, and all metadata cells moved as expected except for the name field. Then I double-click the name cells, and the actual file name came back.

https://user-images.githubusercontent.com/73122375/212809335-3f96f818-927f-452e-b6fb-867d524aded1.mp4

### What did you expect to happen?

The name field is expected to move as the item's order has been changed.

### How can we reproduce it (as minimally and precisely as possible)?

Edit a sorted column that will cause the item order to change, then track the name field.

### Anything else we need to know?

The Boolean cells also have strange behavior if they are sorted, I will open up another issue to describe it.

### Plugin version

1.10.0

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment]
Thanks for reporting this! 🙏
