### ISSUE TITLE
Table: Reactivity problem of Boolean fields

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#362]
### What happened?

I edited a Boolean cell in a sorted column, and another one was affected by editing unexpectedly. Notice that only the display was influenced, but not the actual value.

https://user-images.githubusercontent.com/73122375/212811662-c466c1b1-dc49-42bd-abfe-08557bd61091.mp4

A similar case is when I edited a Boolean cell with a filter applied, the display also gave a wrong reaction.

https://user-images.githubusercontent.com/73122375/212812508-294683c5-03f1-418d-8aeb-636e895b0e6c.mp4

### What did you expect to happen?

I wish the cells would react properly.

### How can we reproduce it (as minimally and precisely as possible)?

Edit a sorted/filtered Boolean cell that will cause reorder and mistakenly display, then check the actual value by double-clicking on cells.

### Plugin version

1.10.0

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment]
Thanks for reporting, I'm able to reproduce this with a sorted boolean field.

**Comment by SmokenFlames** [comment]
Having the same issue.
