### ISSUE TITLE
Defining a project by tags in frontmatter not working

### ISSUE THREAD

**Issue by ltroj** [marcusolsson/obsidian-projects#364]
### What happened?

When setting up a project using
``Data source`` : ``Tag`` and ``Tag`` : ``#Project/my-proj``

notes with the tag mentioned in the frontmatter won't get recognized as a part of the project.

YAML looks like

```
---
tags:
  - Project/my-proj
---
```
Using ``#Project/my-proj`` in the note body adds the note to the project as expected.
 
When using folders to set up a project, empty tags in frontmatter show up as ``null``, which is inconsistent with plain Obsidian and other tag-based plugins which ignore empty tags.

YAML looks like

```
---
tags:
  - 
---
```

### What did you expect to happen?

There should be no difference between tags in frontmatter and tags using ``#`` when setting up a project.
"Empty" tags in frontmatter should be ignored completely.

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Anything else we need to know?

Great plugin, love it so far!

### Plugin version

1.11.0

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment]
Thanks for reporting! 🙏
