### ISSUE TITLE
Possibility to make Kanban (Board) columns persistent

### ISSUE THREAD

**Issue by ltroj** [marcusolsson/obsidian-projects#366]
### What would you like to be added?

Currently when a column in Board view has no cards/notes in it it will disappear. It would be great to be able to keep columns even when there is no note in that column.

### Why is this needed?

I'd like to lay out the board structure before adding notes. Also it happens during the completion of a project that a column is temporarily empty (for example, if I have a column "On hold", but no task is currently on hold). In the moment, in which the column becomes empty it disappears and breaks the Kanban board structure.

**Comment by marcusolsson** [comment]
If you go to the Table view, click the three dots for the column you're using for your status, and then select **Configure field**, you can add the columns you want to persists under Options.

**Comment by ltroj** [comment]
Oh thank you, I completely overlooked that! Makes things so much easier, thanks for pointing out.
