### ISSUE TITLE
Turn off name in Kanban card

### ISSUE THREAD

**Issue by rapatel0** [marcusolsson/obsidian-projects#367]
### What would you like to be added?

In kanban view, would like the ability to use turn off the name in the card 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/18704704/213191234-9211e3c7-9205-4db4-a5da-7ad1f3e34a3b.png">

This is because I use MetadataMenu to manage metadata across tasks. As shown in the image above this metadata menu renders fine if I use the file column in the dataview query. Alternatively if the metadata link can be propagate to the main name link, that would be great as well.

### Why is this needed?

Duplication of filename. User might want to control card display in a more finegrained way.

**Comment by yojiyama7** [comment]
I would like this.
Or something that allows metadata for the name part to be something other than `file.name`.
