### ISSUE TITLE
[FEAT] Add command to CP to Add New Item/Note and then a modal asks which Workspace to add to

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#37]
This is in relation to #34 ... I realize that when I say "Project" you are probably thinking I mean "Workspace" when I am actually calling a Project just a new Note/Item. So in #34 you added the command for creating a new workspace (thank you) but I was actually meaning a command to "Add a new item/note" (or whatever we want to call it). And then it will ask you which Workspace to add it to. Basically a way to quick create items/notes within our workspaces. I think it should also ideally then ask you if you want to open this new Item/Note in the current active tab/pane or to open it in a new tab/pane.

I have been referring to those new Notes as "Projects" (thinking like small sub projects for each note) but realize now that "Project" to most probably lines up with "Workspace". I think this goes to the conversation you and I had @marcusolsson via DM in Discord about how the naming has changed a bit and it may be confusing for folks understanding the different between Folder vs Workspace vs Project vs Item vs Note etc.

![image](https://user-images.githubusercontent.com/64155612/190829037-7071fc5e-932b-40ba-88cb-1e2ef1a499e4.png)

**Comment by marcusolsson** [comment]
😆 

Before publishing this, I definitely need to look over the terminology. 

So far, I've only really considered two abstractions. An individual note, and a collection of notes. 

I've been using "record" to refer to an individual note. I thought about using "note", but since the plugin isn't really about note-taking I wanted to distinguish them. Might have to revisit that.

A collection of notes (or records) is a "workspace" at this point. The only place I'm using Projects is in the name, so the way I see it, we should rename the plugin to Obsidian Workspaces, or rename the "workspaces" to "projects".

**Comment by marcusolsson** [comment]
Another question is whether each view should call it different things based on the context.

For example:

- Table: Record -> Row
- Board: Record -> Card
- Calendar: Record -> Event

... or we use "record" consistently throughout all the views.

**Comment by GitMurf** [comment]
My opinion is that we use "record" consistently. The idea (in my opinion) is that the data is all the same and the views are just on top of the data and allows you to see the data in different ways (since it is just a view). For example, if I add a record to the Table view for "Create a new GitHub repository for blah blah..." and I put in there a date I'd like to do it, it will (and should) show up in my Table view and Calendar view. But it would not be considered an "Event". It all depends on the context of the view I think at that point. So all that being said, I agree that probably keep it consistent with either "Record" or "Item" or even "Note" (since they all are Notes... at least today they are 😄 ).

Thoughts?

**Comment by GitMurf** [comment]
> so the way I see it, we should rename the plugin to Obsidian Workspaces, or rename the "workspaces" to "projects".

If I had to choose between these two options I would definitely say "rename the workspaces to projects" ... because if you change the plugin name to Obsidian Workspaces it will confuse everyone with the core Workspace plugin already and the Workspace ++ plugin :)

If you changed the terminology from workspaces to projects then I think that adds opportunity (at some point) to introduce the idea / terminology of "Sub Projects". Because you would probably have a folder (Project) for Client ABC but the you may have multiple projects for Client ABC so some sort of Project > Sub Project hierarchy may be good to explore.

Alternatively once you explore the ideas of filtering and grouping and "Folders" concepts, then that may solve the problem or need for introducing "Sub Projects".

Hopefully this helps!

**Comment by GitMurf** [comment]
@marcusolsson adding comment here from our DM chat just for documentation purposes :)

>This is PERFECT! The only thing I can add to it would be it would be nice if the new note created opened (or could be opened) after creation in a new tab (or had an option in the creation modal that you can select "Do nothing" / "Open Note" / "Open Note in New Tab". But now I am just getting greedy 😉 haha

I will open a new Issue for consistency.
