### ISSUE TITLE
Clickable http/https links inside a view

### ISSUE THREAD

**Issue by AzadKshitij** [marcusolsson/obsidian-projects#372]
### What would you like to be added?

I would like to have my links added in YAML to be clickable inside table, gallery view. 

ex: 
![image](https://user-images.githubusercontent.com/54288405/213405765-703ef1e8-c90e-4705-9a7c-2a45900286ae.png)

Make this YouTube link be clickable.

### Why is this needed?

It will be easier to get what you need and not to go to each file just to open a link.

**Comment by marcusolsson** [comment]
You can do this already, but it's a bit hidden 😅 

1. From a Table view, select the three dots icon in the `youtube` column, and then select **Configure field**.
1. Select **Enable rich text formatting**.
1. Select **Save**.

Enabling rich text formatting should work across views. We should let the user open the Configure field modal from the other views as well.

**Comment by AzadKshitij** [comment]
Oh! Thanks I just implemented similar by my self... XD
![image](https://user-images.githubusercontent.com/54288405/213435484-eb7da311-ebbf-44f0-9756-e6c09885541d.png)
