### ISSUE TITLE
After updating to 1.11.2 from 1.11.1, line break exception in the board and gallery view

### ISSUE THREAD

**Issue by wuzhen97** [marcusolsson/obsidian-projects#387]
### What happened?

![image](https://user-images.githubusercontent.com/61906420/213685724-00498441-60e6-416e-a87d-44f052f08d42.png)

![image](https://user-images.githubusercontent.com/61906420/213685741-afcd685a-0c7f-406a-ad22-2f7029b61b6c.png)

### What did you expect to happen?

Normal

### How can we reproduce it (as minimally and precisely as possible)?

After updating to 1.11.2 from 1.11.1, line break exception in the board and gallery view

### Plugin version

1.11.2

### Obsidian version

1.1.11

### OS

Windows

**Comment by marcusolsson** [comment]
Thanks for letting me know!

**Comment by marcusolsson** [comment]
I've released 1.11.3 with a fix. Let me know if it persists!

**Comment by wuzhen97** [comment]
> I've released 1.11.3 with a fix. Let me know if it persists!

all works well，thanks~
