### ISSUE TITLE
Table: Adjust navigation action of Tab key to prev/next instead of left/right

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#398]
### What would you like to be added?

Now the Tab key navigates left/right, which means the cursor will be stuck at the start or end of the row. I wonder if the behavior can be adjusted to prev/next to move forward/backward between rows?

### Why is this needed?

The prev/next style is consistent with major column limited sheets.

---

I'd like to have a try on this if accepted. A concern is, should I just pass the parameter "the number of columns" to Grid-Cells, or should cell navigation be lifted to DataGrid?

**Comment by marcusolsson** [comment]
Good idea!

I think the easiest way is to implement [here](https://github.com/marcusolsson/obsidian-projects/blob/ae27275e727041cc8f6a3d6cf31d3c88eae29bb2/src/views/Table/components/DataGrid/DataGrid.svelte#L197-L213). Ideally, I think only the Tab character should wrap to the next and previous rows, so maybe we need to update the event payload to include a `wrap` property or similar.

**Comment by Acylation** [comment]
Got it, I'll have a further look into this.
