### ISSUE TITLE
TypeError when using tags as dataSource

### ISSUE THREAD

**Issue by evelynweiser** [marcusolsson/obsidian-projects#399]
Hi Marcus,

thanks for the plugin. I am excited to use it, but unfortunately I have not been able yet to make it work.
I want to define my projects based on tags. I have tried frontmatter tags and also inline tags, but I always receive the error message:

_TypeError
Cannot read properties of null (reading 'toString')._

I have seen the tickets #368 and #364 but they did not help.
I am using Obisdian v1.1.9 on Linux Mint 21.

Am I overlooking something obvious?
Any hint is highly appreciated.

Cheers,
Eve

**Comment by marcusolsson** [comment]
Could you share some more details on how I can reproduce this? 

Could you try going to the plugin settings and setting the Project size limit to anything but the default value, and see if that helps?

**Comment by evelynweiser** [comment]
Thanks for the quick reply.

Changing the default value of the project size limit does not change anything.

I have just created a new vault without any notes and copied the .obsidian folder from the problematic vault. After creating two test notes and a test project it works fine. So I guess there's nothing wrong with all my other plugins and settings but it must be something in my notes?

I will play around some more.

**Comment by evelynweiser** [comment]
Finally, I have found the problem.
There was a template in my vault which had the following in the frontmatter:

```
---
date: <% tp.date.now("YYYY-MM-DD") %>
updated: 
status: current
tags:
  - 
---
```

The empty YAML bullet  at the end was the culprit. If I write

```
---
date: <% tp.date.now("YYYY-MM-DD") %>
updated: 
status: current
tags:
---
```

... everything works fine.

Cheers,
Eve

**Comment by marcusolsson** [comment]
Thank you for letting me know! I added a fix so that empty tags are filtered out instead of crashing (https://github.com/marcusolsson/obsidian-projects/pull/404).
