### ISSUE TITLE
Option to open new note after creation

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#40]
In reference to the implement of #37 This is PERFECT! The only thing I can add to it would be it would be nice if the new note created opened (or could be opened) after creation in a new tab (or had an option in the creation modal that you can select "Do nothing" / "Open Note" / "Open Note in New Tab". But now I am just getting greedy 😉 haha

I will open a new Issue for consistency.

_Originally posted by @GitMurf in https://github.com/marcusolsson/obsidian-projects/issues/37#issuecomment-1251217990_

**Comment by marcusolsson** [comment]
I think it makes sense to open the note when using the command (with I've added), but when you create the note from the Project view, I'm guessing you are more likely to want to create several notes. You probably don't want to lose context in this case.

Could of course add options to change the behavior, but typically you can open the note from one extra click, so I'm not sure I think it worth it. If enough people enough people ask for it, I think we can consider it though.

**Comment by GitMurf** [comment]
@marcusolsson perfect! And I agree completely. And I tested the new note from command palette and it opened just as I would expect! thank you.
