### ISSUE TITLE
Separate the commands in the 'New' button

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#401]
### What would you like to be added?

Now in the dropdown of the 'New' button, we have commands to create new projects, new views and new notes/items. Should they be separated and moved to places like project selector and view selector?

![image](https://user-images.githubusercontent.com/73122375/214150902-e7e0bb17-24f3-44ee-8397-dc5526fbde5e.png)

### Why is this needed?

To integrate commands which are at the same level.

**Comment by marcusolsson** [comment]
Actually, I had it like that before 1.0.0. I changed it because I felt like the bar became too busy with several buttons that weren't used that often. 

If we add more object types, like recurring notes, it would fit well with the New button.

I'm not married to the current design, but I'd like to avoid changing it too often. If we change the top bar, I'd like to do some more design work before changing it.

For example, I can see the "New view" in your screenshot, but how would you add a new project, or note?

**Comment by Acylation** [comment]
Fisrtly congrats! Wish you a wonderful marriage!

For new projects, the new command can be integrated into the project setting menu. An alternative solution is, add an option called "Create new project" in the project selector. 
![image](https://user-images.githubusercontent.com/73122375/214270292-74965e27-3f76-470f-ad3d-3b47cc88cc2f.png)

To save space in the toolbar, an iconbutton for new view is enough. The design also simplifies view creation from a two-step operation to one.
![image](https://user-images.githubusercontent.com/73122375/214271753-fa67c433-b5dc-4ce4-8702-8b274126cac4.png)

As adding note is also a project-level command, maybe where the current new button lies is the best place for the notes. 
However, as there are note creating commands/shortcuts in most of the views, we can even cancel the new button. For example, there are buttons for new notes in both Table view and Board view, and we can double click on the date cell in the calendar view to create new note. Then, find a way to add new notes in the Gallery view seems the only thing we need to do. Here's an protype using the blank card to create new notes.
![image](https://user-images.githubusercontent.com/73122375/214273070-f39c7b04-c49a-41a1-aeaa-dbeef5cf5620.png) 

> I'd like to avoid changing it too often.

Yeah, maybe we can provide a transition period during when old & new ways all works. Currently, adding support to create new project in project setting menu, new view in the toolbar and new note by clicking a blank card in Gallery view would enhance the UX, I think.

> If we add more object types, like recurring notes, it would fit well with the New button.

If the recurring notes are still physically notes, but with several special header fields, we can leave it to note creating modals. However, if they touchs the project configs, then the new button do have advantage in compatibility. I haven't considered it before but it worth. and the changes should be applied in an appropriate time.

I'd also like to help with this when designs are settled. Thanks for your patiently reviewing and glad to know your opinion.

**Comment by Acylation** [comment]
closed by #468
