### ISSUE TITLE
Move add note button to top

### ISSUE THREAD

**Issue by ina6ra** [marcusolsson/obsidian-projects#408]
### What would you like to be added?

![image](https://user-images.githubusercontent.com/48197/214751680-b9422662-4583-4bd8-b6f8-4bbf669a6e00.png)

### Why is this needed?

If the list of tables grows, you have to scroll to add notes.
It is more convenient to be on top.

**Comment by marcusolsson** [comment]
Thanks for the suggestion! I understand the frustration of having to scroll down to the bottom to add a new note.

I'm a little hesitant to move the bottom to the top though. One thing I'd like to experiment with in the future is grouped tables, where you can add notes to each group:

![grouped-table](https://user-images.githubusercontent.com/8396880/214807084-94e6adc9-e9cc-416c-b153-a4f5866c8a84.png)

I think keeping the Add note button at the bottom makes more sense in this situation. But maybe we could make it sticky, so that it stays at the bottom of the screen when you scroll down?

**Comment by ina6ra** [comment]
@marcusolsson Thank you for your prompt reply.
I think group tables are a great feature.

However, personally, it would be more convenient if there was an `Add note` button at the top and a group selection list next to it, allowing you to switch between them.
It reduces unnecessary scrolling, and even in the current situation, items edited from the list display may not be saved well, so I think it's better to make it as simple as possible.

**Comment by ina6ra** [comment]
(I fixed it because the title was memo instead of note)

**Comment by marcusolsson** [comment]
Thanks for clarifying! I need to give it some thought.

Also, it's one extra click, but could you use the New button in the upper-right corner?

**Comment by ina6ra** [comment]
I knew I could create one from the top right list.
The same column is the project's menu, so the `New note` button is not intuitive.

This is a change that modifies the UI, so prioritize other issues.
I think what's more important is the ability to open other projects and URL from the `Table view`.
#73

**Comment by Acylation** [comment]
Would stick `add note` to the bottom solve the problem?

A demo from GitHub Projects
<img width="960" alt="image" src="https://user-images.githubusercontent.com/73122375/237044390-97ed78d1-540a-413e-8e3a-33d436420e29.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/73122375/237044455-0bde1caa-ed46-4f55-9a75-ce287c671e96.png">

**Comment by jorgeherrera1** [comment]
I mistakenly created a duplicate #578 (which is now closed) but I would still like to comment that it'd be a nice good usability addition to have the Add Note visible regardless of the number of notes.  I'm not a UI/UX designer so I cannot speak to where the button should go but as a user it would be lovely that I don't have to scroll all my notes to create a new one on the Table view :)

**Comment by marcusolsson** [comment]
> Would stick add note to the bottom solve the problem?

I like this better than having it on top!

**Comment by jorgeherrera1** [comment]
> > Would stick add note to the bottom solve the problem?
> 
> I like this better than having it on top!

I think that should work :)

**Comment by Acylation** [comment]
Sticky add note has been supported since release 1.16.1 via #616 . Close this as completed.
