### ISSUE TITLE
Ability to specify specific Templates to use for a Project instead of an entire Folder location

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#41]
Great work here! This is a great first step and I apologize for not being clearer in my initial request but the only problem here is that this requires either have a single folder where all template are stored for all my different projects and cannot be separated into sub folders etc. (because have to set a single folder to use)... as well all templates in a folder are included which I have MANY templates so need to select through a massive list of a lot of "crap" to find a template I want each time. So if I wanted to have just a couple templates to select one for a specific project I would need to copy those templates into their own folder. And then I will use a couple of the same templates on many of my projects so then I would have to copy the same template over and over again which is not ideal because if I want to update one then I have to update it in all locations.

The ideal situation and intention behind my idea/request is that it doesn't matter where templates sit in our vault. You select templates one by one for each project. So some projects have no templates. Some have one single template and others maybe have 3 or 4 templates. My inspiration behind the idea is like how Templater does their "Add new hotkey for template" where you add new items and specify their location and then you can remove them with the "X". So for a project that I want 3 templates to choose from, this is what the settings of the workspace/project would look like:

![image](https://user-images.githubusercontent.com/64155612/191062896-b62b0653-f0e1-46bb-921b-a8ef6027950d.png)

And then when creating new notes for that Project the way you currently have it is perfect! With a dropdown where the default is "None" (empty) and then if you click the dropdown it would just show those 3 templates that I added above (instead of the entire templates folder you need to select currently).

![image](https://user-images.githubusercontent.com/64155612/191063227-819087c5-466f-4e72-8e61-a5f9bab2ce4a.png)

_Originally posted by @GitMurf in https://github.com/marcusolsson/obsidian-projects/issues/38#issuecomment-1251232942_

**Comment by GitMurf** [comment]
Also I have two main template locations (core templates and Templater templates) so in the current implementation there would be no way to have option to use templates from both.

My biggest use case / example for having specific templates is that I have a few different Meetings templates that I re-use across many projects. So most Projects I want just a couple templates to choose from like:

- Meetings template
- Research template
- Notes on an article, podcast or video template

So if I have a Project for a client I am doing some IT Consulting for, I will likely have templates for Meetings, Research, Presentations and Analysis. And I will re-use those for several Projects / clients etc. But then I will also use the Research template in my Projects for Obsidian development (Plugins etc.).

**Comment by marcusolsson** [comment]
You raise some very valid points. I haven't used Templater and replicated the native Template plugin. I'll think about how to address this.
