### ISSUE TITLE
Board view priority selection and status assignment

### ISSUE THREAD

**Issue by JordanChoe** [marcusolsson/obsidian-projects#410]
### What happened?

Related to this discussion: https://github.com/marcusolsson/obsidian-projects/discussions/353

When I create a board view, the priority only allows for number fields for the ability to drag and drop, based on my observation.  Additionally, the meta for any item in the no status column automatically updates to "no status" under the selected status field for the notes once a note has been dragged to another column.

For my use case, across various projects, I want to use the boards as a way to edit the meta in various files. This might be budgets, school lesson planning, book management, etc. For the purposes of the issue, I am sticking to a sample budget project with minimal files. :) This issue is also affecting my template file - in this case budgetingfile.md.  This means any new note I create using that template is auto-populated with no status for the selected field.  (the extra date thing in the budget file is a separate issue unrelated to this one.)  

### What did you expect to happen?

I expected the chosen status field, category, to only update for files dragged to a column. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a board view.  Select a status.  Notes are fine in "no status" column. Select a priority, which must be a number field (is this a separate issue?).  Drag a note to a column. View a note still in the "no status" column. The status field for those notes has been updated to "no status".  

Alternatively, can close and reopen the project to see these updates in the category column in both table and db views.

![Screenshot (83)](https://user-images.githubusercontent.com/108248499/214875672-b141a024-5246-4c35-ae36-765ba75dfcb1.png)
![Screenshot (78)](https://user-images.githubusercontent.com/108248499/214875674-66a2e609-33b0-41f2-b4bb-a1412ad09e6b.png)
![Screenshot (81)](https://user-images.githubusercontent.com/108248499/214875676-e9b73ce0-2cd9-427b-bbf0-8bfad7a1f76d.png)
![Screenshot (85)](https://user-images.githubusercontent.com/108248499/214875774-c7cee2f4-53f5-416b-a00d-2a465e126b10.png)
![Screenshot (88)](https://user-images.githubusercontent.com/108248499/214875780-f90f1217-1fdf-4baf-a69d-f4a67d734242.png)
![Screenshot (89)](https://user-images.githubusercontent.com/108248499/214875772-24492c9c-5cf0-42d3-b5ca-afb41c975dee.png)

### Anything else we need to know?

Note that in my screenshots I did not change the status field drop down to payee.  It is simply what came back, though I would expect the view to change as a result, and it didn't.  It is possible I accidentally touched my trackpad or touchscreen creating the condensed screenshot.  I don't use a mouse or dataview inquiries on this laptop for creating projects.  

That is unrelated to this specific issue, though might be a different one if I can recreate it on purpose.  :)

### Plugin version

1.11.5

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment]
I agree. "No status" shouldn't be written to the files.

The question though is what the value should be when dragged into No status. Should it remove the field from the file, or clear the value? 

From your screenshots, I suspect that you'd prefer by simple clearing the value?

**Comment by JordanChoe** [comment]
Ideally, it shouldn't input a value of "No status" at all.  Moving one card should not have the meta updated for the other cards in No status.  

However, yes, if a card were moved back to No status, then clearing the value may or may not be desired, depending on the user's use case. That would require a feature to toggle for if user desired it, with the default being to clear the value.

**Comment by Acylation** [comment]
In recent versions this seems to no longer be a problem, drag-n-drop a card won't affect the status value of other cards. In a coming PR I'll cancel writing 'No-status' when the note dragged into that column, instead we'll leave the value empty (implemented by set to `null`). Then this would be marked as completed.
