### ISSUE TITLE
Right click context menu to open a file in a new tab from any view

### ISSUE THREAD

**Issue by JordanChoe** [marcusolsson/obsidian-projects#413]
### What would you like to be added?

I would like a context menu to open a file from any view in another tab or window. It is currently not possible in any view. I don't see this on the roadmap anywhere. Searches in issues and discussions for right click, context, and menu revealed no relevant results.

### Why is this needed?

Currently, clicking the file name opens the file in the same tab as the project is displayed. Multiple files cannot be opened to compare with the project or other notes natively in the plugin.

The current workaround is the built in search feature to find the file, then using the Obsidian context menu to open the file(s).

Additionally, using the back button to return to the project being viewed after clicking to open the file from projects goes to the "default" first project, not the one I am working in if it isn't first in list. That portion may be related to open issues about project selection.

**Comment by marcusolsson** [comment]
If you hold Ctrl (or Cmd on macOS) it should open the link in another tab. Let me know if it doesn't!

**Comment by marcusolsson** [comment]
No worries, it's not really documented anywhere, so I apologize for that 🙏
