### ISSUE TITLE
"Cannot read properties of null (reading "toString")

### ISSUE THREAD

**Issue by CrackheadoooObsidianUserooo** [marcusolsson/obsidian-projects#414]
So when i create a new Project and select "Tags" as resource, and fill out the Tag i want to have my resource from, it only shows me  "Cannot read properties of null (reading "toString")"  ![Porjects Plugin Bug - Obsidian](https://user-images.githubusercontent.com/121588624/215787947-cf28112d-9105-4b94-a92e-06813f3afd29.png)

Theres no hint in the console, that ive found. I disabled all other Plugins and this bug still happens. When i switch the Vault everything is fine. What am i missing?

**Comment by sci268** [comment]
I meet it too today
![image](https://user-images.githubusercontent.com/76660932/216851486-eb64cabe-6c75-449a-a675-307d7a157d02.png)

**Comment by marcusolsson** [comment]
Fixed in #404.
