### ISSUE TITLE
Add option to use inline "key:: value" fields natively (not only through a dataview query)

### ISSUE THREAD

**Issue by m-beau** [marcusolsson/obsidian-projects#425]
### What would you like to be added?

Automatically detecting the inline properties and being able to edit them as you go when the source is a folder, not a dataview query.

### Why is this needed?

It allows to include rich content as values such as links and embeds, which is impossible when the 'key: value' pair is part of the YAML frontmatter.

**Comment by marcusolsson** [comment]
Closing in favor of #173.
