### ISSUE TITLE
Images do not render in board view as "included fields"

### ISSUE THREAD

**Issue by m-beau** [marcusolsson/obsidian-projects#427]
### What happened?

In dataview query mode, when using a property "picture:: [[my_image.png]]" or "picture:: ![[my_image.png]]" in the queried notes, when this property is ticked on in the 'include fields' tab of a board view, the 'picture' property renders as text "[[my_image.png]]" or "[[my_image.png]]" instead of the actual image.

### What did you expect to happen?

To see the actual image rendered.

### How can we reproduce it (as minimally and precisely as possible)?

In dataview query mode, use a property "picture:: [[my_image.png]]" or "picture:: ![[my_image.png]]" in the queried notes. Witness that when this property is ticked on in the 'include fields' tab of a board view, the 'picture' property renders as text "[[my_image.png]]" or "[[my_image.png]]" instead of the actual image.

### Plugin version

1.11.5

### Obsidian version

1.1.9

### OS

Linux

**Comment by Acylation** [comment]
There’s a new api method enabling this. Will come out sooooooon! https://github.com/obsidianmd/obsidian-api/issues/120
