### ISSUE TITLE
Improve the Database Folder View file name

### ISSUE THREAD

**Issue by SalahAdDin** [marcusolsson/obsidian-projects#440]
### What would you like to be added?

It would be nice if either:
- The database folder view file is named after the project.
- The database folder view can be loaded from the folder when it does exist (kind of option).
- The database folder view file can be renamed.
The first one would be the behavior by default.
The last option would be so nice features.

### Why is this needed?

The current file name is ugly and difficult to handle, while with such improvements I would not uglify the project/folders.

**Comment by marcusolsson** [comment]
This needs to be addressed in the DBFolder plugin rather than in Projects. Projects can hide the file for you, but to remove the need of the file altogether, you need to contact the author of DBFolder.

**Comment by SalahAdDin** [comment]
> This needs to be addressed in the DBFolder plugin rather than in Projects. Projects can hide the file for you, but to remove the need of the file altogether, you need to contact the author of DBFolder.

DB Folder extension can create a file with the name we want, as Projects create the file itself, I think it could have an input so we can add the file name, or it can create the file base on the project name.
