### ISSUE TITLE
Deleting Database Folder View does not delete the file

### ISSUE THREAD

**Issue by SalahAdDin** [marcusolsson/obsidian-projects#441]
### What happened?

I just got annoyed to have two database folder view files, so I decided to delete project one cause its file is ugly.

I deleted it, it does not appear in the project, but the file is still there.

![image](https://user-images.githubusercontent.com/5034215/221368125-bd1d5ae9-846b-46c6-bba2-6db5f4ceec4e.png)

### What did you expect to happen?

The file must also be deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Process:
1. Create a default vault.
2. Create a new folder for your project.
3. Create your project.
4. Add some notes.
5. Add a Database Folder View.
6. Delete the view.
7. Check the file.

### Plugin version

1.11.5

### Obsidian version

1.1.9

### OS

Linux

**Comment by marcusolsson** [comment]
The file is specific to DBFolder rather than Projects. You'd need to contact the author of DBFolder, who can determine when the file should be deleted.

**Comment by SalahAdDin** [comment]
> The file is specific to DBFolder rather than Projects. You'd need to contact the author of DBFolder, who can determine when the file should be deleted.

But I can delete the file manually. That's why I think it is more related to this extension.
