### ISSUE TITLE
Database Folder metadata file tasks not rendering

### ISSUE THREAD

**Issue by aikruger** [marcusolsson/obsidian-projects#444]
### What happened?

The Database folder file tasks field is available but does not render in the Database Folder view

### What did you expect to happen?

For it to work as it does in the native add-in

### How can we reproduce it (as minimally and precisely as possible)?

In the database folder view with metadata file task enabled, add the field 

### Plugin version

1.11.5

### Obsidian version

1.1.16

### OS

Windows

**Comment by daamiian** [comment]
I can confirm the same results. Using minimal theme I only get rendered tasks if I go the the actual db folder, however the db folder view in projects does not render tasks.

**Comment by marcusolsson** [comment]
Sounds like it could be an issue in the DBFolder. I'll look into this when I get the chance, but I think you should let the author of DBFolder know in the meantime.
