### ISSUE TITLE
Use default template

### ISSUE THREAD

**Issue by brush701** [marcusolsson/obsidian-projects#446]
### What would you like to be added?

Currently, the note creation dialog does not select any template by default. This introduces extra clicks for the user. I suggest the following behavior:
- If there is only one template loaded, that template is automatically selected
- If there are multiple templates loaded, they are sorted alphabetically and the first one is automatically selected

### Why is this needed?

This reduces clicks & overhead for users doing one of the most basic tasks.

**Comment by marcusolsson** [comment]
This assumes that the user wants to use the template most of the time, which I think is a fair assumption actually.

It would change the default, so it might cause some frustration initially for those who only use templates some of the time. It might be worth it initially though.

**Comment by brush701** [comment]
Makes sense. I suppose for those who like the current behavior you can always create a blank one called `00-Default` and have that be automatically selected. Adds overhead for those users, but I strongly suspect that’s the less-common use caseOn Mar 15, 2023, at 7:11 AM, Marcus Olsson ***@***.***> wrote:﻿
This assumes that the user wants to use the template most of the time, which I think is a fair assumption actually.
It would change the default, so it might cause some frustration initially for those who only use templates some of the time. It might be worth it initially though.

**Comment by EntranceJew** [comment]
Weighing in, I'd also find this useful. It's really a chore to take more steps to make a note than the Kanban plugin, including having to tab past the redundant question of what project it belongs to (if i'm doing it from the Board screen, and I can't create a new project via that dropdown, isn't it safe to assume it's for the current project?) especially for getting templates with basic CRUD data such as creation time.

**Comment by jun6lee** [comment]
+1 on at least the option of a default template.

Have only started using this a couple of weeks back and it's pretty intuitive and useful.
I do find it would be significantly quicker for me to add numerous rows if I had had less clicking to do

**Comment by jun6lee** [comment]
I'd go on to add that it would be nice if the "Untitled note" text was already highlighted when I hit the "add note" button.
A couple less keystrokes go a long way when trying to make a 100 new rows swiftly

**Comment by marcusolsson** [comment]
In 1.16.3, the first template is selected by default, and you can now press Enter after typing the name of the note to create it. Should speed things up a bit.

The name field should already be focused by default. Let me know if it isn't.
