### ISSUE TITLE
FR: Support Mocca101/obsidian-plugin-groups with Dataview queries

### ISSUE THREAD

**Issue by Profile8647** [marcusolsson/obsidian-projects#448]
### What would you like to be added?

It looks like obsidian-projects is looking at `app.plugins.enabledPlugins` which will not list Dataview, even when it is technically loaded manually or via another plugin. Could you please check `app.plugins.plugins['dataview']?._loaded` or an equivalent instead?

### Why is this needed?

Even if Dataview is technically loaded manually or via other plugin, obsidian-projects says that "Dataview is disabled."

See: ![image](https://user-images.githubusercontent.com/125712365/223163865-f6831997-aa53-45cb-b6b0-cdf6197120ea.png)

On desktop, I use [Mocca101/obsidian-plugin-groups](https://github.com/Mocca101/obsidian-plugin-groups) to delay the loading of Dataview in my vault as Dataview's loading at startup unfortunately delays Obsidian sync for a few minutes which can be quite frustrating when I'm in a rush and need to reload the app really quick.

To achieve this, Dataview is disabled via the Community Plugins tab and obsidian-plugin-groups, which is enabled, handles Dataview's loading via that plugin's functionality with my config for that plugin.

My obsidian-plugin-groups config (just for Dataview) for your convenience: [data.zip](https://github.com/marcusolsson/obsidian-projects/files/10895565/data.zip)

Thanks!

**Comment by Profile8647** [comment]
Please disregard as I have opened an issue with Mocca101/obsidian-plugin-groups to populate `app.plugins.enabledPlugins` as obsidian-projects is expecting.

Thanks for your time!

**Comment by Profile8647** [comment]
Hi again.

I'm re-opening this because I [worked with the maintainer of obsidian-plugin-groups to try to support the method you are using to detect `dataview` but I ran into a downstream issue](https://github.com/Mocca101/obsidian-plugin-groups/issues/24#issuecomment-1468639394). 

One of the Obsidian devs was kind enough to [advise me in Discord about the proper way to detect `dataview`](https://discord.com/channels/686053708261228577/840286264964022302/1085558080290439178).

Could you please modify [this call](https://github.com/marcusolsson/obsidian-projects/blob/1004cdc690d4d25c1fd8c05a7fd3a855cc236a70/src/view.ts#L61) to use the `app.plugins.getPlugin(...)` method instead of checking `app.plugins.enabledPlugins(...)`?

**Comment by marcusolsson** [comment]
Thanks for the heads-up, I didn't know about the `getPlugin()` call. I'll get that fixed for you!
