### ISSUE TITLE
Does Projects support relations?

### ISSUE THREAD

**Issue by donovanrost** [marcusolsson/obsidian-projects#449]
Does Obsidian Projects support relations like DB Folder? I can't seem to find the option for this.

**Comment by marcusolsson** [comment]
Unfortunately, Projects doesn't support anything... _related_ to that 😈 Puns aside though, could you describe the feature a bit more? I haven't been using DBFolder that much.

**Comment by jimjam-slam** [comment]
I can't speak to DB Folder's implementation much, but if it's Notion-like, I would assume a Relation is a reference to one or more rows in another project/table, and a Rollup is a summary of a field of those rows. For example:

Table 1: team members

Name | Favourite number
-------|-------
James | 23
Yusuf | 13
Riko | 17

Table 2: tasks

Task | Assigned team members | Lowest favourite number |
-----|--------------------------|--------------------------|
Design | Yusuf, Riko | 13
Development | Riko, James |  17
Sales | Yusuf | 13

Here, "Assigned team members" is a relation: it references a number of rows in table 1 (it might format visually as the Name field of those rows, but it function as a reference to the rows themselves). The "Lowest favourite number" is a rollup: it takes the previously defined relation field, Assigned team members, selects a field from the related rows (here, favourite number) and then computes a summary on them (here, the minimum).

That summary could just be identity if one external row is related (eg. Who is the lead for this task, and what is their favourite number?), or it could be some other aggregation function if several external rows are related to each row in the current project (eg. Who are all the team members assigned to this task, and what is the lowest of their favourite numbers?).

**Comment by marcusolsson** [comment]
I hope to release more analytical tools in the future, but each row will likely still refer to a note. 

Here are some ideas I've had:

- Derived fields: Create transient fields that are computations of other fields. While I was initially thinking of things like creating a duration field from two dates, I don't see what the value of each cell could be an aggregated value, say from another project.
- Aggregated fields: For example, in the Table view, you could display the sum for a number field at the bottom of the column, or the number of unique values in a string field.

**Comment by jimjam-slam** [comment]
Fair! To clarify, when I say that a Relation refers to an external row, I don't mean that it would necessarily change the structure of the row it's _in_. A row could still be backed by a single note; it's more a question of how the relation field is modelled. At its most basic, it could be a list of links to other notes.

**Comment by marcusolsson** [comment]
> I don't mean that it would necessarily change the structure of the row it's _in_.

Then it sounds like it would definitely be possible and within the scope of the plugin. 

I'll close this issue since the question in OP has been answered. If you (or anyone else) be interested in something like this, please [create a feature request](https://github.com/marcusolsson/obsidian-projects/issues/new/choose). If possible, since relations is a rather big area, I'd appreciate feature requests describing more specific features.
