### ISSUE TITLE
Input elements in modals are not wide enough. Replicate the "Add template" items where it spans the entire modal

### ISSUE THREAD

**Issue by GitMurf** [marcusolsson/obsidian-projects#45]
Another thing I have been meaning to suggest is that the input boxes in the modals all typically feels too small so you cannot see much of what is in there. I think the way your templates are setup are perfect with the input below the description and full width. I would recommend you make all of them this way. 

![image](https://user-images.githubusercontent.com/64155612/191296424-1303db4a-5c25-48c9-be49-ab7031438d3d.png)

**Comment by marcusolsson** [comment]
Fixed in 0.14.4.
