### ISSUE TITLE
Function nextUniqueFilename is unavailable in subfolders

### ISSUE THREAD

**Issue by Acylation** [marcusolsson/obsidian-projects#454]
### What happened?

When create new notes in a project under a subfolder continuosly, the default filename stays still, instead of giving a unique new name. There is another reactivity problem when we try to create new notes right after swtiching projects.

https://user-images.githubusercontent.com/73122375/225871561-43779481-c7d3-4a17-b5af-a450405e2111.mp4

### What did you expect to happen?

In subfolder, enable next unique filename. After switching projects, the unique filename should be refreshed.

### How can we reproduce it (as minimally and precisely as possible)?

Create a project under a subfolder, than try to add new files continuously.

### Anything else we need to know?

Both `Add note` button in view and the blue `New` button have this problem.

### Plugin version

latest build beyond 1.11.5

### Obsidian version

1.1.16

### OS

Windows

**Comment by marcusolsson** [comment]
Thank you so much for reporting these bugs (and for your recent PRs)! 🙏

I've been afk for a while, but I've finally caught up on issue triage. Starting to work on [prioritized](https://github.com/marcusolsson/obsidian-projects/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2Fhigh) issues this week.

**Comment by Acylation** [comment]
Thanks for the efficient repair! I tried to figure out some of the problems but failed. There is still so much to learn. 😅

**Comment by marcusolsson** [comment]
Feel free to ask if you run into any issues. I'd be happy to walk you through the code base.
