### ISSUE TITLE
How to link views 

### ISSUE THREAD

**Issue by timovirtaneva** [marcusolsson/obsidian-projects#462]
Hi

Thanks for the nice plugin.
I need to link the calendar view to my dashboard canvas. 
I have not found a way.  Is there way to do this?

--Timo

**Comment by marcusolsson** [comment]
I'm not sure I understand the use case. Could you share some more details on this would work?

**Comment by timovirtaneva** [comment]
Hi

I would like to see the calendar without opening the project.

I’m using canvas to collect my important notes. 
The have the calendar view embedded in the canvas would be nice. I could see the project timing with other documents.

Like in the attached picture

—Timo

￼

**Comment by marcusolsson** [comment]
I haven't been looking at how to integrate Projects with Canvas yet, but I don't think you can create custom embeds for canvas. That sounds like something Canvas would need to add, but not sure.

**Comment by timovirtaneva** [comment]
OK. Thanks.

I will take another approach to solve my need.

—Timo

**Comment by jessicamindel** [comment]
Hello! Thank you indeed for a fantastic plugin! I come bearing a similar request: the ability to link a Project in any note (albeit not necessarily in a Canvas). The use case: given the Notion-esque style of the views Projects offers, I'd like to be able to embed a kanban board or gallery view in a note as part of a dashboard of current projects.

Is there any way to reference a Project (or a view within a Project) in a note? Many thanks!
