### ISSUE TITLE
Improved filtering for array type fields

### ISSUE THREAD

**Issue by rolandhesz** [marcusolsson/obsidian-projects#464]
### What would you like to be added?

Currently the only option I can see when trying to filter based on field that is an `array` is `s empty` or `is not empty`
The example in the screenshot is for `tags`.

![image](https://user-images.githubusercontent.com/13273796/226929489-66a7cea9-6d43-4bff-8b1d-b4ec72ee8a12.png)

It would be great if `array` type data fields had the same options as `string` type fields, like `name`, i.e., `is empty`, `is not empty`, `is`, `is not`, `contains` and `does not contain`.

![image](https://user-images.githubusercontent.com/13273796/226929975-e1c4ddac-f758-492d-bf29-d5f6af1f574a.png)

### Why is this needed?

It's needed because - in my case - `tags` are one of the easiest way to filter different types of notes, like when building a board that shows user stories it would be much easier to  filter `tags contains user-story` rather than `name contains "User Story"` or `path contains "User Stories"`.

**Comment by marcusolsson** [comment]
Closing in favor of #447.
