### ISSUE TITLE
More options for how columns are displayed in tables.

### ISSUE THREAD

**Issue by tektrip-biggles** [marcusolsson/obsidian-projects#474]
### What would you like to be added?

Absolutely loving what you've done with this plugin so far. Have been tweaking things a little via css but it would be great to have proper support for:
1. Choosing horizontal alignment for each column, whether left-aligned, right-aligned or centred.
2. A general setting to hide the "column type" icons, which can lead to columns needing to be wider than otherwise necessary.
3. For columns where specific "options" have been configured, the ability to assign a colour for each of those options.
4. (related to the above) the option to show _all_ options when clicking on a cell in a column with set options (at the moment, the currently selected option acts as a "filter" for the list, so you need to click → delete selected text → select new option)

### Why is this needed?

1. Some columns, especially ones with very short values would be easier to parse at a glance when centred rather than aligned to one edge or the other. (Note: this can currently be implemented by the user via css workarounds)
2. For some users, this information does not need to be displayed once the view has been configured & hiding the icon will both reduce visual clutter and allow more columns to fit into the available horizontal space. (Note: this can currently be implemented by the user via css workarounds)
3. For columns that represent categories it can be much easier to identify those categories at a glance by using colour. Note that this _cannot_ currently be implemented via css workarounds as far as I'm aware.
4. Switching the category for a row is a common use case & it is a common workflow to wish to do this many times in quick succession for many rows. Currently this requires 2 mouse clicks as well as use of the keyboard. It would streamline this common workflow to not require any keyboard input.

**Comment by marcusolsson** [comment]
Thanks for the kind words! I'm glad you're finding the plugin useful! ❤️ 

I'm grateful for the suggestions, though I'm afraid I need to ask you to split the issue in multiple issues. I'm using reactions to gauge how many are asking for a feature, and it would be difficult to know which of the four feature people are asking for.

I think 1, 3, and 4 are pretty straight-forward, and within the scope of the plugin 👍 

I'm a little more hesitant to 2. Sounds like the need is to be able to fit more columns on screen, which I think there might be more ways than one to accomplish.

I'm closing this feature in favor of separate issues for each feature request.
