### ISSUE TITLE
Can’t change field type

### ISSUE THREAD

**Issue by m1chaeljmk** [marcusolsson/obsidian-projects#476]
### What happened?

In table view, I go 3 vertical dots → configure field → type (dropdown)

nothing shows when I click the dropdown menu

I don’t see where or how to change the field type, e.g. to turn it into a date or a status or a toggle

### What did you expect to happen?

I expect to be able to change the field type by clicking on the dropdown

### How can we reproduce it (as minimally and precisely as possible)?

See “what happened” 

### Plugin version

1.13.0

### Obsidian version

1.1.16

### OS

macOS

**Comment by marcusolsson** [comment]
Being able to change the type is planned but not yet supported.

Adding predefined values for a field allows you to auto-complete the field, i.e. it's still a "text" field, and not a "select" field.

I've updated the description for both properties to clarify this. Thank you!
