### ISSUE TITLE
Re-order color conditions

### ISSUE THREAD

**Issue by TomWol** [marcusolsson/obsidian-projects#480]
### What would you like to be added?

I want to be able to drag the different color condition lines set up in a Board view to re-order them. 

There could be a visual icon which allows you to drag the condition line up or down.

### Why is this needed?

Assigning colors to Board cards based on matching a certain condition is great. 

However, it seems that when a card matches two color conditions, it is the order in which the conditions themselves are created which defines which color gets assigned. Visually this is the top one in the condition list.

I am all for prioritizing the conditions with top priority at the top, but please let us rearrange the order by dragging the different condition lines. If I want to alter the color for a particular note matching multiple conditions, I have to start altering and deleting the conditions and that is a little counter-productive. Thanks!

**Comment by Acylation** [comment]
Working on this.
