### ISSUE TITLE
Hide the 'Unprioritized' section of a Board view column when all are empty

### ISSUE THREAD

**Issue by TomWol** [marcusolsson/obsidian-projects#481]
### What would you like to be added?

When all 'Unprioritized' sections are empty in a Board view, I would like for these sections to be hidden.

I understand you could need them when dragging cards, it makes sense that when you start dragging a card they show up again. But if they are still empty when the dragging it stopped, not showing them will take up less space in the view.

This could be a setting to turn on or off in the Board settings modal.

### Why is this needed?

I create all project notes with a template that sets a default priority weight field (for now, I'm looking forward to #451 because I solely create this priority field for Projects). 

This means my notes are never Unprioritized, leaving a block of empty space at the bottom of every Board column. 

I understand the need for it to be there when you drag notes (because then you can drag them into Unprioritized). But I'd find the Board view a lot cleaner when all those empty sections are not there. Thanks!

Related to #68 but not exactly the same.

**Comment by Acylation** [comment]
Resolved as the prioritize are deprecated by new sorting options, PR #584.
