### ISSUE TITLE
[Feature] Sort by file creation time (or by any field)

### ISSUE THREAD

**Issue by m-primo** [marcusolsson/obsidian-projects#497]
### What would you like to be added?

Sort items (files) in the project views by at least file creation time, and it'd be great if we can sort by any field.
I know I could be doing it by changing the project data source to dataview, but it'd be better if it's implemented that way.

We would need to add a field that automatically add the creation time in the file or just extract the file creation time, ig the best way is to add the creation time as a field.

### Why is this needed?

It'd increase productivity and be more reliable instead of sorting by z-a file name or whatever.

**Comment by marcusolsson** [comment]
Closing in favor of #275.
