### ISSUE TITLE
[Bug] Add file is not working in Gallery View

### ISSUE THREAD

**Issue by m-primo** [marcusolsson/obsidian-projects#498]
### What happened?

![image](https://user-images.githubusercontent.com/44984918/232247618-6ff91f13-c810-428c-804a-b13859355a65.png)

Clicking on "+" doesn't work in Gallery View.

### What did you expect to happen?

Add a file.

![image](https://user-images.githubusercontent.com/44984918/232247649-3be280f8-b7c8-4983-943a-c7dbb84c23df.png)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Projects and open any project with Gallery View.
2. Click on "+".

### Plugin version

1.14.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by Acylation** [comment]
Thanks for the report and I've submitted a PR to fix it. ❤️
