### ISSUE TITLE
Adding Resource Pool to Project Plugin - Obsidian

### ISSUE THREAD

**Issue by MarounnSader** [marcusolsson/obsidian-projects#510]
### What would you like to be added?

hello,
is there a way to add resources pool to the tasks, this way we can see idle resources and assigned resources? can we add this function to the plugin?

i know we can use YAML for that, but this will show only the assigned ones, we can have a look how many resources are assigned and how man are not

### Why is this needed?

this will help to track resources across the porjects

**Comment by Acylation** [comment]
@MarounnSader 

For now, actually we have ways to allocate them. Only to set the predefined values (in your example, team members) in Table view, then you can fill the cells easily with the help of auto-complete. You can even check their tasks and flexibly adjust them through the Board view.

https://user-images.githubusercontent.com/73122375/233384685-1a5f262b-9ab6-401c-b82f-41ed941fa532.mp4

A better UX would be accomplished by providing single select and multiple select components, as well as keep show board column with no card in Board view to know the idle ones (related to #482 ).

**Comment by MarounnSader** [comment]
OH @Acylation , you made the view i want!
the one with resource name but with empty box under it...

can you send me the steps exactly? also do i need the priority column to achieve that, from what try is to create a 13 placeholders (my team) then add all backlogs with the actual tasks owners and then just modify the status

i will try it this way hope it will work? what the priority actually does here?

**Comment by Acylation** [comment]
After the predefined values set in Table view, you can
1. Create a placeholder note for each option (member)
2. Create a Board view and set the `Status` field as the name of resource category. The board uses `Status` field to create columns. You can change the name of the view by double clicking the view tab title / view selector.
3. Set filters in both views to exclude placeholder notes
4. Create tasks and assign you members

By adding a number field as priority, you can drag and drop the task cards in the Board view to reassign the task to another people, as well as sorting the cards. You can simply set the priority field to `None` to see the difference. 

If this has already satisfied your case, I suggest that we convert the issue to discussion as a showcase. Or we can just leave it here if it needs further coding. (cc @marcusolsson , thanks and glad to know you opinion 🌹 )

**Comment by MarounnSader** [comment]
Thanks a lot for the help, yes please do the needful to help the community appreciate your help all of you


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
