### ISSUE TITLE
[FEAT] Editing fields when creating new note

### ISSUE THREAD

**Issue by zuluwi** [marcusolsson/obsidian-projects#54]
Can you add the fields of the selected project to the create new note modal, as in the edit note modal?

**Comment by marcusolsson** [comment]
Hm. I think this is mainly tricky from a UX standpoint. For example, how would you like it to work if you also select a template? I'm a little hesitant since it seems like a nice-to-have, right? You could edit the values you want as soon as it's created. Or am I missing anything?

**Comment by marcusolsson** [comment]
Did you add your template to the project when you created it? If you did, you can select the template directly from the Create note modal. Any context-specific values, like date in the Calendar view, override the value in the template however.
