### ISSUE TITLE
Lost the "+Add note" at the bottom of dataview pages AND the dark drop down on the Project NavBar

### ISSUE THREAD

**Issue by WebrangerC** [marcusolsson/obsidian-projects#540]
### What happened?

The "+Add note" seems to not work with the dataview source.
The missing drop down on the right side of the Project NavBar seems to be missing since the last update  (it was the way I added notes to dataview source projects)

### What did you expect to happen?

I had originally expected to see the "+Add note" at the bottom of my dataview table as if the source was a tag.
Overall I expected there to be a way to add  a note which was placed in the project directory per the setting. This was the case with the "add note" in the drop down.

### How can we reproduce it (as minimally and precisely as possible)?

All I did was run the Project update from the Community Plugins under settings. I an running Project v1.15.0 in  Obsidian-1.1.16.AppImage. In projects using source folder or tag, the "+Add note" exists at the bottom of the table. It is not there for source dataview. With this Obsidian/Project combination the dropdown is missing.

### Plugin version

Project v1.15.0

### Obsidian version

Obsidian-1.1.16.AppImage

### OS

Linux

**Comment by marcusolsson** [comment]
We removed the New button in the upper-right corner. You can still create notes from the views and the command palette.

Board and Calendar views need to edit metadata when adding them, which isn't supported for Dataview projects. That being said, Table and Gallery view don't need to add any metadata to new notes, so they should be allowed to add notes.

I've released 1.15.3 with a fix.

**Comment by WebrangerC** [comment]
Thank you. Just updated and verified that the '+Add note' is back in the table view.
I am using a single vault as a Life OS (life manager connecting goals with activities to meet those goals and KM (pkm) to support the activities. I have found Projects to be my 'home-base' for daily use (although canvas may soon match it supporting brainstorming and navigation) after struggling with the wire&tape method you described.
Using Templater and the +Add has allowed me to customize new notes (when the notes are entered directly to the right directory, which is why this issue became an issue when the "New" button disappeared (not a complaint about the new design).

**Comment by WebrangerC** [comment]
Yes, that is what I do, but it did not work from the command palette. Again, why the loss of the 'New' button was problematic. 
Wire&tape:  your description of the motivation for creating Projects. I was using Tasks and dataview along with QuickAdd and MetaEdit. I haven't added a new Goal (Personal Focus => Goal =>  Projects => Tasks) with KM supporting Tasks recently so I'll probably need to update QuickAdd/MetaEdit when I do.

**Comment by marcusolsson** [comment]
> but it did not work from the command palette

That sounds like a bug. They should be equivalent. Let me have a look at it 🙏

**Comment by WebrangerC** [comment]
I expected that the command palette didn't have access to the referring page/plugin so I did not find this to be surprising (a bug).

**Comment by marcusolsson** [comment]
You're correct that when you create a note from the command palette, it doesn't know which project you want to add it to, but if you select the project from the dropdown, it should use the new-note location for that project. 

The only difference between the command palette and the earlier New button was that the button could select the active project as the default.

**Comment by marcusolsson** [comment]
You're helping _me_ here! I appreciate your patience helping me understand.

Obviously, I want changes to be for the better, so if you lost your workflow, I'd like to fix it if I can :)

**Comment by WebrangerC** [comment]
The 'sorry' was for needing dataview more than projects (by a little). No this workflow for Activity management is really good. I had 'automated' the creation of the flow from a goal to tasks using the more plugins before. I don't expect Projects to solve all my specialized workflows. It DOES solve my Activity ones. Actually more than that as it is also acting as my index for information associated with projects, spheres of responsibility and interests. I had started trying to document my intents at bylos.net but have become very busy and have not stabilized my process yet (I am still migrating from P.A.R.A.).
