### ISSUE TITLE
Calendar View Cannot Create New Notes

### ISSUE THREAD

**Issue by acook** [marcusolsson/obsidian-projects#543]
### What happened?

Right clicking and then selecting "new note" or double clicking on the calendar does not create a new note. There are no errors in the developer console, just nothing happens at all.

### What did you expect to happen?

A new note to be created.

### How can we reproduce it (as minimally and precisely as possible)?

From a sandbox vault, create a new project, create a calendar view for it, and the attempt to create a new note by double or right clicking.

### Anything else we need to know?

**Background**

I was trying to figure out how to display notes on the calendar when I encountered this issue. I can't see any help documentation that explains what frontmatter field is used for calendars. I created a `Due Date` field using DB Folder, but that seemed to have no effect. 

### Plugin version

1.15.2

### Obsidian version

1.1.16

### OS

Linux

**Comment by marcusolsson** [comment]
@Acylation is correct. You can't create notes in Dataview projects. You can find more information in #65.

It's not obvious though. Maybe we should show a message to let people know.

**Comment by marcusolsson** [comment]
Something like this maybe?

<img width="417" alt="Screenshot 2023-04-26 at 19 27 14" src="https://user-images.githubusercontent.com/8396880/234655343-ed776ca2-7d75-485b-817b-c6457911c0c5.png">

**Comment by acook** [comment]
I think those are good ideas.

However, these are not dataview projects, just standard folder projects. This is taken from my main vault, but the same problem exists in a sandbox vault for me.

![Screenshot from 2023-04-26 15-02-41](https://user-images.githubusercontent.com/71984/234689531-3d974e5c-fea0-4220-b96e-d0a5cef86e94.png)

**Comment by marcusolsson** [comment]
To be able to create calendar events, you need to have set metadata property to use as the date field (the Date drop-down) in the upper-right of the calendar view.

Without setting the Date field, the plugin doesn't know what the field name should be.

Should probably display a message when attempting to create notes without first setting the Date field.

**Comment by acook** [comment]
You might not be able to tell, but the `Date` dropdown is greyed out. I can't click into it at all.

In the sandbox, I added a couple of different date fields in different styles to the frontmatter. Despite this, the `Date` button is still unclickable.

![Screenshot from 2023-04-27 09-10-16](https://user-images.githubusercontent.com/71984/234889613-d38e326a-5bab-4f90-b0d3-56a45c9292c7.png)

There doesn't seem to be a way to add columns natively in Projects that I can find?

![Screenshot from 2023-04-27 09-15-43](https://user-images.githubusercontent.com/71984/234890256-18d96846-5249-4d24-b44b-5a53c3228fb4.png)

I noticed that the symbols next to the field names indicated that Projects had interpreted those values as numbers and text for some reason. I assume this is why the `date` button isn't finding it.

![Screenshot from 2023-04-27 09-18-27](https://user-images.githubusercontent.com/71984/234890762-0aa0671d-f9fb-42a5-abc4-b87635c5adaf.png)

The field type cannot be changed either. 

Given all this, I am perplexed them as to how the articles in the readme were able to set up date columns, which is clearly shown in their screenshots.

**Comment by marcusolsson** [comment]
As you probably guessed, the Date select only lets you select date fields. But since you don't have any, it's greyed out.

However, `date1` is a correctly formatted date, and should be interpreted as such. That looks like a bug. Do you have a `date1` field in the other notes?

**Comment by acook** [comment]
Only that one note has it. You can check out the current state of the data in the table view screenshot. As I had intended to use it for like due dates and things, or have it share locations with DB Folder, so it won't really be possible for everything to have a preset date field.

**Comment by Acylation** [comment]
Still can't reproduce it. Can you try to follow this procedure to create a date field?
- Create a new note
- Add YAML, with a date field (in the format of YYYY-MM-DD as you have done above, and make sure that there's no other type of value sharing the same field name in any of the notes tracked by the project)
- Move the cursor out of the range of YAML and click 
- Reopen Projects tab to see if the field is correctly created

**Comment by acook** [comment]
Confirmed working on latest. Whatever the issue was has been fixed. 

- Projects doesn't require all notes to have a filled in date field.
- Simple YYYY-MM-DD dates appears properly in both the table view cells as well as the Date dropdown in Calendar.
- While changing field type is not supported yet, the dialog box explains this, making for a less confusing experience.

I can see a lot of little tweaks and improvements from the last few months.

Thanks!
