### ISSUE TITLE
incompatible with "Default New Tab Page"-Plugin

### ISSUE THREAD

**Issue by nousernameavailableanymore** [marcusolsson/obsidian-projects#552]
### What happened?

Projects wont open if "Default New Tab Page" is enabled and set to "New Tab opens": "New Tab page".

Trying to open projects simply opens the default new tab page.

Solution: simply open projects in the current tab

### What did you expect to happen?

Projects gets opened in current tab

### How can we reproduce it (as minimally and precisely as possible)?

- install "Default new tab page"-Plugin
- set it to "New Tab page"

### Plugin version

latest

### Obsidian version

latest (non-insider)

### OS

Windows

**Comment by usernotnull** [comment]
+1
For reference: https://github.com/chrisgrieser/new-tab-default-page

**Comment by Acylation** [comment]
Reproducible, but it sounds more like a bug of the `new-tab-default-page` plugin to me, and should be discussed there. Here are the [possible bug lines](https://github.com/chrisgrieser/new-tab-default-page/blob/573cd5fdc34e2231125763af32780ec0ae508b33/main.ts#LL47C1-L49C8).

**Comment by usernotnull** [comment]
I confirm. I also noticed the new-tab-default-page interferes with the new bookmarks core plugin. I opened another issue for it, hoping it's linked to the same bug as the one affecting Projects.

**Comment by joriswvanrijn** [comment]
I can confirm that this is a issue with the new-tab-plugin. I've created a PR as a fix:  https://github.com/chrisgrieser/new-tab-default-page/pull/18
