### ISSUE TITLE
Not able to make new fields, change fields, and table collapses when editing a field title.

### ISSUE THREAD

**Issue by polyinnovator** [marcusolsson/obsidian-projects#557]
### What happened?

There are no buttons (+) to add a column in order to make one. The only way I've seen that semi works is the YAML data on the note itself, which isn't even fully working because it only creates text fields regardless of what I put. Url or status, etc.

Then I am not able to change the column either as "changing type isn't supported yet".

### What did you expect to happen?

Well I am spoiled from notion's fluidity, but I expected to be able to make new fields easily, and that would edit the note as well. I did not choose "dataview" option either, just the tags option, but I think I've tried the folder one too.

This is I think the fifth time I've tried this plugin this week.

### How can we reproduce it (as minimally and precisely as possible)?

The table collapse is the only thing you'll need to reproduce, and that was simply editing the title for the column field.

### Anything else we need to know?

Feel free to reach out.

### Plugin version

1.15.3

### Obsidian version

1.2.8

### OS

Windows

**Comment by Acylation** [comment]
I recorded the field creation process to reproduce this in following steps:

1. In a new note in the target folder, add new YAML field
2. Check Projects, the new filed is recognized as `Text`
3. Put a valid date value to the field, right in the note (notice that the cursor is at the end of the line)
4. Reopen Projects, and the new field is still detected as `Text`
5. In the note, move the cursor elsewhere, and the `Date` type is assigned finally

https://github.com/marcusolsson/obsidian-projects/assets/73122375/15d824df-e972-4403-a602-cede90e99b18

Seems like reopen the Project view would solve the problem. 

The misidentification of the field type when the cursor at the end is likely a bug, and add field in the Table view may be a separated feature request.

**Comment by polyinnovator** [comment]
That still doesn't help the tags or status tag cause they aren't changing to tags. Also I've been trying the reopening project view. that helped with the columns appearing, but it didn't with the changes. It did however in my testing just now (not the other day) with the date. That worked this time.

Also there was a crucial missed point from my issue. The bug that I was sharing. I tried to take a screen vid but OBS was crashing for some reason. Basically I'd try to change the width or click on the top and it would collapse all the way to just the first column.

No idea why.

**Comment by polyinnovator** [comment]
I also thought that the issue with the table not being able to change the type was because of dataview, and so if using yaml on its own would solve that, but I guess not?

**Comment by polyinnovator** [comment]
Hey this is still an issue. Your responses didn't solve the problem. The collapses have decreased in frequency at least, but the issue of column types persists. Regardless of what I put in the metadata it just always defaults to text, and it won't change. In the metadata of the doc or in the projects view if I try to change something. Still says "changing type is not supported" yet I never was able to declare the type. Projects just treats it as a text, even dates if they are more than the word "date" (which I have a "Do date" and "published date")

**Comment by Acylation** [comment]
Sorry for my postponed reply and for some possible misunderstanding (as I'm not a native English speaker). So I would make some clarification, as well as require more info.

Seems like you are using `Tag` as your data source, and that's how it works:
- Include notes that contain the certain tag you typed in the `Edit project` modal.
- Generate `table` and other views according to the YAML metadata of the note.

Field types are auto-detected according to your YAML. If all the values of a field, let's say, 'pub date', are in the format of `YYYY-MM-DD` (only the format is supported now, #309 FYI), then the field will be recognized as `date` type. As mentioned above, the cursor at the end of the line should be avoided, and sometimes reopening the `Projects` tab is helpful. There's nothing related to the field name.

I suggest you test the `Tag` data source with the notes provided in the demo project, which shows when you first install the Projects plugin. You can create a new vault to test it. The tags in the YAML are also supported. Create a new project using the `Tag` data source, and observe if the date field is correctly detected and rendered.

---

> Regardless of what I put in the metadata it just always defaults to text, and it won't change. In the metadata of the doc or in the projects view if I try to change something. Still says "changing type is not supported" yet I never was able to declare the type. Projects just treats it as a text, even dates if they are more than the word "date" (which I have a "Do date" and "published date")

About the typecasting, I would say this is 'as design', and isn't supported yet, you can check #558 to get more info.

---

> The table collapse is the only thing you'll need to reproduce, and that was simply editing the title for the column field.

> Also there was a crucial missed point from my issue. The bug that I was sharing. I tried to take a screen vid but OBS was crashing for some reason. Basically I'd try to change the width or click on the top and it would collapse all the way to just the first column.

I just can't reproduce it, maybe I need more detail. What does it look like after the table collapse? (Seems like only the first column survives, the name column right?) And about editing the column field, do you mean that you are changing the column name in the `Configure field` modal? But I observed nothing wrong when changing the names. Notice that the `name` and `path` shouldn't be modified.

The table collapse sounds like a severe bug, and I'd like to figure it out, with your help to reproduce it.

Hope this would help you. Further discussion on this is welcome.

**Comment by Acylation** [comment]
Oh, got it. It's sorry that for now, only when you get all the values that belong to the same field name correclty typed, can the field be detected as date. It's a hard work if you have so many notes migrate from notion. More date formats support is scheduled, so if you don't want to change the date formats manually, you can wait for the impliment. (may take several months)

> It also doesn't explain why tags, status, or links are not showing up correctly.

Tags need to be formatted in the YAML too.
![image](https://github.com/marcusolsson/obsidian-projects/assets/73122375/08e75fdf-5813-4cdd-8ce7-4bd943afe77a)

To enable link rendering, you can enable rich-text formatting in text fields' configure field modals.
<img width="418" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/73122375/283e8322-41fe-4c24-bda5-62c8b8fd3853">

What are you refer to when talking about `status`? Maybe some notion examples are enough.

**Comment by polyinnovator** [comment]
![image](https://github.com/marcusolsson/obsidian-projects/assets/40401528/3cc7d6d1-51d4-491b-b717-5a61fa4faf81)
I tried making sure the dates are formatted correcting, I still don't know why it isn't working. Ironically I made a typo in one field that I added today. Published Date instead of Publish Date, and it formatted to date property correctly.

I get that this plugin is still new in the grand scheme of things, and there is a lot to do/going on. Although some of these thing are basic use cases or issues, that other people have had too from what I've seen from the forums.

**Comment by Acylation** [comment]
Would you mind checking the notes details in the `.md` file, rather than only in the table view? There's a guess that, in some of your notes, if you have an empty value of a potential date field (but in text field temporarily), and you edited it manually in the table view, the value would be quoted, yielding someting like `Do date: ""`

To modify this, you may use tools like VSCode, or other text editors that supports find and replace, to remove the whole line containing quotation marks. (Including the field name, to avoid generate quotation marks again). Another solution is, since the quoted date field value can also be detected, i.e. `Do date: "2023-05-31"`, so filling all empty cells in the table view can also fix this.

This is indeed a bug that the quoting criteria are some times disturbs editing, especially migration from other note-taking applications, and the type system do need to be imporved (#76 )

**Comment by polyinnovator** [comment]
Tags should be formatted correctly, and I'll see if the rich text switch will fix links. Thanks.

as for dates that really sucks, that ALL of them have to be correct. It is probably around 1000 published content pieces, and close to that number for content ideas. I actually have to go through all of them and tag them anyways for Obsidian's graphing 

Alright let's table this issue for now.
