### ISSUE TITLE
Add an Archive Project option 

### ISSUE THREAD

**Issue by Nergatar** [marcusolsson/obsidian-projects#559]
### What would you like to be added?

I would like an option to Archive a project, and maybe also an option to Activate an archived project.

### Why is this needed?

I work with the folder projects system, keeping the projects in sub folders of my projects folder. When a project is done (or get paused for a long period) I archive the project by moving the project to an archived_projects folder. Since I don't want to see an archived project in my active projects I have to delete the project in Projects as well.

If for any reason the archived projects needs to get activated I need to move the project folder back to my projects folder and I need to create a new project in Projects.

An alternative could be to just Archive the project in Projects to not see them in the Projects dropdown folder and then an option to reactivate an old project if needed.

**Comment by Acylation** [comment]
Related to #523

**Comment by marcusolsson** [comment]
Just to clarify, you want to be able to hide a project in the projects drop-down? We'd probably need to remove any commands related to that projects or its views as well.

I imagine we'd need to list all archived projects under Settings, so you could "re-activate" them again.

**Comment by Nergatar** [comment]
Yes, remove them from the projects drop-down is what I am looking for. When it is reactived I would like it to be back as it were before it was archived, with the same views. So I dont see the removal of the Views as a good option. (What commands are you speaking about)?

**Comment by Acylation** [comment]
Would like to work on this.

**Comment by Jnolcox** [comment]
> Would like to work on this.

Would like to work on this as well

**Comment by marcusolsson** [comment]
@Acylation If you still want to work on this, feel free (otherwise, go ahead @Jnolcox!)! I think it's a useful and straightforward feature 👍

**Comment by Acylation** [comment]
Sorry I’ve been busy with finals lately, it would take weeks for me to finish this issue. So I’m gonna step away for a bit and look for other work when I come back. Thank you @Jnolcox being interested in contributing to the plugin! If needed I will help this.

**Comment by marcusolsson** [comment]
Best luck with the finals! 🙏

**Comment by remainedmind** [comment]
I'm new to Projects plugin and I was wondering how can I archive completed projects. So, now I will wait until you, guys, add this feature!
