### ISSUE TITLE
Project board does not update when notes are moved out of project folder

### ISSUE THREAD

**Issue by ScottKillen** [marcusolsson/obsidian-projects#561]
### What happened?

I moved a note out of the project folder, I had a project opened, but it did not update to remove the note.

### What did you expect to happen?

I expected the note to be removed from the project. (The project updates correctly when file names or metadata change.)

### How can we reproduce it (as minimally and precisely as possible)?

2. Create a note in a folder.
3. Create a new folder project using that folder.
4. Move the note somewhere else.
5. See that the note remains in the project.

### Anything else we need to know?

If you close the project and reopen it the changes are reflected correctly.

### Plugin version

115.3

### Obsidian version

1.3.1

### OS

Windows

**Comment by Acylation** [comment]
Reopening as a user reported a similar problem. This can be achieved by listening to the source folder on folder based projects. However, to adapt tag & dataview datasources, we need to find out how to monitor changes. Otherwise a refresh button is acceptable.

**Comment by Acylation** [comment]
Sorry for the long wait but this will be fixed in the upcoming version.
