### ISSUE TITLE
Show fields as readonly in a Dataview Project

### ISSUE THREAD

**Issue by m-primo** [marcusolsson/obsidian-projects#562]
### What would you like to be added?

Show the fields with its value but as read only.

A pic for more clarification:
![Screenshot 2023-05-18 015800](https://github.com/marcusolsson/obsidian-projects/assets/44984918/6376af0e-fde2-4c9a-ae4f-5f7197842779)

### Why is this needed?

It'd be great to view data as the folder project.

**Comment by marcusolsson** [comment]
I agree, the current solution was a quickfix, but it would be more useful to mark the individual fields as readonly.
