### ISSUE TITLE
Support nested tags in creating project

### ISSUE THREAD

**Issue by wwjCMP** [marcusolsson/obsidian-projects#564]
### What would you like to be added?

When creating projects using tags, nested tags of the second level are not recognized. For example, if a project is established using the tag #A, it will not include projects with tags such as #A/B, #A/C, etc. 

### Why is this needed?

When creating a project using #A, it is hoped that files with nested tags including #A/B, #A/C, #A/D/F, etc. can all be included.

**Comment by Acylation** [comment]
https://github.com/marcusolsson/obsidian-projects/discussions/549, FYI

**Comment by wwjCMP** [comment]
> #549, FYI  #549 ，仅供参考

thanks
