### ISSUE TITLE
2 independant folder for 2 views

### ISSUE THREAD

**Issue by MaximeGuyot1** [marcusolsson/obsidian-projects#573]
### What would you like to be added?

Hello, i would like to have 2 folders for 2 differents views, for example a folder where i stock all my notes and i could access with a table view and a folder where i can stock tasks, events... and which i could access with a calendar view

### Why is this needed?

Actually i can do that but it need two projects and we need to switch project and it's not practical

**Comment by Acylation** [comment]
Here's an quick hack. You can set up a project on a parent folder that includes the two folders you want to manage, and enable the option 'Include subfolders' in project settting.

<img width="415" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/73122375/8976d810-4d8a-4087-ac0e-977eebbcee6d">

Then, you can use filters on path field to manage the two folders separately, as long as the folders have unique names.

<img width="729" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/73122375/2b4ef2f9-92ee-4364-8162-099dfccbb3a4">

**Comment by MaximeGuyot1** [comment]
Okay, thanks for the tips, i'm news on the plugin so i didn't know, sorry for the useless issues then, do you know if i can activate the hours on the calendar view, like on google agenda where you can setup the times of your events... ?

**Comment by Acylation** [comment]
No worry, you are welcome to ask any questions, and the [Discussions](https://github.com/marcusolsson/obsidian-projects/discussions) section is prepared for that.

> if i can activate the hours on the calendar view,

Unfortunately for now, Projects plugin only support the granularity of `date`, and the `datetime` feature is requested but takes time to develop. (#390)

**Comment by MaximeGuyot1** [comment]
Thanks for letting me now, have a nice day !
