### ISSUE TITLE
[FEAT] Displaying wikilinks in each view

### ISSUE THREAD

**Issue by overZellis133** [marcusolsson/obsidian-projects#58]
Overall, it seems that if there is a wikilink in the frontmatter, it won't pull into the Table view. I'd love if wikilinks could be pulled into the Table view so that I can use the Table view to more easily navigate when I am using the frontmatter for specific inter-note linking

I did a further writeup describing this and showing some screenshots here:
https://docs.google.com/spreadsheets/d/1bvBZEEBnGX_RPV_I4pr5LAHikZ0TdWgABBr9LE1PynA/edit?usp=sharing

**Comment by marcusolsson** [comment]
Looks like this is a limitation in the Dataview API. When you have comma-separated links the dataview query only returns the first one.

If you can reproduce this with single link attributes, could you provide the Markdown content, and the Dataview query so that I can reproduce it?
