### ISSUE TITLE
Link to Project in another note

### ISSUE THREAD

**Issue by Tanjamuse** [marcusolsson/obsidian-projects#589]
### What would you like to be added?

I would love the opportunity to create a link to a project in another note.

### Why is this needed?

It would make it so much easier to see if I've created a project/database for whatever it is I've got in that folder.

**Comment by jebeaudoin** [comment]
If I understand your request, you want to be able to place a link in note that would open a specific project?

I've been able to do this using the Advanced URI plugin. I've got the latest Obsidian build on a Mac. Here are the steps I use:
1. Install the Advanced URI plugin (I don't think you need to change any of the settings).
2. In the options for the Project plugin, look at the Commands section. In the screenshot below, I've toggled "Building My IWE" on. This means that it will now show up in Obsidian's Command Palette.

![Screenshot 2023-06-29 at 8 43 32 AM](https://github.com/marcusolsson/obsidian-projects/assets/10992411/5f936e23-5311-446e-a6db-fddbc2f3f27b)

3. To get the link to this project, call up the Command Palette and select "Advanced URI: copy URI for command"
4. The Command Palette interface then asks to select a file. Choose "<Don't specify a file>" at the top of the list.
5. The Command Palette interface then asks to select a command. Start typing "Projects" and the command list will narrow the results to commands associated with the Projects plugin. In the screenshot below, you can see the selection for "Projects: Show Building My IWE" - that's the link I'm looking for, so I'll select it.

![Screenshot 2023-06-29 at 8 50 06 AM](https://github.com/marcusolsson/obsidian-projects/assets/10992411/e06658ec-e397-425d-9449-eb3127397a7f)

6. Now the Advanced URI Plugin notifies me (with a little badge in the upper right hand corner of my screen) that "Advanced URI copied a link to the clipboard."
7. With the link copied to the clipboard, I go to the note where I want to place it and simple paste it in. It will look something like this: "obsidian://advanced-uri?vault=yourvaultname&commandid=obsidian-projects%253Ashow%253A8139ek70-9az1-8zd6-821n-fbm9e712e2a5)"

This makes it look much harder than it is to execute. If I figure out how to do it, I add a screen capture to illustrate just how easy it is once you start.

jack

**Comment by Tanjamuse** [comment]
Hi.

First of all thank you for the very thorough explanation.

I made the link, but when I try to click on it, I get the following error:

![Obsidian](https://github.com/marcusolsson/obsidian-projects/assets/15678057/cc20bc07-b2f9-4d2b-b26e-dae792c69cff)

The link is:

[[obsidian://advanced-uri?vault=Obsidian%20Sandbox%20(mynamevault)&commandid=obsidian-projects%253Ashow%253A5ee479c5-9579-4999-89be-8948d2bb9730]]

**Comment by jebeaudoin** [comment]
It looks like the name of your vault is "Obsidian Sandbox (mynamevault)" and I wonder if the parentheses () are causing the error. Can you try it on a vault without any special characters in the name?

**Comment by jebeaudoin** [comment]
Here's the screen capture version

https://github.com/marcusolsson/obsidian-projects/assets/10992411/a34d88a0-9e40-458a-a234-db34eb11715c

**Comment by Tanjamuse** [comment]
It works now. I think I was missing the last step you do in "creating" a name for the link.

Thank you so much for your patience, and for the fantastic plugin.

**Comment by jebeaudoin** [comment]
I'm happy to help, but I am only a fellow user of the plugin! @marcusolsson is the fellow who deserves all the credit!

**Comment by Tanjamuse** [comment]
Then I will thank you very much for your patience and send my thanks to @marcusolsson for the amazing plugin.

**Comment by marcusolsson** [comment]
@jebeaudoin Thanks for helping out! 🙏 

For anyone dropping in, I also have a guide on how to do this in the FAQ:

https://github.com/marcusolsson/obsidian-projects/discussions/377
