### ISSUE TITLE
Need to understand the creation fields better

### ISSUE THREAD

**Issue by stoweboyd** [marcusolsson/obsidian-projects#59]
I create a project, but I don't know how to configure it using the dialog. Can you display an image of a configured project, like the editorial calendar example?

**Comment by marcusolsson** [comment]
If you're doing something like an editorial calendar, and you have you content drafts in a folder for example, you can actually right-click that folder in the File explorer and choose "Create project from project".

By default, the plugin uses the front matter in each Markdown file (you can also use Dataview if you have it enabled). The plugin doesn't yet support creating new fields, only view and edit existing properties. For example, try creating a note that looks something like this inside your project folder.

```md
---
publish: false
due: 2022-10-30
status: Backlog
tags: [pkm, obsidian]
---

# My blog draft
```

**Comment by stoweboyd** [comment]
That helps
