### ISSUE TITLE
Priorities do not sort correctly

### ISSUE THREAD

**Issue by ScottKillen** [marcusolsson/obsidian-projects#590]
### What happened?

Notes with no priority sort before those with priority 1.

### What did you expect to happen?

Priority should obey a special sort order. In an ascending sort:

1. First priority (priority 1) tasks should come first.
1. Second priority (priority 2) tasks should come second.
1. Third priority (priority 3) tasks should come third.
1. etc.  
9. Followed by tasks with no priority and tasks with a priority of 0.

### How can we reproduce it (as minimally and precisely as possible)?

1. Remove the priority from a note.
2. Create other notes with various priorities.
3. Create an ascending sort rule for priority.
4. Note that tasks without priorities sort before those that have priorities.

### Plugin version

1.16.0

### Obsidian version

1.3.5

### OS

Windows

**Comment by ScottKillen** [comment]
An additional piece to this. If set the priority to `blank` within the project using the plugin's meta editor, the note's priority is set to '.nan' in the note's metadata.

Nevertheless, in my tests, this bug appears whether the note's priority is `blank`, '0', or '.nan'.

**Comment by ScottKillen** [comment]
If I create a task and give it no priority, it would be unprioritized. Likewise, 0 and .nan would also mean not prioritized.

As I mentioned, priority sort requires a special sort order. (see other plugins)

For this plugin, priority is no longer constrained by the plugin but is allowed to be a freeform field. This being the case, you now have many more use cases than before when the plugin controlled the field.

For instance, what if I use the following priorities:
- blank (none)
- D
- C
- B
- A

**Comment by axelson** [comment]
I think ideally there would be an option to control if no priority comes first or last (this is similar to what PostgreSQL offers, as well as https://linear.app)
