### ISSUE TITLE
UI/UX improvement - Table view - Add note button, create new note right away

### ISSUE THREAD

**Issue by PSFHU** [marcusolsson/obsidian-projects#592]
### What would you like to be added?

Even if one would be in would help a lot:
- Option to just use **Enter** if you want to create a new note in the **Add note** prompt
- Property toggle to Add note without prompt on Table views 
(_could be harder to implement_)

### Why is this needed?

While I'm in the planning phase of a project quickly trying to dot down the tasks on **Table view.**
I find the **Add note** UI flow quite frustrating with the prompt:

- Click **Add note**
  - **Name** property is good, probably want to change
  - **Project** propery is "redundant", you have to be on the view to press the button 
  _(There's are use cases however, where it's might be important: Project planning accross multiple project instances)_
- Click **Create note**

My biggest issue is the double click, if it would be possible to just hit **Enter** after clicking **Add note** that would speed up the process much more.

**Comment by marcusolsson** [comment]
Totally agree. The Add note modal was a way to centralize note-creation across all places were you can add notes.

Another limitation right now is that there's no way to rename a note from within Projects. If it was possible to rename, then we could just create a new note called something like "Untitled 2" (mirroring native Obsidian behavior).

If we introduced this without the ability to rename, I think it would lead to frustration.

Another option would be to add a temporary inline input field next to the Add note button for example.

**Comment by Acylation** [comment]
Enter to create note right away is supported now. Implemented by #624 and #642.
