### ISSUE TITLE
Feature request : ability to add links to open projects

### ISSUE THREAD

**Issue by brappier** [marcusolsson/obsidian-projects#597]
### What would you like to be added?

Say i want to add a link to a project. 
If i click on that link, it should open that project. 
That is what I want!

### Why is this needed?

very useful if you have 100s of projects

**Comment by marcusolsson** [comment]
Sounds like you want to link to a project from a note. I have a guide on how to do this here:

https://github.com/marcusolsson/obsidian-projects/discussions/377

**Comment by brappier** [comment]
Okay nice.
