### ISSUE TITLE
Can't change due: field

### ISSUE THREAD

**Issue by stoweboyd** [marcusolsson/obsidian-projects#60]
I try to edit the `due:` field in a project note, but it either reverts to the original value or jumps to some random date. I have to edit the `due:` date in the file.

**Comment by marcusolsson** [comment]
Since to be working for me. Maybe could you share some details on how I can reproduce this?

**Comment by stoweboyd** [comment]
I set a date in a projects file, called `project view`. I Use the 'yyyy-mm-dd' format.

![2022-10-17 project  view](https://user-images.githubusercontent.com/3037422/196167492-02942027-b8cf-442b-bc2b-fd542996300b.png)

Viewed in a table view, all looks right.

![2022-10-17 due date](https://user-images.githubusercontent.com/3037422/196167904-bf0554a6-6bde-4364-9ff0-faced2a5c81b.png)

I try to change the date. When I select, shows up in 'yyyy-dd-mm' format.

![2022-10-17 date selected](https://user-images.githubusercontent.com/3037422/196168167-8b086a4c-a090-461a-b99d-399cfda50866.png)

I select a new date.

![2022-10-17 select date](https://user-images.githubusercontent.com/3037422/196168310-ad4955dd-67f6-4ba9-a935-900af776ee02.png)

After selecting, though, the date reverts.

![2022-10-17 due date](https://user-images.githubusercontent.com/3037422/196168398-548d86c0-eae6-4bcd-a779-33a220fce7c4.png)

**Comment by marcusolsson** [comment]
Thanks for the examples! I'll try and reproduce with this.
