### ISSUE TITLE
Board View - can't open project note 

### ISSUE THREAD

**Issue by foegra** [marcusolsson/obsidian-projects#602]
### What would you like to be added?

Currently - when clicking on the note in "Boards" view - You are prompted to edit the note. What I'd like to - to open note itself in the same way as in the table view.

### Why is this needed?

It makes it much easier to navigate to the project note

**Comment by foegra** [comment]
It works. But would be nicer to click on the page to open - directly.

**Comment by DudeThatsErin** [comment]
Agreed. Clicking the link is unreliable for me. It usually just opens the frontmatter. I have to hold CTRL or CMD to open the note reliably.

**Comment by Tanjamuse** [comment]
Yes it would be really nice if it there was a setting to switch it around.

**Comment by marcusolsson** [comment]
> Yes it would be really nice if it there was a setting to switch it around.

Available under the plugin settings in the latest release.
