### ISSUE TITLE
Display all status options on kanban board with filters active

### ISSUE THREAD

**Issue by ThisIsKeb** [marcusolsson/obsidian-projects#605]
### What would you like to be added?

On the status view, it would be nice to be able to see all the available status options (for the status type you have selected) if you filter for specific metadata. 

Ex. 
You can see all the status columns here with no filter - I can freely drag and drop to different areas of the kanban:
![image](https://github.com/marcusolsson/obsidian-projects/assets/70029954/e09edc12-da43-4d0f-9bb7-0e72eebcea10)

Now I filtered for a specific set of notes in the projects, all of which are in "preprod", and since none of them have a different tag, only "preprod" is shown on the kanban. If all the other status' were available, I could drag and drop to the others quickly VS changing it manually, which is what you are able to do without the feature.
![image](https://github.com/marcusolsson/obsidian-projects/assets/70029954/53894aa2-c1f7-4505-b8c4-fc903d8af3c8)

### Why is this needed?

Quality of life improvement more than anything. Def not high priority as if you just remove the filter, you can then drag and drop to other status columns.

**Comment by luismercon** [comment]
This is something I also realized. Ideally I would like to create my flow on the board and see the columns even if there is no note with the status of a specific column.
