### ISSUE TITLE
Modifying `Settings > Dataview > Table Settings > Primary Column Name` leads to `Can't read the properties of undefined (reading 'path')` for all Dataview query projects

### ISSUE THREAD

**Issue by magma-chili** [marcusolsson/obsidian-projects#606]
### What happened?

The Projects plugin was throwing `Can't read the properties of undefined (reading 'path')` for Dataview queries after I modified `Settings > Dataview > Table Settings > Primary Column Name` within Dataview's settings.

### What did you expect to happen?

Work rather than bug-out.

### How can we reproduce it (as minimally and precisely as possible)?

Change `Settings > Dataview > Table Settings > Primary Column Name`  from 'File' (default) to something else.[](url)

### Anything else we need to know?

Somewhere in your code I'm guessing that `'File'` is hardcoded [somewhere](https://github.com/marcusolsson/obsidian-projects/blob/dcf94c7d4e7413b0ef4b7cc6d409469af1d43a9d/src/lib/datasources/dataview/datasource.ts#L120) and it should probably be set to this value instead: `app.plugins.getPlugin('dataview')?.settings.tableIdColumnName`

### Plugin version

1.16.0

### Obsidian version

1.3.5

### OS

Windows

**Comment by marcusolsson** [comment]
Oh! I didn't know that you could change the ID. I'll look into it!
