### ISSUE TITLE
a new note to a tag based project is not part of the project

### ISSUE THREAD

**Issue by ceciltech** [marcusolsson/obsidian-projects#607]
### What would you like to be added?

When adding a new note to a tag based project the note does not open for editing and because the new empty note does not have the project tag the new note will not show up in the project at all.  An option to allow opening a note created with the button in projects would be the simplest, automatically adding the projects tag to the front-matter would be ideal.

Work around:  Create a new set of templates for each project which includes the tag or use Templater plugin and have some sort of prompt for adding the tag  in every template.  Neither is ideal.

### Why is this needed?

Very frustrating to create a new note from within a tag based project and have nothing seem to happen and no way to easily access the new note from the current project.

**Comment by Acylation** [comment]
One more step to achieve this! I'm looking for a way to merge existing property tag values from the template with the newly assigned tag, rather than simply overwriting them.
