### ISSUE TITLE
[CSS BUG] Cells overlay the header when in table view

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#61]
![image](https://user-images.githubusercontent.com/13215013/196347949-b175d232-fe9f-4e58-a128-eb493fe759ad.png)

I found you added the z-index to css but it had been commented https://github.com/marcusolsson/obsidian-projects/blob/32e191e08f59c67c272e9a941ffde86b114eab4a/src/views/Table/components/DataGrid/GridCell/GridCell.svelte#L214

Do you have any other thoughts on this?

**Comment by marcusolsson** [comment]
Oh! Seems to only be the Switch control that has a weird z-index though. I'll look into this, thanks for reporting!
