### ISSUE TITLE
Feature Request: Add 'New Row' Button on Top of Databases in the Projects Plugin

### ISSUE THREAD

**Issue by sfdrada** [marcusolsson/obsidian-projects#613]
### What would you like to be added?

Description:
I would like to suggest a feature enhancement for the "Projects" plugin for Obsidian. The proposed feature would involve placing an 'Add New Row' button at the top of databases in the table view.

Currently, users need to navigate to the bottom of the database to add a new row. In cases where the database has a substantial number of entries, this can be quite time-consuming and interrupts the user's workflow. Having the option to quickly add a new row from the top of the database would streamline this process and save time.

Implementation:
This could be implemented as a button labeled 'Add New Row' or '+' located at the top of each database view. When clicked, a new row would be added at the top of the database, ready for the user to enter data. If necessary, this new feature could be made optional through a setting in the plugin's preferences, allowing users to toggle it on or off as needed.

### Why is this needed?

Benefits:
Adding this feature would make data entry more efficient and user-friendly, especially for users managing large databases. It would offer a faster, more accessible way to add new entries without needing to scroll to the bottom of the page, which can be particularly beneficial for large projects.

**Comment by Acylation** [comment]
The feature has been proposed and discussed in #408 . You can check the thread for more information. In brief, for a more friendly UX, we can stick the `Add note` button rather than scrolling. I'd also like to provide keyboard short cut for this.

I'll close this as duplicate, but feel free to continue communicate this on the previous thread, thx.
