### ISSUE TITLE
Unable to install plugin, throws 404 error presumably due to versioning issue

### ISSUE THREAD

**Issue by thattridentdude** [marcusolsson/obsidian-projects#619]
### What happened?

When trying to install plugin Obsidian notifies with "Failed to install plugin 'Projects'".   
Console shows that a `Request failed, status 404` error is thrown.  

Manually downloading and installing plugin works fine, with the caveat that Obsidian shows an update is available with version 1.16.1 despite most recent version on the repo being 1.16.0, as shown below. Attempt to update result in the same 404 error.
![CleanShot 2023-07-17 at 15 44 32](https://github.com/marcusolsson/obsidian-projects/assets/5077094/67cf8fdf-4f2a-454f-a17c-493b9bbff071)

This suggests that Obsidian is looking for a version that doesn't exist, leading to the installation failure.

### What did you expect to happen?

For the plugin to be installed/updated

### How can we reproduce it (as minimally and precisely as possible)?

Steps to reproduce: 

1. Open Obsidian
2. Ensure the Projects plugin isn't installed
3. Open Settings
4. Click on Community Plugins
5. Disable Restricted Mode
6. Search for the Projects plugin
7. Click on Install

### Anything else we need to know?

Edited to add:
Seems caused by the version bump in the manifest from #617. Is this simply a matter of unfortunate timing on my part combined with a new release that's about to be released?

### Plugin version

1.16.1

### Obsidian version

1.3.5

### OS

macOS

**Comment by marcusolsson** [comment]
Thanks for reporting, I'm releasing right now and have yet to tag the release 😅

**Comment by thattridentdude** [comment]
Haha, bad timing on my part it seems. I’ll close the issue.
