### ISSUE TITLE
Feature Request - Define width of kanban columns

### ISSUE THREAD

**Issue by jebeaudoin** [marcusolsson/obsidian-projects#63]
Really like this project! A couple of usability suggestions, if it's OK to suggest...

1. My columns on the kanban board are 2x wider than I'd like. I wish there were a way to define the default size in the settings.
2. Is there a way to define the order of the columns? Right now, they are out of order for my workflow :)
3. Finally, I'd like the option of hiding a column (especially when there's no value for the field)

Thanks!
JB

**Comment by marcusolsson** [comment]
Thank you! 🙏 

1. Can definitely add this!
2. Not right now, I've been meaning to figure out how to implement drag and drop, and have been pushing this until then. I could potentially also make this configurable through other means until drag and drop happens.
3. Sounds like your use case is hiding empty columns rather than manually hiding them? Is that correct?

**Comment by jebeaudoin** [comment]
On point 3, it’s more an intuition than use case. screen real estate is precious, so anything (like an empty column) that occupies space without relaying information is frustrating. I suppose manually hiding may be more universally helpful than auto hiding.

Thanks again for this great work!

**Comment by benhamilton** [comment]
This would be very useful! 
Regarding hiding empty columns, I've seen some Kanban boards where empty columns are auto collapsed, thus they stay in correct order, but only take up a fraction of a full width column. This would be my personal preference as it makes it clear that there is a status/column, where it sits, and that there are currently no cards in that column.

**Comment by marcusolsson** [comment]
I've added a setting in 0.19.2 for adjusting the column width.

![CleanShot 2022-10-25 at 13 05 16@2x](https://user-images.githubusercontent.com/8396880/197757223-4dc15ec6-82e6-4026-8898-0512d234b78c.png)

Let's continue the discussion on auto-collapsing columns in #68 and column ordering in #2.
