### ISSUE TITLE
[Bug] If attachment file name has special characters i.e. ö,ä,ü, & etc. it will not display

### ISSUE THREAD

**Issue by zenminimalist** [marcusolsson/obsidian-projects#643]
### What happened?

If the attachment in a note e.g. book cover file name contains characters such as `&`, `ä`, `ö`, `ü`,`.`,  etc. it will not be displayed in the cover view. Obsidian itself does not have this problem showing the attachments that have these characters in them. 

### What did you expect to happen?

For them to be display anyway, just as Obsidian does.

### How can we reproduce it (as minimally and precisely as possible)?

Take an attachment and add i.e. `ö` in the file name and watch it **not** be displayed in the cover view.

### Plugin version

1.16.3

### Obsidian version

1.3.5

### OS

macOS

**Comment by Acylation** [comment]
The characters work fine within my vault, and I'm testing it on a windows laptop. Did I miss anything or this is a system related problem?
