### ISSUE TITLE
A option to deleted files

### ISSUE THREAD

**Issue by VenomRaiden** [marcusolsson/obsidian-projects#649]
### What would you like to be added?

A option in the projects view to delete files adding in it

### Why is this needed?

So that you dont have to open a file to delete it out of the project view

**Comment by Acylation** [comment]
Now in table view, you can delete an item by right clicking at the row header, calling out the menu.
<img width="347" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/73122375/d656f472-e8d3-4c4f-8018-5c11fd469259">

**Comment by VenomRaiden** [comment]
oh... thanks for the help. I didnt know it existed
