### ISSUE TITLE
Cannot create list independent of notes

### ISSUE THREAD

**Issue by GeneralKugelBlitz** [marcusolsson/obsidian-projects#653]
### What happened?

If a list of cards in the board is empty it vanishes, I have to keep placeholder notes just to keep a list.

### What did you expect to happen?

That I can create a list independent of if there is a note or not, basically for every project while making it we can choose the board status fields and they remain there as lists and we can choose among them in Yaml of the notes themselves

### How can we reproduce it (as minimally and precisely as possible)?

just make a list empty and it will vanish

### Plugin version

1.16.3

### Obsidian version

1.3.7

### OS

Windows

**Comment by Acylation** [comment]
Discussed in #605 , and I'd like to work on a fix recently.

**Comment by ltroj** [comment]
@Acylation Not sure if I'm missing the point here but - we can already have this behavior by simply switching to Table > column (e.g. "status") > Configure field > Options.

You can define all the statuses (or whichever columns you want to show in your board) you need there and they will stay in the board view even if the columns are empty.

This setting should be accessible from the boards view, though, it's hard to find rn.

**Comment by scottbolte** [comment]
Is there a collection of **How Tos** for the **Projects** plugin? I was going make a feature request for persistent Kanban columns and happened to find this request first. The suggestion by @ltroj is what I needed (thank you!), but fishing through the issues list is cumbersome. 

For example, this is the note I created for myself:

--- 

## Kanban Status Fields
The panels on the Kanban board will come and go if there are no projects in a given state (e.g., *Active*). To retain the panels at all time, and make it easier to drag a note into an empty state, configure the field to have a fixed set of options.

1. Open **Obsidian** in the vault of interest.
2. Open the **Projects** plugin's tab.
3. Select the project of interest at the **Table** view.
<img width="538" alt="Pasted image 20240331083805" src="https://github.com/marcusolsson/obsidian-projects/assets/10702040/cc0c5c9a-764d-48cf-acbd-3e35bfd8983e">

4. Scroll over to the **status** column and press the `...` button to click on **Configure field**
<img width="323" alt="Pasted image 20240331083943" src="https://github.com/marcusolsson/obsidian-projects/assets/10702040/0604c3a0-1a6a-42d3-81a6-bd7de24edcb7">

5. Add all available status values.
<img width="572" alt="Pasted image 20240331084123" src="https://github.com/marcusolsson/obsidian-projects/assets/10702040/ed52e505-ee72-4449-a85c-6e68026c42c2">
