### ISSUE TITLE
Add functionality to exclude folders

### ISSUE THREAD

**Issue by mtiowl** [marcusolsson/obsidian-projects#655]
### What would you like to be added?

I would like to be able to exclude specific subfolders.  Not just list files.  Maybe allow us to exclude all files in a sub folder by using \*.\*    Example for exclude:  /Projects/Archive/\*.\*

### Why is this needed?

Since we cannot edit when using Dataview, I would like a way to exclude certain sub-folders.  Example setup:  I have a Projects folder with sub-folders to group my projects:

Projects
- Archive
- Home Projects
- Work Projects

I would like to exclude all files in the Archive since these are all completed, canceled, abandoned, etc.

**Comment by Acylation** [comment]
The option to include or exclude subfolders is available in folder datasource projects. Am I correct in understanding that your request is for dataview datasource projects?

**Comment by mtiowl** [comment]
> The option to include or exclude subfolders is available in folder datasource projects. Am I correct in understanding that your request is for dataview datasource projects?

**Comment by Acylation** [comment]
Sorry for misunderstanding of your request. Exclude a specific folder is not yet supported but it has been raised in issue #501 , marking this as a duplicate and you can check the progress there. I will catch up with the backlogs but it would take some time.
