### ISSUE TITLE
OR on Filtered views

### ISSUE THREAD

**Issue by aubreyz** [marcusolsson/obsidian-projects#656]
### What would you like to be added?

This is a stupendous plugin - thank you!
Hope I'm not being dense or missing an open issue, but OR filtering would I think be important in the views. 

I appreciate it's hard to have complex filtering combinations especially in a GUI (the GUI aspect is important I think for this plugin), but at the very least I think a choice between all ANDs or all ORs in the filter stack would cover 90% of use cases. 

### Why is this needed?

At the moment I have multiple different YAML fields with attention flags of different sorts and it would be good to be able to show all stuff that requires attention without 6 views for each type of attention.

**Comment by imeed166** [comment]
Check #279

**Comment by Acylation** [comment]
Closing as duplicate. Thanks for helping triaging this @imeed166
