### ISSUE TITLE
Open/Edit a card

### ISSUE THREAD

**Issue by icebruce** [marcusolsson/obsidian-projects#657]
### What would you like to be added?

While in Gallery view, I am not able to open the note/card on click unless I include the "name" field, press ctrl button and click on the file link.

I think it would be more intuitive to directly open the note by clicking on the file link as this is the general behaviour across obsidian. As for the edit functionality it could be achieved via a right click or maybe a pencil button when covering ovr a card

### Why is this needed?

Make the UI/UX more streamlined and easier to navigate
![image](https://github.com/marcusolsson/obsidian-projects/assets/66655064/5c272252-ed41-4193-a57a-85056a4d2711)

**Comment by Acylation** [comment]
In the plugin’s settings tab, there is an option to select the default behavior when clicking on a link. You can choose between opening a note or opening the edit modal. With the `Ctrl` key it is expected to perform the opposite. So if the file can't be opened by either clicking or `Ctrl` + clicking on the link, it's possibly a bug. Though I can't reproduce this, please let me know if the problem persists after following the aforementioned instructions.

I agree that having a floating Edit button is a good way to interact. However, to keep the consistency between different views, we should provide an equivalent user experience. This would require a major refactor.

**Comment by icebruce** [comment]
I didn't realize there was an option in the settings. That solves the issue then, thanks!
