### ISSUE TITLE
Latex in YAML

### ISSUE THREAD

**Issue by shimu527** [marcusolsson/obsidian-projects#66]
Can the latex be supported in yaml, e.g. `the function formula is $x^2$`

**Comment by marcusolsson** [comment]
Hey and thanks for the suggesiton! Would you be able to provide an example of a note that would use it?

**Comment by shimu527** [comment]
like this
![image](https://user-images.githubusercontent.com/81798750/198813043-aa6b07c6-d61b-4ca0-b717-59d795c60e6b.png)
![image](https://user-images.githubusercontent.com/81798750/198813051-f3926a57-d637-4a6d-998e-162ef92a4fac.png)

**Comment by shimu527** [comment]
and whether or not there is a chance of a line feed implemented by `\n`。
Sorry for taking so long to reply, but it would be great if we could support such a feature!
