### ISSUE TITLE
Date edit field icon overlapping date input

### ISSUE THREAD

**Issue by viniciusdel** [marcusolsson/obsidian-projects#667]
### What happened?

I noticed that when **editing a project**, the if one of your note properties is a date field, the field to edit that has an icon that overlaps the input field:
![image](https://github.com/marcusolsson/obsidian-projects/assets/19553214/604916d2-b4e4-4486-b178-be1afae9eebd)

I'm guessing it just needs a bit of extra padding on the left, but wanted to report it either way :).
I tried changing the zoom and font size of my Obsidian, but the issue persisted.

### What did you expect to happen?

I expected the icon and the input fields to be a little more far apart so I could see what I was typing.

### How can we reproduce it (as minimally and precisely as possible)?

Create a project that has a date field as a property.

Open it in the edit view and see if the icon is overlapping the input field.

### Plugin version

1.16.3

### Obsidian version

1.4.5

### OS

Windows

**Comment by Acylation** [comment]
Yeah this is reproduciable, thanks for the report! The overlapping problem only seems to have occured recently if I remember correctly. Not sure if this is related to the new version of the plugin or the v1.4.x updates of Obsidian main application. I'll look into this.

**Comment by viniciusdel** [comment]
> Yeah this is reproduciable, thanks for the report! The overlapping problem only seems to have occured recently if I remember correctly. Not sure if this is related to the new version of the plugin or the v1.4.x updates of Obsidian main application. I'll look into this.

Thank you so much! I just started using it and I am excited to learn it :D

**Comment by Acylation** [comment]
Closed as completed by https://github.com/marcusolsson/obsidian-svelte/pull/2
