### ISSUE TITLE
Would be very helpful if tables and galleries can be filtered by lists

### ISSUE THREAD

**Issue by Zachary0116** [marcusolsson/obsidian-projects#669]
### What would you like to be added?

<img width="572" alt="Screenshot 2023-09-06 at 17 04 55" src="https://github.com/marcusolsson/obsidian-projects/assets/139985852/2e1f8837-0fda-40b0-9581-3b8ade4e35f9">

### Why is this needed?

Tables/galleries cannot be filtered by lists currently - only 'is empty/not empty' rather than the specific tag (e.g. A).

**Comment by Acylation** [comment]
Prefer #447 and mark this a duplicate and you can check the progress there. Thx!
