### ISSUE TITLE
Split current projects view cause obsidian to stop working

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#67]
# How to reproduce

1. Open Projects View
2. Right Click on the tab header or use hotkey to split current view.
3. See error.

# Related

#39 

I found that this is related to how to create multi app instances with svelte, so maybe we need some code to control every app instances life cycle or ?

And I also tried to register a codeblock last night :

```typescript
this.registerMarkdownCodeBlockProcessor('projects', async (source: string, el: HTMLElement, ctx) => {
			let error = null;

			const optionsMatch = parseYaml(source);
			let project;
			console.log(optionsMatch);
			if (optionsMatch !== null) {
				try {
					project = optionsMatch["project"];
				} catch (e) {
					console.error(e);
					error = `<strong>Failed to parse project options</strong>\n\t${e}`;
				}
			}

                        // the app is same as what we get from new app instances in a view
			const app = new CodeBlockApp({
				target: el,
				props: {
					codeBlockProject: project
				}
			})

			this.codeblockSet.add(app);

			if (error !== null) {
				const errorNode = document.createElement('div');
				errorNode.innerHTML = error;
				errorNode.addClass("obsidian-plugin-project-error");
				el.appendChild(errorNode);
			}
		});
```

So do you have any idea about how to create multi app instances ?

**Comment by marcusolsson** [comment]
What version and OS are you running? Seems to be working on 0.19.3 (macOS):

![CleanShot 2022-10-26 at 17 17 02](https://user-images.githubusercontent.com/8396880/198066597-714e591e-347a-4f5b-896e-0db0fd5a7715.gif)

**Comment by Quorafind** [comment]
@marcusolsson it is not reproducable in 0.20.0, so I decide to close this issue unless I found a way to repro it.
