### ISSUE TITLE
Sorting by a date puts the projects at the bottom of the table

### ISSUE THREAD

**Issue by MavropaliasG** [marcusolsson/obsidian-projects#682]
### What happened?

When I sort by a date, when I put the date Old -> New, it puts the sorted items at the bottom

![image](https://github.com/marcusolsson/obsidian-projects/assets/13523909/e28d0360-c529-45e5-8ab4-4706ad665abd)

Whereas when I sort by New -> Old it puts the sorted items at the top

![image](https://github.com/marcusolsson/obsidian-projects/assets/13523909/0524bd0a-593f-4983-a2f1-b11b9e3a9533)

### What did you expect to happen?

Display items with a deadline at the top, then sort them based on preferred order. What I would ultimately like as this is a deadline date, is for the first row to show me the closest deadline and the last row (for the items that contain a value in this column) to show me the furthest deadline. So ultimately from the screenshots, first row should have 16/09/2023 and row 6 to have 15/11/2023. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a deadline filed with a date in your projects, then sort them trying to get the closest deadline at the top

### Plugin version

1.16.5

### Obsidian version

1.4.13

### OS

Linux

**Comment by Acylation** [comment]
This is similar to #590 , requiring to exclude undefined values when sorting.
