### ISSUE TITLE
MultiValue YAML (property) Doenst support for filter

### ISSUE THREAD

**Issue by GoosheBaaz** [marcusolsson/obsidian-projects#683]
### What would you like to be added?

I want to have access to filter  Properties in frontmatters (YAMLs) with multiple values in "projects plugin" , but your Awsome plugin doesnt support this.

I uploaded a video explaining What I exactly mean in more detail (enable the audio for the video)
https://github.com/marcusolsson/obsidian-projects/assets/141968929/f155c7c5-b479-4463-90e0-9b4defd1dc70

### Why is this needed?

very crusial in other softwares like notion and also I think the "dataview" plugin also support this
it makes my work and I think lots of other people much easier and more flexible

**Comment by Acylation** [comment]
Prefer #447 , and this is priorized since it's a really useful feature. Please track the progress there, thanks!
