### ISSUE TITLE
Untitled Note 1 not selected for easy replacing.

### ISSUE THREAD

**Issue by ceciltech** [marcusolsson/obsidian-projects#684]
### What would you like to be added?

When creating new note the default name "Untitled note 1" is not preselected.  I would like the default title to be pre-selected.

### Why is this needed?

In order to add a new note and name it I have to hit the backspace key 16 times or reach for my mouse to give the note a new name that does not start with 'Untitled note 1".  The quality of life points for this minor enhancement are high!

**Comment by Acylation** [comment]
This would be a great enhancement on note creation. Btw the pending PR #642 is also related to new note modal, improving `enter` key confirmation. Your suggestion could be integrated in conjunction with this.
