### ISSUE TITLE
Support adding new fields in the project page

### ISSUE THREAD

**Issue by YousufSSyed** [marcusolsson/obsidian-projects#692]
### What would you like to be added?

I'd like a button and keyboard shortcut to press to add new fields right in the project page, and then edit them for individual pages to add them as properties.

### Why is this needed?

It would be more convenient than going to a page and adding the property there and going back to the project page.

**Comment by Acylation** [comment]
Will be worked on in the next iteration, release within two minor versions.

**Comment by Li-Mingshuang** [comment]
Support, it's important to add information in the table window directly.

**Comment by Acylation** [comment]
Mark as completed based on adding field in table view is supported. Will explore more solutions like control panel etc.
