### ISSUE TITLE
tags filter error

### ISSUE THREAD

**Issue by 273032860** [marcusolsson/obsidian-projects#707]
### What happened?

tag:
   - 111
   - 222

only show “is empty” and "is not empty"

### What did you expect to happen?

show all

### How can we reproduce it (as minimally and precisely as possible)?

yaml 
tag:
   - 111
   - 222
----------------------------------
-space 111
-space 222

### Plugin version

1.16.5

### Obsidian version

1.4.46

### OS

macOS

**Comment by Acylation** [comment]
Filter for tags is in active development and you can check the progress in #686 . The proposed filters would be `has any of`, `has all of` and `has none of`.

I'm closing this as a duplication of #447. However, feel free to report if I didn't get you correctly.
