### ISSUE TITLE
gallery view

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#72]
I'd like to suggest the gallery view if it's in the scope of the plugin
https://www.notion.so/help/galleries 
https://support.airtable.com/docs/guide-to-gallery-view

**Comment by marcusolsson** [comment]
Should be able to make an initial version rather easily 👍

**Comment by marcusolsson** [comment]
Available in 0.20.0. It's rather minimal right now, but feel free to open another issue if you have specific feature requests.

**Comment by imeed166** [comment]
What syntax is recognized in the image property to display them in the gallery view ? I tried `![[image.jpeg]]` and `[[image.jpeg]]` and the original link `https://unsplash.com/...` but it didn't display anything when I choose `image` in the cover setting.

**Comment by marcusolsson** [comment]
Just the link URL without the brackets should work. Only internal links work in this version.

**Comment by imeed166** [comment]
I see, the file path also works. Thank you.

**Comment by marcusolsson** [comment]
Added support for https:// links in 0.20.1.

**Comment by nkkn1008** [comment]
@marcusolsson This is awesome plugin!

@imeed166 Could you please share the YFM showing the recognized file paths?

**Comment by imeed166** [comment]
Just go to the image file and use the `copy file path` command. @nkkn1008

**Comment by nkkn1008** [comment]
@imeed166 Thank you for your comment, but not rendered.
I wrote YFM as below. Do you know what's the mistake?
```
---
due: 2022-11-09
status: done
finished: false
image: ProjectTestFolder/2021-06-30_15h21_04.png
---
```

**Comment by imeed166** [comment]
Maybe it's the image type, try with `.jpg`

**Comment by nkkn1008** [comment]
@imeed166 
Thanks for the quick reply, I tried jpg but no gallery.

**Comment by nkkn1008** [comment]
![image](https://user-images.githubusercontent.com/3515425/199746189-52caad0c-e20e-4fea-b00d-923ac2b2d402.png)

**Comment by nkkn1008** [comment]
That is exactly what happened!
Selecting Cover field to `image` leads to gallery view!!
