### ISSUE TITLE
Support url in gallery view

### ISSUE THREAD

**Issue by Quorafind** [marcusolsson/obsidian-projects#73]
Now we get image in vault works correctly when using gallery view. Could we have the img url support?

**Comment by marcusolsson** [comment]
Could you give me an example of a URL you'd like to use as the cover?

**Comment by Quorafind** [comment]
For example: `https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1599649084i/30753841.jpg`  .Most of those image url has `png\svg\jpg\jpeg` as extension.

And random image link from a famous image site: 
- `https://source.unsplash.com/random`

**Comment by Quorafind** [comment]
And at the same time, if we could just detect if a url is vaild or not, maybe this would make this feature most customizable ?

**Comment by marcusolsson** [comment]
Released 0.20.1 with support for remote images (http(s)). Right now, I'm only checking whether text starts with `https://` or whether Obsidian can resolve it to an image file inside the vault.
