### ISSUE TITLE
Latest release cannot be downloaded via Brat

### ISSUE THREAD

**Issue by danieltomasz** [marcusolsson/obsidian-projects#75]
When trying to update via Brat the there is an info that release cannot be downloaded (main.js is missing according to BRAT, with release 20.1)

**Comment by marcusolsson** [comment]
Thanks for the heads-up! I'll look into it when I'm back at the keyboard!

**Comment by danieltomasz** [comment]
BTW Manually downloading and loading the plugin from the zip attached to the release is working, so I am not sure what is the cause

**Comment by danieltomasz** [comment]
Ok, my old  experiences with creating plugins and sharing it via brat suggest that the main.js need to be  included in the root folder in the repo (but I am not 100% sure)

**Comment by marcusolsson** [comment]
Tried installing 0.20.0 which worked, but 0.20.1 does not. So weird. The release build went well and I see no obvious changes that could've impacted this. I'll try publishing another release to see if it was a flake.

**Comment by marcusolsson** [comment]
Could you try updating to the latest (0.20.3)?
