### ISSUE TITLE
Date & Time Property Calendar View

### ISSUE THREAD

**Issue by optechadam** [marcusolsson/obsidian-projects#750]
### What would you like to be added?

The current calendar view only handles the Date metadata type. Can this be modified to either:
1. Sort daily by a Time metadata type so that items appear in time blocks on the calendar
2. Use a Date & time type within the calendar view to sort items by day and time.
Dragging items within a day should update their times similar to how dragging items from day to day updates their date.

### Why is this needed?

There is currently no way to sort items on the calendar if there are multiple items in a day. This would allow an Outlook calendar like functionality

**Comment by Acylation** [comment]
Thanks for proposing this! Will be worked on within this month. Related to #390
