### ISSUE TITLE
FR - Add Note Preloads front-matter according to active view filters.

### ISSUE THREAD

**Issue by davidlaym** [marcusolsson/obsidian-projects#751]
### What would you like to be added?

For determinate filters like "field" is "value" I think is expected that if I create a Note from the project, It pre-loads those filtered values into the note front-matter, after the template was applied, the same way it currently includes the field corresponding to the lane it was created at.

### Why is this needed?

This will allow to display the new note in the context for when it was added independent of view filters.

**Comment by Acylation** [comment]
Closes as duplicate and in favor of #596. Thanks for proposing!
