### ISSUE TITLE
Table view: Render internal links in list fields

### ISSUE THREAD

**Issue by DragNet2** [marcusolsson/obsidian-projects#756]
### What would you like to be added?

I use properties for various tasks and sometimes I need to specify links right inside the properties (e.g. links to the contacts). Therefore I would like to see the links rendered in the Project's table view properly.

![CleanShot 2023-12-16 at 20 00 45](https://github.com/marcusolsson/obsidian-projects/assets/41149801/23aeee37-9aaf-4c06-81cb-a5f18e44271c)

![CleanShot 2023-12-16 at 20 04 39](https://github.com/marcusolsson/obsidian-projects/assets/41149801/f5649c18-65b3-47fd-b282-c42be7b3b332)

### Why is this needed?

I would like to have access to the linked objects right from the table view.

**Comment by Acylation** [comment]
Thanks for sharing your use case. Internal links are supported in `text` fields, if you enable the richtext formatting via the column setting in the table view. From your screenshot, it seems you're requesting that, internal links in list items should also be rendered. I will rename the issue title and this may need some design.

**Comment by yodaliu0414** [comment]
> Thanks for sharing your use case. Internal links are supported in `text` fields, if you enable the richtext formatting via the column setting in the table view. From your screenshot, it seems you're requesting that, internal links in list items should also be rendered. I will rename the issue title and this may need some design.

Hi, I met the same problem. And there isn't an option to enable the richtext formatting in column setting for those columns read from "list items" type in page properties (or metadata). Look forwards to the improvement. Thank you!

**Comment by Acylation** [comment]
This will be available in the upcoming version in a few days. Thanks for the suggestion, following up and all your engagements!
