### ISSUE TITLE
Table view names gets reset to default name "Table" when adding fields to table after changing the view name

### ISSUE THREAD

**Issue by mippzon** [marcusolsson/obsidian-projects#757]
### What happened?

The table view name gets reset to the default name "Table" when adding new fields after changing the table view name.

### What did you expect to happen?

The view name should be persisted even though other changes, such as adding fields, are performed.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a project based on Folder
2. Open the project in Project view (Table)
3. Add a new note
4. Change the view name to something else than "Table"
5. Add a field
6. Check the view name which now have returned to the default name "Table".

### Plugin version

1.17.1

### Obsidian version

1.5.2

### OS

Windows

**Comment by Acylation** [comment]
Thanks for the report! As the new field creation is coupled with previous apis in an ugly way, some features are affected and some dirty values will return after the new field creation. I've recorded a similar problem in #733. There will definitely be a fix but it  will take some time.

A temporary workaround is, you can close the Projects tab after renaming a field, then reopen and create a new one. Then your rename will persists.
