### ISSUE TITLE
Add the possibility to group by in different views

### ISSUE THREAD

**Issue by mippzon** [marcusolsson/obsidian-projects#758]
### What would you like to be added?

I would like to have a "group by" feature in the table view (and maybe also the other views if applicable) similar to what Notion and other tools do. 

Example:

I have a list of servers. Each server has several properties and belongs to different systems. Then it would be nice, in a table view, to group by system so that I still can see all my servers, but get some kind of overview as they are grouped. 

### Why is this needed?

I guess this can already be accomplished by combining filters and views, i.e. creating a new view for each "group by" and filtering each view on something. But the problem is then that you cannot see all the data in the same view as you would with a group by function.

**Comment by Acylation** [comment]
The design is discussed together with a "Meta view" feature in #140 and here's marcu's reply https://github.com/marcusolsson/obsidian-projects/issues/140#issuecomment-1829813470

Let's track the design there!
