### ISSUE TITLE
[Feature Request] Gantt-style horizontal planning calendar

### ISSUE THREAD

**Issue by jreus** [marcusolsson/obsidian-projects#777]
### What would you like to be added?

I would love to see Projects include a Gantt-style horizontal calendar view, showing tasks and notes within a project displayed according to `start-date` and `due-date` parameters ( these already exist in Tasks, and can easily be added to note metadata ).

The horizontal calendar view should allow you to get a total overview of the timeline of your projects, allowing you to set the begin date and end date of the view. It should also include filters allowing you to show or hide certain tasks/notes by status, or by a subtask they might belong to.

### Why is this needed?

I work freelance, and every project I do is different ... with many different phases and sub-tasks happening at different times over the course of many months. A horizontal calendar frees you from the limited overview provided by the monthly calendar view, and lets you manage tasks within the whole timeline of your project.

Obsidian is really lacking anything like this. The only option I've found at this point is using mermaid to cobble together gantt chart overviews ... which is very difficult, error prone, and missing the valuable integration such an overview would have if included in the Projects suite of views.

**Comment by ltroj** [comment]
https://github.com/marcusolsson/obsidian-projects/issues/6

**Comment by Acylation** [comment]
Thank you @ltroj and @jreus thanks for the post. Close this in favor of #6
