### ISSUE TITLE
Buttons "Filter", "Sort" etc. don't work when the tab is opened in a new window.

### ISSUE THREAD

**Issue by Vulpes4** [marcusolsson/obsidian-projects#784]
### What happened?

When project tab is moved to a new window the buttons like filter, sort, color etc. don't work. The project tab works normal. They open under the actual window.
![obraz](https://github.com/marcusolsson/obsidian-projects/assets/46760675/2fcd43c8-e515-4eb0-8913-0d5a26029b2a)
![obraz](https://github.com/marcusolsson/obsidian-projects/assets/46760675/331764ee-8825-4fad-86a3-b1ba969b0ddb)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

- Open projects
- Right click on the tab,
- Choose move to new window
- Try to use the "Color", "Filter" and "Sort" buttons
- After clicking on the button above click alt+tab and navigate to the main obsidian window. You will see the Color/Filter/Sort menu.

### Anything else we need to know?

.

### Plugin version

1.17.1

### Obsidian version

1.5.3

### OS

Windows

**Comment by Acylation** [comment]
Reference: https://obsidian.md/blog/how-to-update-plugins-to-support-pop-out-windows/
