### ISSUE TITLE
Images Dropped From Kanban

### ISSUE THREAD

**Issue by ReessKennedy** [marcusolsson/obsidian-projects#797]
### What happened?

I had a cool visual Kanban up by just inserting markdown image links inside a frontmatter field but and it was fine for weeks and then I think I updated and it stopped working? 
<img width="396" alt="Screen Shot 2024-02-22 at 6 32 58 PM" src="https://github.com/marcusolsson/obsidian-projects/assets/3970267/496d8d0a-12c9-4240-8566-5454e1341adf">

### What did you expect to happen?

Would like to be able to see images in Kanban. 

### How can we reproduce it (as minimally and precisely as possible)?

Try to add an image links to a field like:
```
 ![Raspberry Pi 3 Model A+ Plus Pi 3A+ - Picture 1 of 2](https://i.ebayimg.com/images/g/IPEAAOSwP9lkn6IJ/s-l1600.jpg)
```
 ... it used to show up in Kanban and now it does not. 

### Plugin version

1.17.1

### Obsidian version

1.5.3

### OS

macOS

**Comment by Acylation** [comment]
Please check the corresponding field settings from the `Table view -> column three dot drop-down -> configure field`, and make sure the `richtext` is enabled. This feature seems still active for me. Not sure why it occurs after update.

Much appreciate for your feedback. Follow-up if the problem persists and I will do more investigation.

**Comment by ReessKennedy** [comment]
@Acylation .. this worked! Thank you! I was confused.

**Comment by Acylation** [comment]
Yeah glad to know that.

Safely close this as completed.

**Comment by niudungh** [comment]
Plugin version
1.17.4

Obsidian version
1.8.7

os
macOS


“Please check the corresponding field settings from the Table view -> column three dot drop-down -> configure field”

Excuse me, where can I find it? I didn't see it on the interface.
