### ISSUE TITLE
File cannot be sorted correctly

### ISSUE THREAD

**Issue by wwjCMP** [marcusolsson/obsidian-projects#820]
### What happened?

![Snipaste_2024-03-24_14-07-29](https://github.com/marcusolsson/obsidian-projects/assets/32979859/0ff347ac-3a8e-40cb-9bd9-14ad22eb5934)
![image](https://github.com/marcusolsson/obsidian-projects/assets/32979859/a0432e30-75f9-49af-9140-775674102826)

### What did you expect to happen?

Sort alphabetically.

### How can we reproduce it (as minimally and precisely as possible)?

All that is needed is to create the corresponding files.

### Plugin version

1.17.2

### Obsidian version

1.5.11

### OS

Windows

**Comment by Acylation** [comment]
Sorry but I can't reproduce this. Could you please try toggling on / off the sorting condition several times to see if it works correctly?

**Comment by wwjCMP** [comment]
> Sorry but I can't reproduce this. Could you please try toggling on / off the sorting condition several times to see if it works correctly?

I use tags to build my project, is it related to this?

**Comment by Acylation** [comment]
Are your notes stored in different folders? I have located this problem and could you please confirm that, if the shown order in the screenshot actually based on `path` field rather than `name` field? Will give this a fix in recent days.

![image](https://github.com/marcusolsson/obsidian-projects/assets/73122375/cc42bea6-94f5-4c30-b9c5-dd76aa1f82a6)

**Comment by wwjCMP** [comment]
> Are your notes stored in different folders? I have located this problem and could you please confirm that, if the shown order in the screenshot actually based on `path` field rather than `name` field? Will give this a fix in recent days.
> 
> ![image](https://private-user-images.githubusercontent.com/73122375/316314848-cc42bea6-94f5-4c30-b9c5-dd76aa1f82a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTI0MTYsIm5iZiI6MTcxMTI5MjExNiwicGF0aCI6Ii83MzEyMjM3NS8zMTYzMTQ4NDgtY2M0MmJlYTYtOTRmNS00YzMwLWI5YzUtZGQ3NmFhMWY4MmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0NTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZjgwYTE0NTkyMzQ4YTlkOTVmODJhMTA1ZTYzYmQ3YThlODk3MDNiNjIyZWQ0MjA5YWU4NWI2MDAwZDBmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kaTPi7om3bE_JZtgoNstSaN8AjHFS0WPxCjzvGEOtJ0)
> 
> This may also affect nested folder project users. Will build tests for these problems.

Yes, my files are placed in different paths.

**Comment by Acylation** [comment]
Hi! Along with the release 1.17.3 this problem should be resolved. Please upgrade and see if it works corretly. Thanks again for reporting!

![image](https://github.com/marcusolsson/obsidian-projects/assets/73122375/2c2955ec-f302-4389-a738-6089f520183e)
