### ISSUE TITLE
[BUG] With Console open I get an error "DevTools failed to load source map: Could not load content for app://obsidian.md/styles.css.map: System error: net::ERR_FILE_NOT_FOUND"

### ISSUE THREAD

**Issue by GH4TP** [marcusolsson/obsidian-projects#833]
### What happened?

When enabling Projects with Console open the following error is generated "DevTools failed to load source map: Could not load content for app://obsidian.md/styles.css.map: System error: net::ERR_FILE_NOT_FOUND"

### What did you expect to happen?

Loaded message without error

### How can we reproduce it (as minimally and precisely as possible)?

Disable and Enable plugin with Console open

### Plugin version

1.17.2

### Obsidian version

1.5.12

### OS

Windows

**Comment by Acylation** [comment]
Close as duplication of #773. Thanks for reporting as I can't stablely reproduce this, and you've provided an evidence that this is not a platform related problem. Will look into this when I next have time.
