### ISSUE TITLE
When creating different views, it would be nice to copy colors and filters from other views within the same project

### ISSUE THREAD

**Issue by mayersj1** [marcusolsson/obsidian-projects#837]
### What would you like to be added?

Right now, I've populated my Table view with many color rules and filter options.  When I create a Board or Calendar view, I have to recreate all those color and filter rules. I would like to have the option to use shared color rulesets (and filter rulesets) across all views within the project

### Why is this needed?

Saved rulesets are the backbone of data visualization. Having to recreate them each time is painful and time consuming.

**Comment by Acylation** [comment]
Prefer issue #779 and close this as duplicate.
