### ISSUE TITLE
Understand Dataview-like `::` syntax?

### ISSUE THREAD

**Issue by fzyzcjy** [marcusolsson/obsidian-projects#843]
### What would you like to be added?

Hi thanks for the plugin! However, some of my fields are not yaml frontmatter, but dataview's `::` syntax. For example, `summary:: Hello world`. It would be great if this project could support it.

### Why is this needed?

Because dataview's syntax is widely used, and it is quite convenient sometimes (e.g. support

**Comment by Acylation** [comment]
The Dataview inline field syntax is supported if you opt to use dataview as datasource. However this will make your project as `read-only`.

**Comment by fzyzcjy** [comment]
I see, thanks, but I would like it to be writeable...

**Comment by Acylation** [comment]
Yeah dealing with inline field is the most painful point. Here's a long-pending request #173 about this, for your reference.

**Comment by fzyzcjy** [comment]
Thanks, then this issue looks like a duplicate
