### ISSUE TITLE
Can only create dates from 1901-1909

### ISSUE THREAD

**Issue by W1BTR** [marcusolsson/obsidian-projects#847]
### What happened?

With a date field, day and month work fine, but for the year, as soon as I hit any number 1-9, it fills in 1901-9. I cannot change it to antoher date

### What did you expect to happen?

Setting the year

### How can we reproduce it (as minimally and precisely as possible)?

Create a date field and enter in a date

### Plugin version

1.17.2

### Obsidian version

1.5.12

### OS

Windows

**Comment by Acylation** [comment]
Yes there's some problem with the date-input. Will look into this!

**Comment by thesolarboi** [comment]
I've discovered you can put the year in first, and that will allow you to set the correct year. Then you can move to set the day and month. Annoying, but a solid work-around
