### ISSUE TITLE
The different views do not open or are difficult to open on Android

### ISSUE THREAD

**Issue by Adriz1er** [marcusolsson/obsidian-projects#858]
### What happened?

![Screenrecorder-2024-04-27-11-23-44-673](https://github.com/marcusolsson/obsidian-projects/assets/105045271/84e8c2e3-1f64-4ab9-9ab2-f47e4d0c4d9e)

### What did you expect to happen?

Open view with one click

### How can we reproduce it (as minimally and precisely as possible)?

Open a project and try to change the view

### Plugin version

1.17.3

### Obsidian version

1.5.12

### OS

Other

**Comment by Dars90** [comment]
I noticed this too. Please fix this.

**Comment by Acylation** [comment]
Just got access to an android device. Will test and check later.

**Comment by rajanpatel022** [comment]
Yes same problem here, can't switch.
