### ISSUE TITLE
Moving collumns around in a new window.

### ISSUE THREAD

**Issue by Vulpes4** [marcusolsson/obsidian-projects#859]
### What happened?

I can't move collumns around, when using Projects in a new window.

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open Projects
2. Right click on the tab -> Move to new window
3. Click on Maximize (oddly enough it works when the window is not maximized)
4. Try to move collumns around

### Plugin version

1.17.3

### Obsidian version

1.5.12

### OS

Windows

**Comment by Acylation** [comment]
Wow so weird. Confirmed that on maximized window this is a problem. Thanks for reporting and will find out a fix!

**Comment by Acylation** [comment]
OKay that's an existing problem earlier than v1.17.1. When the pop-out window got full sized, all components that using svelte-dnd-action got stuck; while in the new window, the sortable.js based view tab sorting won't work either.
