### ISSUE TITLE
When Clicking on note name in Table view creates a new note instead

### ISSUE THREAD

**Issue by Tricksturdoesstuff** [marcusolsson/obsidian-projects#862]
### What happened?

I clicked on the name of the note, such as "Art Stands Apart", but it just created a new note in my vault entirely with the same title. The files in question are from the Omnivore Plugin.

![image](https://github.com/marcusolsson/obsidian-projects/assets/73765129/968c80fa-197f-401a-af45-996792030e17)

My folder structure
![image](https://github.com/marcusolsson/obsidian-projects/assets/73765129/48e135d1-47e5-4721-bc31-342b110d5d77)

### What did you expect to happen?

I expected to be able to see the note I was clicking on. The table can even see the properties, so I know it's seeing it. 

### How can we reproduce it (as minimally and precisely as possible)?

Here are my project settings. I only have a few plugins installed at the moment. 
![image](https://github.com/marcusolsson/obsidian-projects/assets/73765129/deba8e55-6248-43fa-a48e-7a9644b2024c)

### Anything else we need to know?

Here is an example Properties of the note mentioned above, if that's important here.
![image](https://github.com/marcusolsson/obsidian-projects/assets/73765129/6fc5851d-143e-424c-ad32-01f84abe428b)

### Plugin version

1.17.3

### Obsidian version

1.5.12

### OS

Windows

**Comment by Acylation** [comment]
Thanks this must be an regression issue of #821. Previously the link is in the scheme of `[[path|name]]` so the locating won't fail, but the sorting will be affected if the notes are in various folders (see #820).

We need to resolve the link destination manually based on the `path` field. Thanks for reporting!

**Comment by Acylation** [comment]
Could you please confirm if the link in Board / Gallery / Calendar views behaves normally if you use any?

**Comment by Tricksturdoesstuff** [comment]
It seems to work properly on the other views, strangely enough.

**Comment by Acylation** [comment]
Sorry that I didn't successfully reproduce this. However, to eliminate the problem, I decide to revert the previous modification, that is, the path info is now back to the name field. You can test if the problem persists in the coming release 1.17.4.
