### ISSUE TITLE
Could not change the property at one time 

### ISSUE THREAD

**Issue by yoghurtdewdew** [marcusolsson/obsidian-projects#868]
### What happened?

<img width="419" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/63794438/3703bc1c-99a0-4645-b0ba-caa2dc040a74">

### What did you expect to happen?

Could not change the property at one time: text → date & time

### How can we reproduce it (as minimally and precisely as possible)?

Some of the notes may do not have any property. If some notes have that property, it may be text property come from templater plugin. And I want to change all the text property of the notes in the same folder into date & time property so as to look them in the calendar view. I want this feature to make it at one time instead of one by one, now it showed  couldn’t and I don't know why.

### Plugin version

1.17.3

### Obsidian version

1.5.12

### OS

macOS

**Comment by Acylation** [comment]
Thanks for bumping. This has been requested and long-hanging, see #320. I'll close this issue as duplicate and please track the dev progress there. The date&time field support will be add in one or two minor versions, then changing types between them would become possible.
