### ISSUE TITLE
In Calendar view cannot open a note (video included)

### ISSUE THREAD

**Issue by rajanpatel022** [marcusolsson/obsidian-projects#901]
### What happened?

As soon as I click on any note in calendar view, screen got black 

https://github.com/marcusolsson/obsidian-projects/assets/112935185/16a596a3-3754-48ac-9258-a039c9ba0354

### What did you expect to happen?

To be fixed 

### How can we reproduce it (as minimally and precisely as possible)?

I don't know 

### Plugin version

1.17.3

### Obsidian version

1.5.12

### OS

Other

**Comment by Acylation** [comment]
May be solved by #898.
