### ISSUE TITLE
Board Column Creation Issue

### ISSUE THREAD

**Issue by wjohnallen** [marcusolsson/obsidian-projects#909]
### What happened?

Regardless of device, I am unable to create a new column in the Board view. 

### What did you expect to happen?

I expected a new column to be created when entering the name and pressing Enter. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a new project, add the Board view, and then attempt the column creation. 

### Anything else we need to know?

I attempted this in my preexisting vault and also a new one with only this plugin installed. Result was the same. 

### Plugin version

1.17.3

### Obsidian version

1.6.3

### OS

Windows

**Comment by Acylation** [comment]
This was just addressed in #865. Board view needs a `status` field to store the `column` info. Please select a status field first, then try to add column again. Improvements on helping text will be made recently. Thanks for raising this!

**Comment by wjohnallen** [comment]
Ahh! Thank you. What I did not realize was that the other views are based on the Table fields. Your comment led me to that understanding.
