### ISSUE TITLE
Kanban status field not available

### ISSUE THREAD

**Issue by creativefibro** [marcusolsson/obsidian-projects#916]
### What happened?

The necessary field, blog-stage is in the metadata. It is showing in the include fields list but not in the status drop down as shown in the recorded gif. 
![CleanShot 2024-07-05 at 5  26 12](https://github.com/marcusolsson/obsidian-projects/assets/39191327/58b09242-5302-4b4e-91d3-62fb6cbcbb3e)

### What did you expect to happen?

I expected the blog-stage option to be in the drop down list so I could use it as the option for the column headers.

### How can we reproduce it (as minimally and precisely as possible)?

Create a project and see if all the metadata options are there to select.

### Plugin version

1.17.3

### Obsidian version

1.6.5

### OS

macOS

**Comment by kitmonkman** [comment]
I'm experiencing the same problem. For me, it appears to relate to fields that are already configured with multiple-choice  options (created via Meta-Bind plugin).

**Comment by kitmonkman** [comment]
So, it appears that all the properties that aren't available in the Kanban board are the ones marked with a '+' in the following screenshots.

 ![Screenshot 2024-07-30 at 1 51 20 PM](https://github.com/user-attachments/assets/1452cc55-cc2d-466b-933d-d72d982388b8)
![Fields](https://github.com/user-attachments/assets/54c6bc1e-214f-48b9-a3a3-21300295d097)

**Comment by Acylation** [comment]
Grouping kanban cards by list / tags / multitext fields is not yet supported. There is an existing request and associated discussions noted down in #117.

**Comment by Acylation** [comment]
Close as duplicate
