### ISSUE TITLE
Calendar Dates are Wrong

### ISSUE THREAD

**Issue by Axl-t** [marcusolsson/obsidian-projects#923]
### What happened?

Calendar has dates for August 26 - October 6, 2024 when it should be for September 2 - September 29 (I think?).

It's not just the calendar label that's wrong, but also it's scheduling the notes to these incorrect dates as well. 

![Immagine 2024-07-17 072529Calendar](https://github.com/user-attachments/assets/4aa20bcf-1f92-4429-8b2a-06846023e0ac)

### What did you expect to happen?

That the dates on a calendar would actually be accurate. 

### How can we reproduce it (as minimally and precisely as possible)?

Problem seems to only be happening on the Monthly view 

### Plugin version

1.17.3

### Obsidian version

v1.6.3

### OS

Windows

**Comment by Acylation** [comment]
Sorry for the inconvenience. I would need a full screenshot to better identify the problem. To be more specific, what's your current locale (Obsidian language & computer locale) and if the start-of-week of Projects plugin being set to "Monday"?

**Comment by Acylation** [comment]
Related to #877
