### ISSUE TITLE
Note open behavior difference between "Add note" click action vs. "Create note" hotkey

### ISSUE THREAD

**Issue by maximbelyayev** [marcusolsson/obsidian-projects#929]
### What happened?

"Add note" click action (e.g., creating a new note/row in 'Table' view) does not open the note, and keeps you in the current view. Whereas "Create note" hotkey action ('Projects: Create note') redirects you out of the current view to open the note in a new tab.

### What did you expect to happen?

"Create note" hotkey action ('Projects: Create note') creates the note, does not open the note, and keeps you in the current Obsidian projects view.

### How can we reproduce it (as minimally and precisely as possible)?

Execute "Create note" hotkey action in any Obsidian projects view. Compare to executing click of "Add note".

### Plugin version

1.17.4

### Obsidian version

1.6.7

### OS

macOS

**Comment by Acylation** [comment]
Thanks for reporting!
