### ISSUE TITLE
adding excluding option in the project setting for excluding a note from the project

### ISSUE THREAD

**Issue by erfanbashar1q** [marcusolsson/obsidian-projects#93]
### What would you like to be added?

Hello again,

as we talk about it in the discussion, it will be great to add a feature to the plugin for completely exclude one or some notes from the project.

You told me that:
" Oh, so you're looking to completely exclude a note from the project rather than to just hide it for a view?

If we added a Exclude notes from project section under Project settings, would that work for you?"

in response: yeah, completely true and it will be worked surely.

### Why is this needed?

some notes in a folder maybe just have some dataview queries, or maybe for some other reasons, and because of this it is better not to showing them in the project.

**Comment by danieltomasz** [comment]
would it be possible to extend this  feature to exclude a folder or pattern like
`subfolder-with-excluded-notes\*`?

**Comment by marcusolsson** [comment]
I don't see an issue with extending it to folders. Could you create another issue so we can track it separately?
