### ISSUE TITLE
Render images in Board view

### ISSUE THREAD

**Issue by CristolGDM** [marcusolsson/obsidian-projects#935]
### What would you like to be added?

Something similar to Gallery covers, but in Board view

Currently if I had the image field, the string is used:

<img width="1114" alt="Screenshot 2024-08-08 at 17 49 15" src="https://github.com/user-attachments/assets/7bed9c7e-77b1-43f3-a251-7ab9b2d835d1">

Rendering it as an image would be much much nicer

### Why is this needed?

Increases production value

Easier to parse information when working on a large project

**Comment by Acylation** [comment]
Actually you can. In table view, find the `image` column, and configure this field via the three-dot dropdown to allow the richtext formatting. Internal links will be rendered instantly, however, if you want to include web links, currently you can achieve this by wrapping it up in the format `![caption](weblink)`

**Comment by CristolGDM** [comment]
@Acylation That's perfect :) Thanks, let me close this issue
