### ISSUE TITLE
Projects are not synced between devices...

### ISSUE THREAD

**Issue by HKohlhoff** [marcusolsson/obsidian-projects#943]
### What happened?

I use obsidian on Mac, iPad and iPhone. On all devices I have installed the projects-plugin and added a Projekt on the Mac. But is not showing up on the other devices and vice versa.
I have set obsidian sync to sync all types of files.
Is this a bug or just something projects-plugin cannot do, in which case I can not really use it... otherwise I must always keep the devices in sync by hand...

### What did you expect to happen?

see above

### How can we reproduce it (as minimally and precisely as possible)?

see above

### Plugin version

1.17.4

### Obsidian version

1.6.7

### OS

macOS

**Comment by HKohlhoff** [comment]
In the discord-forum I got this very important info:
_im not sure that plugins should be saving to the ./obsidian/plugins/<plugin>/data.json file if they expect their files to be synced 
obsidian sync excludes it, as does the default git setup
other plugins store data they want to sync between devices in /.<my-plugin>/data.json 
**so may be worth trying to make devs aware of that**
this isnt the first time ive seen this issue due to using the data.json file for data ppl expect to sync for a plugin

=> this means: I can not use the plugin until this issue is fixed. Because it is not a good way to change the sync-service just because one plugin isn't working correctly. 
This is very sad, because I'd love to use it for my publication-projects...

**Comment by HKohlhoff** [comment]
I have now checked the sync-protocol and there it is: obsidian-sync does sync the files:

<img width="600" alt="Bildschirmfoto 2024-09-06 um 13 12 43" src="https://github.com/user-attachments/assets/82ffc2a4-1b39-485e-9cb5-2ba917dd1205">

so why makes the plugin no use of the new file, even when you completely close and re-open the obsidian-app

**Comment by gonzaloyamama** [comment]
"so why makes the plugin no use of the new file, even when you completely close and re-open the obsidian-app" 

What does that mean? I've read the sentence like 10 times and have no idea what you're trying to say. Did you solve the issue somehow? If so, could you help? I'm having the same issue.

**Comment by HKohlhoff** [comment]
I wanted to say the following wit the sentence (sorry, it is was not clear English, but I am German and tried my best)

I see that the json-file, said to contain of the data of all the projects being set up in the one device, is synced by obsidian-sync (show by the screenshot of the sync-activities).
I wondered, why the plugin does not react on the new information when after the sync new data / projects an in the newly sync file. 

Does this make it clearer to you?

**Comment by Aleksandrai-ai** [comment]
Hey, I guess the same issue here, just between windows laptop and android mobile doesn't work.

The whole Obsidian content is sync, but when on the mobile I added Projects plug in, it doesn't see any project and suggesting to create a new one or use the template.

I restarted, I checked all the updates, I googled it any info - found nothing. 
I am a psychologist, so no special coding skills here, but did all what's in my power, cause I like the app and plugin a lot - it's super helpful in my work. 

Any help? 
The Projects app is one of the huge reasons why I want to use Obsidian, but if there is no sync between devices, I would need to change the app, and I don't want to do that :(

**Comment by HKohlhoff** [comment]
Hi,
this is my final finding and how I live with it...

First of all: the json-file with all the information of the projects is synchronized by Git and also by Obsidian sync. 
At the end I have the projects right on all devices :-)

What I think is important: 
1) to have the projects page open only on one device at a time
2) when you closed the page on the one device and open it on the other - just give it a little time (speaking of seconds).
3) if the actual page then isn't showing up: goto to settings an deactivate the projects-plugin and after a few seconds re-activate it (activate - not delete!)

At least in my cases this works.
I assume the plugin is not always updating correctly, but when newly activated, it reads in the latest version. 

Good luck and greetings...

**Comment by HKohlhoff** [comment]
My be one day the developer looks into the refresh of the plugin to make it even better :-)

**Comment by javiavid** [comment]
+1 
windows 11, ios 18. Obsidian 1.8, Projects 1.17.4
