### ISSUE TITLE
Can't Add Multiple Links in a Field

### ISSUE THREAD

**Issue by kurisocat** [marcusolsson/obsidian-projects#953]
### What happened?

Linking multiple notes in a text field doesn't work. 
![image](https://github.com/user-attachments/assets/ad79726e-0f46-406e-a30d-7fbb70f2ea18)

### What did you expect to happen?

I'd like it to link to multiple notes. The List field can't make links unfortunately.

### How can we reproduce it (as minimally and precisely as possible)?

Add multiple links with the typical "[[_]]" formatting to a field in Projects.

### Plugin version

1.17.4

### Obsidian version

1.6.7

### OS

Windows

**Comment by kurisocat** [comment]
I guess it works as a list it just doesn't work as a direct link from the plugin itself the way text fields work.

**Comment by Acylation** [comment]
You can configure this field via table view column dropdown, and enable "richtext", that will render your links in list.

**Comment by kurisocat** [comment]
> You can configure this field via table view column dropdown, and enable "richtext", that will render your links in list.

You're so right I totally missed that my bad. I'm glad I made this post now thank you, sorry for the inconvenience.
