### ISSUE TITLE
Timeline/Calendar View not working on iPad

### ISSUE THREAD

**Issue by Saharsha-N** [marcusolsson/obsidian-projects#963]
### What happened?

The Timeline/Calendar view on Mobile (specifically iPadOS) does not work. It works normally on my PC, but when I try to view it on iPad, it just does not render.

### What did you expect to happen?

I expected for the Timeline/Calendar view to render properly like it does on a laptop, but it does not.
![IMG_0811](https://github.com/user-attachments/assets/d43e8313-ab0d-42f6-9a30-ee93d8d0eac7)

### How can we reproduce it (as minimally and precisely as possible)?

Just attempt to render the Timeline/Calendar view on an iPad. If this does not reproduce the issue, here are the list of plugins that I currently have installed:
![IMG_0812](https://github.com/user-attachments/assets/f1076231-0323-4065-a677-883c313c6e32)
![IMG_0813](https://github.com/user-attachments/assets/ab0a7e2a-de6a-40e3-ae58-22ca8a91f1a3)
![IMG_0814](https://github.com/user-attachments/assets/0f68d46c-5ba9-448d-96ac-35b5d60b8d84)

### Plugin version

1.17.4

### Obsidian version

1.7.4 (167)

### OS

Other

**Comment by Acylation** [comment]
Thanks, this is a known issue that has been reported by #939. Sorry that didn't find time to shot a fix, testing on mobile is really painful. I'll close this thread as duplicate and please track dev progress there.
