### ISSUE TITLE
Birthday Calendar

### ISSUE THREAD

**Issue by ahackel** [marcusolsson/obsidian-projects#99]
### What would you like to be added?

It would be great, if the calendar view could be used as a birthday calendar. This could be an option in the calendar view. If set the date entries would be treated as recurring every year.

### Why is this needed?

If your project is a list of people you may want to see their birthdays.

**Comment by marcusolsson** [comment]
💯

Sounds like a duplicate of #69 as a birthday is effectively a yearly recurring note/task/event.
